### ISSUE TITLE
Caldavsynchronizer 0.99.4: SSL Trust relationship not established.

### ISSUE THREAD

**Issue by linuxcrash** [aluxnimm/outlookcaldavsynchronizer#1]
Hi Guys,
Congratuliation to this very nice tool! I have an issue because I use a selfsigned certificate for my Owncloud instance as the certificate on the client is not recognized as trusted. Would there be an option to add "Import Certificate" button when the "Test Connection" recongnizes the untrusted certificate so I could kind of add this certificate to the trusted certs and with it create an exception?

Extract from the log.txt:
`System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.`

**Comment by aluxnimm** [comment]
Did you try to add the self signed cert to the Local Computer Trusted Root Certification Authorities?
You can import the cert by running the MMC as Administrator.

**Comment by aluxnimm** [comment]
app.configuration options to disable certificate validation and enable ssl3/tls12 have been implemented in 0.99.15. see readme.md
