### ISSUE TITLE
Windows XP support

### ISSUE THREAD

**Issue by internaut19** [aluxnimm/outlookcaldavsynchronizer#101]
Any chance that we can get a version that can run on Windows XP? Right now because DotNet 4.5 is a prerequisite and dotnet 4.0 is the latest version that can be installed on XP, I cannot use the plugin on Windows XP PCs.

Thansk,
Chris.

**Comment by nertsch** [comment]
No chance to get a Framework 4.0 version from us.
We are using features which are not available in framework 4.0. Furthermore the used libraries are not compatible to Framework 4.0. So it is not possible to compile a Doteet 4.0 Version just be setting a compiler switch.
Your only option is to fork the project and migrate it back to Framework 4.0.

br
Gerhard
