### ISSUE TITLE
Sync yahoo calendar

### ISSUE THREAD

**Issue by boesiii** [aluxnimm/outlookcaldavsynchronizer#103]
Hello,

I am trying to get this working with a Yahoo calendar but I get an error message when trying to test settings.  Error message "An error occurred while sending the request.  the server committed a protocol violation, Section=ResponseHeader Detail=CR must be followed by LF".  Should this work with Yahoo calendars?  How can I fix this error message?

Thanks.

**Comment by boesiii** [comment]
I am using version 1.14 with Outlook 2013

**Comment by aluxnimm** [comment]
See README.md:
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine
The server sends invalid headers. Enable the commented out option useUnsafeHeaderparsing in the app config file, see Debugging and more config options above.
