### ISSUE TITLE
Loss of calendar entries

### ISSUE THREAD

**Issue by may-bee** [aluxnimm/outlookcaldavsynchronizer#106]
Hi, I recently observed, that some of my calendar entries have been lost meanwhile. I started to analyse the log, but I could not find out anything of interest so far as the log also just states the UID, which I even do not know of the deleted items.

Interestingly, the lost calendar entries were all affected by the issue #99 and #58.
My setup: Owncloud 8.2.2 / DavDroid on Android 5.1.1 / Outlook 2013 + latest updates of OutlookCaldavSync / Outlook 2016 + latest updates of OutlookCaldavSync.
All Client sync the same calendar with two-way sync.

All lost items were created on my Android Phone coming with an invalid meeting organizer as identified in #99. Unfortunately, I could not trace back when the caldav items have been lost. Perhaps after some time with the old version or during update to 1.14.0? I do not know.

So two hyperthetical reasons why the deletion could have happend

1. Due to the fact, that I the items were causing errors on synchronization with direction server -> outlook, the items were not carefully marked to be in an errorneous state such that in the back direction (outlook -> server) they could have been deleted as they do not occur in the local outlook calendar.
2. The two OutlookCaldavSync implementations on two different clients synchronizing the same calendar in two-way configuration might conflict by any meta-data stored in the caldav items on the server causing non intended synchronization issues.

Can you deny these reasons to happen? If so, can you image any other cause, why the calendar items have been lost or how to get information when the items have been deleted such that I can start further investigations?

I currently started to create new test caldav entries to isolate the problem (if it persists with the new 1.14.2 version). No more information so far from that side.

**Comment by aluxnimm** [comment]
Hard to debug since you swtiched the versions and we made some changes regarding those issues. But we don't mark anything if you get an error with one appointment like in #99 we just try to sync again next run. We also don't delete anything when syncing back to the server in such a case. Did any of those invites have status cancelled or declined maybe? Fixed some issues with those also in 1.14.2. So best thing is to stay with one version and try to reproduce it. Maybe you accidently switched the sync mode to Outlook -> CalDav(Replicate) during your tests, then of course it deletes items which are not in Outlook.

**Comment by may-bee** [comment]
Mh no, I was the organizer and never declined/canceled these meetings.
You are right, that backtracking this problem now will be very hard, so I just thought about issues that may be occurred. Nonetheless, I will further try to reproduce this issue.

I can say for sure, that I never changed the sync mode since I intially set up synchronization.

**Comment by aluxnimm** [comment]
you also mentioned #58. maybe that could also be the cause since owncloud accepted such wrong recurrence during import but doesn't show the event anymore in the UI and throws the error when trying to fetch them.

**Comment by may-bee** [comment]
Ah thanks. This might be a good hint. Maybe I should have a deeper look at the current owncloud database and search for such entries.
