### ISSUE TITLE
Outlook 2013 and Synology NAS error 405 appers

### ISSUE THREAD

**Issue by SynoCaldaver** [aluxnimm/outlookcaldavsynchronizer#108]
Hi at all,
actually I'm useing a Synology NAS and when I will connect via CalDAVSynchronizer and https via Port 5006 the error 405 ("Response Status code does not indicate success ... The requested method PROPFIND is not allowed or the URL ...") appears. Firewall on NAS was disabled, the calendar folder is created under the web-folder and under SNMP the Level is set to high. 
What can I do?

**Comment by aluxnimm** [comment]
What url are you using? see https://www.synology.com/en-us/knowledgebase/DSM/tutorial/Application/How_to_host_a_calendar_server_using_the_Synology_NAS

should be something like https://yournasip:5006/web/Calendar/Calendarname/

**Comment by SynoCaldaver** [comment]
Thank you, I've checked all this Parameters more than ten times. Everything is ok like in the link before.The link to the Calender is ok, too. ...

**Comment by aluxnimm** [comment]
The error is shown during test connection or when trying to sync? post the full error message.

**Comment by SynoCaldaver** [comment]
The error is shown during the test Connection. When I started the Synchronisation the Sync-Report Pops up and the same error is shown in the log-text.

**Comment by SynoCaldaver** [comment]
In the calendar-folder on my NAS I can see no files. There is only one further ".DAV"-folder. In the .DAV-folder are only two files, on *.dir and one *.pag. Is this ok?

**Comment by aluxnimm** [comment]
We have other users with successful connection to Synology NAS, so it must be a server configuration issue and you need to ask for help in a synology forum maybe, because we have none to test, we can't help here.

**Comment by SynoCaldaver** [comment]
Now I see this is only under https. Under http the error is another one: "An error occured ... da die Gegenstelle nach einer bestimmten Zeitspanne nicht reagiert hat ...". Did you have any Solutions for this error? Thank's a lot!

**Comment by SynoCaldaver** [comment]
The synology users I found in the web are not useing a Synology NAS and Outlook 2013! Nowhere I've found this combination with this error via Google ...

**Comment by aluxnimm** [comment]
Sounds like a timeout issue, and it has nothing to do with the outlook client, it is a server issue. You will get same issues when trying to connect from your mobile sync app or from Thunderbird or whatever. There are alot of synology 405 method not allowed errors reported via Google, maybe similar issues.
