### ISSUE TITLE
Is a version for Outlook for Mac even possible?

### ISSUE THREAD

**Issue by zu** [aluxnimm/outlookcaldavsynchronizer#112]
Just wonder if there is a chance for a Mac version of the tool.

**Comment by nertsch** [comment]
I don't know if it is possible to get the current version of "CalDav Synchronizer" running under MacOs, because I have no knowledge of MacOs. Further I don't know if Outlook for Mac already supports Plugins.
 
In any case we will not make or maintain a seperate Mac-Version.

br
Gerhard

**Comment by aluxnimm** [comment]
not possible, see
https://sourceforge.net/p/outlookcaldavsynchronizer/features/19/

**Comment by zu** [comment]
Thanks for letting me know

**Comment by NadineThouroghby** [comment]
By the way, does anyone know another plugin for Outlook on Mac that implements CalDAV/CardDAV support? 🤔
