### ISSUE TITLE
Sync Error since 1.17 (opr 1.16)

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [aluxnimm/outlookcaldavsynchronizer#113]
Since the update to 1.17 (I must admitt, I skipped 1.16 though, so the error could have been introduced there), I am getting the following error on each sync:

    System.Runtime.InteropServices.COMException (0x80004005): Schlüsselwörter für den Inhaltsindex können für die Beschränkung nicht verwendet werden. Die Sofortsuche ist für diesen Speicher nicht aktiviert.
    bei Microsoft.Office.Interop.Outlook.MAPIFolder.GetTable(Object Filter, Object TableContents)
    bei CalDavSynchronizer.Implementation.Events.OutlookEventRepository.QueryFolder(NameSpace session, GenericComObjectWrapper`1 calendarFolderWrapper, StringBuilder filterBuilder)
    bei CalDavSynchronizer.Implementation.Events.OutlookEventRepository.GetAllVersions(IEnumerable`1 idsOfknownEntities)
    bei GenSync.Synchronization.Synchronizer`6.<SynchronizeNoThrow>d__14.MoveNext()

After this, events are not synced.
I am using outlook 2007 to sync with owncloud 8.2.2

**Comment by aluxnimm** [comment]
do you have windows search service disabled? 
see https://sourceforge.net/projects/outlookcaldavsynchronizer/

**Comment by 1337sup3rh4x0r** [comment]
The Windows Search Service is enabled and currently running.
However in the Outlook Search Settings (as described in your sourceforge link) I cannot select my main mailbox, as it is an exchange mailbox.

**Comment by aluxnimm** [comment]
We will make the filter configurable then if it leads to problems with exchange accounts. Please try 1.16.0 meanwhile it should work, since we changed the substring filtering in 1.17.0.

**Comment by 1337sup3rh4x0r** [comment]
Sounds great!
As always, thanks for the support!

**Comment by aluxnimm** [comment]
version 1.18.0 released which fixes the issues with the filter.
