### ISSUE TITLE
Outlook Toolbar position

### ISSUE THREAD

**Issue by klapperkopp** [aluxnimm/outlookcaldavsynchronizer#117]
After I restart Outlook, the addin toolbar shows up in the second row, even when there'senough space in the first toolbar row. The state does not seem to be saved.

**Comment by klapperkopp** [comment]
Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/11021127/13359922/c9cd1182-dcb6-11e5-9237-a789499eab61.png)

**Comment by aluxnimm** [comment]
Similar problem as in ticket #102. We focus on the ribbon UI starting with Outlook 2010, but if someone has time, he can fix the ToolBar state.
