### ISSUE TITLE
ArgumentNullException on 'input' parameter

### ISSUE THREAD

**Issue by minibuss** [aluxnimm/outlookcaldavsynchronizer#118]
Synchronization was working perfectly, but since few days ago, this message started apparing and now Synchronization always fail.
No change on my config, only a outlookcaldavsynchronizer update.

Client : Outlook 2013
Server : Sogo

<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>Sogo</ProfileName>
  <ProfileId>651ea876-4b28-4fb4-af03-a6454199991b</ProfileId>
  <StartTime>2016-03-01T16:57:14.569322Z</StartTime>
  <ADelta>Unchanged: 0 , Added: 0 , Deleted 0 ,  Changed 0</ADelta>
  <BDelta>Unchanged: 0 , Added: 1 , Deleted 0 ,  Changed 0</BDelta>
  <LoadErrors>
    <LoadError>
      <EntityId>/SOGo/dav/vdes/Calendar/personal/000000008A497BAC7DFCD8408A28799B3D719A30649F2000</EntityId>
      <Error>System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : input
   à System.Text.RegularExpressions.Regex.Match(String input)
   à System.Text.RegularExpressions.Regex.Match(String input, String pattern, RegexOptions options)
   à DDay.iCal.Serialization.iCalendar.RecurrencePatternSerializer.Deserialize(TextReader tr)
   à DDay.iCal.Serialization.iCalendar.DataMapSerializer.Deserialize(TextReader tr)
   à DDay.iCal.iCalParser.property(ISerializationContext ctx, ICalendarPropertyListContainer c)
   à DDay.iCal.iCalParser.component(ISerializationContext ctx, ISerializerFactory sf, ICalendarComponentFactory cf, ICalendarObject o)
   à DDay.iCal.iCalParser.icalbody(ISerializationContext ctx, IICalendar iCal)
   à DDay.iCal.iCalParser.icalendar(ISerializationContext ctx)
   à DDay.iCal.Serialization.iCalendar.iCalendarSerializer.Deserialize(TextReader tr)
   à CalDavSynchronizer.Implementation.CalDavRepository.DeserializeCalendar(String iCalData, IStringSerializer calendarSerializer)
   à CalDavSynchronizer.Implementation.CalDavRepository.TryDeserializeCalendar(String iCalData, IICalendar&amp; calendar, WebResourceName uriOfCalendarForLogging, IStringSerializer calendarSerializer, ILoadEntityLogger logger)</Error>
      <IsAEntity>false</IsAEntity>
    </LoadError>
  </LoadErrors>
  <EntitySynchronizationReports />
  <Duration>00:00:06.0117498</Duration>
</SynchronizationReport>

**Comment by aluxnimm** [comment]
the event /SOGo/dav/vdes/Calendar/personal/000000008A497BAC7DFCD8408A28799B3D719A30649F2000

cannot be parsed because of some invalid recurrence. can you attach that ics file.

**Comment by minibuss** [comment]
[000000008A497BAC7DFCD8408A28799B3D719A30649F2000.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/156994/000000008A497BAC7DFCD8408A28799B3D719A30649F2000.txt)

ics extension didn't work, I changed file extension to txt.
I modified some data to anonymized them.

**Comment by aluxnimm** [comment]
This event has an invalid RRULE and other strange coding errors. You can only delete it on the server and recreate it properly.

**Comment by evert** [comment]
The encoding is strange because it's vcalendar 1.0

**Comment by aluxnimm** [comment]
ok our used dday.ical library can't  parse those and sogo also doesn't show it correctly in the Web gui it seems.  can sabre-dav  handle it? or is there any converter available?

**Comment by evert** [comment]
We don't support it either. It's extremely rare and CalDAV actually requires v2 anyway

**Comment by minibuss** [comment]
Ok, thanks guys for the answer.
