### ISSUE TITLE
Problem with repeated tasks

### ISSUE THREAD

**Issue by Akhanto** [aluxnimm/outlookcaldavsynchronizer#119]
I have two tasks that are repeated (in german it's called Serientyp). 
One daily and one weekly. When I mark one as done with my mobile phone it's not done in Outlook. But it's duplicated with status "waiting for somebody else". 
![unbenannt](https://cloud.githubusercontent.com/assets/11016854/13598959/0799bb74-e521-11e5-9bd2-2200a1d865b1.PNG)

**Comment by aluxnimm** [comment]
what caldav server are you using? does it support recurring tasks?

**Comment by aluxnimm** [comment]
You can disable mapping of recurring tasks in mapping configuration, version 1.22.0.
