### ISSUE TITLE
Kolab CalDAV URLs do not end in / but OutlookCALDavSynchronizer forces ending in / leading to error on setup

### ISSUE THREAD

**Issue by Stormwind99** [aluxnimm/outlookcaldavsynchronizer#120]
Kolab CalDAV URLs don't end in a slash and look like http://collab.descendentstudios.com/iRony/calendars/jason.spangler%40descendentstudios.com/522c535a-4477-4385-977c-56f88d88957c 

When a user tries to enter a Kolab CalDAV URL like the above in the OutlookCALDavSynchronizer Synchronization Profile creation gives an error "The CalDav/CardDav URL has to end in a slash ('/')"

**Comment by aluxnimm** [comment]
Then just add a slash, should work then.

**Comment by evert** [comment]
Kolab's CalDAV is based on sabre/dav and they _do_ end in a slash. If you're seeing a url somewhere without a slash then I would guess that that's maybe a documentation bug.

**Comment by Stormwind99** [comment]
Adding a slash to the end does not fix it - just get an error when first trying to sync.

To get the URL, in Kolab I went to Calendar, highlighted the calendar, clicked the Gear icon, and chose "Show Calendar URL".   Is there a different way you used in testing?  Here is a screenshot.

![image](https://cloud.githubusercontent.com/assets/9441438/13620483/b6f1b354-e555-11e5-9582-409b46b1a68c.png)

**Comment by Stormwind99** [comment]
Here is the error I'm getting when trying the sync with different URLs:

`<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>The Underground</ProfileName>
  <ProfileId>a485d765-bbcb-4697-b8d0-af2003a60a65</ProfileId>
  <StartTime>2016-03-08T23:17:28.2579038Z</StartTime>
  <ADelta>Unchanged: 0 , Added: 0 , Deleted 0 ,  Changed 0</ADelta>
  <BDelta>Unchanged: 0 , Added: 2 , Deleted 0 ,  Changed 0</BDelta>
  <LoadErrors />
  <EntitySynchronizationReports>
    <EntitySynchronizationReport>
      <MappingErrors />
      <MappingWarnings />
      <AId />
      <BId>/iRony/calendars/test1.descendent%40descendentstudios.com/522c535a-4477-4385-977c-56f88d88957c/7A4F374A2614E7B21E0FB941C5CD3F93-1F14599850124EDF.ics</BId>
      <ExceptionThatLeadToAbortion>System.Exception: CalDav Ressources with contains only exceptions are NOT supported!
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IICalendar sourceCalendar, AppointmentItemWrapper target, IEntityMappingLogger logger)
   at GenSync.Synchronization.States.CreateInA`6.&lt;&gt;c__DisplayClass8_0.&lt;PerformSyncActionNoThrow&gt;b__0(TAtypeEntity a)
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.Create(Func`2 entityInitializer)
   at GenSync.Synchronization.States.CreateInA`6.&lt;PerformSyncActionNoThrow&gt;d__8.MoveNext()</ExceptionThatLeadToAbortion>
    </EntitySynchronizationReport>
  </EntitySynchronizationReports>
  <Duration>00:00:02.8437324</Duration>
</SynchronizationReport>`

**Comment by evert** [comment]
Kolab is *showing* the url without the slash, but the underlying server does have the slash. The error you got is unrelated.

**Comment by aluxnimm** [comment]
the error means that the event
/iRony/calendars/test1.descendent%40descendentstudios.com/522c535a-4477-4385-977c-56f88d88957c/7A4F374A2614E7B21E0FB941C5CD3F93-1F14599850124EDF.ics

is a recurrence exception without the master event and we can't  map those. the ics file should also contain the master event with the recurrence rule.

**Comment by aluxnimm** [comment]
According to the rfc:
 Calendar components with the same UID property value, in a given
   calendar collection, MUST be contained in the same calendar object
   resource.  This ensures that all components in a recurrence "set" are
   contained in the same calendar object resource.  It is possible for a
   calendar object resource to just contain components that represent
   "overridden" instances (ones that modify the behavior of a regular
   instance, and thus include a RECURRENCE-ID property) without also
   including the "master" recurring component (the one that defines the
   recurrence "set" and does not contain any RECURRENCE-ID property).

@Evert How should resources with only a recurrence exception and without the master event with the recurrence rule be handled?

**Comment by evert** [comment]
@aluxnimm , you basically just put the exceptions in the calendar. This is not an uncommon situation. If I create recurring event, and only invite you to one instance, you would actually get an event without a master in your inbox, so it would be good to handle this situation.

**Comment by aluxnimm** [comment]
Improved mapping and we try to reconstruct the master event to be able to sync such recurrence exceptions without master events to Outlook in release 1.23.0.
