### ISSUE TITLE
Exclude category from sync

### ISSUE THREAD

**Issue by pcr-coding** [aluxnimm/outlookcaldavsynchronizer#121]
Would be a nice feature to have the possibility to exclude Outlook categories from sync.

Analog to the "sync only appointments with this category" in the "Event mapping configuration".

##### Why is this a good feature?
If I sync Outlook's main calendar with Google Calendar and if my Outlook calendar is containing the holidays (which can be added automatically for several countries. See [here](https://support.office.com/en-us/article/Add-holidays-to-your-calendar-in-Outlook-for-Windows-f16d872f-8dad-4750-bb7c-166e72c26977)) these holidays get synced with Google too. Holidays in Outlook have their own category so it would be easy to exclude them from sync.

**Comment by nertsch** [comment]
That is already possible. The Option is just missing in the new UI, because it was forgotten during the migration to WPF. Will be included in the next release.
In the meantime you can switch to the old UI and activate it there.

br
Gerhard

**Comment by aluxnimm** [comment]
Version 1.24.0
