### ISSUE TITLE
How to run the `CalDavSynchronizerTestAutomation` project locally 

### ISSUE THREAD

**Issue by dotcom900825** [aluxnimm/outlookcaldavsynchronizer#126]
I have been trying to run the test automation project locally. At first, none of the tests can run through. Then I realize that there are some hard coded `FolderEntryId` and `FolderStoreId` in the `App.config` file: https://github.com/aluxnimm/outlookcaldavsynchronizer/blob/master/CalDavSynchronizerTestAutomation/App.config#L4. I first changed "W0858" to my local computer's NetBios name and changed the `FolderEntryId` and the `FolderStoreId` to one of my Outlook's folder's id. Now I am able to successfully run through the `TestOrganizerRoundTrip` test but others are still failing.

I wonder if I missed anything during the setup, but I can't find any doc on either Github or Sourceforge regarding this part.

I have attached the failing tests screenshot below, and hopefully can get some pointer around how to get it running properly.

![finds_matching_entities](https://cloud.githubusercontent.com/assets/1175408/14443420/f9451756-fff3-11e5-9705-bb4134ee6b65.png)
![exists_in_cal_dav](https://cloud.githubusercontent.com/assets/1175408/14443416/f941c97a-fff3-11e5-9892-1df470744e5e.png)
![create_new_in_cal_dav](https://cloud.githubusercontent.com/assets/1175408/14443417/f941e6e4-fff3-11e5-87c1-38982110afbb.png)
![test_time_range_filter](https://cloud.githubusercontent.com/assets/1175408/14443419/f943399a-fff3-11e5-8ff0-21867d02e04f.png)
![keeps_uid](https://cloud.githubusercontent.com/assets/1175408/14443418/f9423446-fff3-11e5-9500-b65c35739378.png)

**Comment by nertsch** [comment]
Hi regarding the FindMatchinEntitiesTest:
Did you specify an AppointmentIem-Folder in the app.config ?
Are there entities created via the calls in lines  InitialEntityMatcherTest:35-38 ?

br
Gerhard
