### ISSUE TITLE
ist keine zulässige Win32-Anwendung (not a valid Win32 application)

### ISSUE THREAD

**Issue by toomuchcookies** [aluxnimm/outlookcaldavsynchronizer#127]
After installation (Win 7, Outlook 2016), i get the following error message 

Name: 
Von: file:///C:/Program Files (x86)/Gerhard Zehetbauer/CalDavSynchronizer/CalDavSynchronizer.vsto

************** Ausnahmetext **************
System.BadImageFormatException:  ist keine zulässige Win32-Anwendung. (Ausnahme von HRESULT: 0x800700C1)
   bei System.Deployment.Internal.Isolation.IsolationInterop.GetUserStore(UInt32 Flags, IntPtr hToken, Guid& riid)
   bei System.Deployment.Internal.Isolation.IsolationInterop.GetUserStore()
   bei System.Deployment.Application.ComponentStore..ctor(ComponentStoreType storeType, SubscriptionStore subStore)
   bei System.Deployment.Application.SubscriptionStore..ctor(String deployPath, String tempPath, ComponentStoreType storeType)
   bei System.Deployment.Application.SubscriptionStore.get_CurrentUser()
   bei System.Deployment.Application.DeploymentManager..ctor(Uri deploymentSource, Boolean isUpdate, Boolean isConfirmed, DownloadOptions downloadOptions, AsyncOperation optionalAsyncOp)
   bei System.Deployment.Application.InPlaceHostingManager..ctor(Uri deploymentManifest, Boolean launchInHostProcess)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.IPHMProxy..ctor(Uri uri)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.get_Proxy()
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

**Comment by aluxnimm** [comment]
Did you try to execute the vsto file directly? This is no standalone application, but an Outlook addin. You just need to restart Outlook and should see the CalDav Synchronizer ribbon there.

**Comment by toomuchcookies** [comment]
The error message appears, when i load Outlook, but now i did also try to execute the vsto file on its own and it gives me the same error message.

**Comment by aluxnimm** [comment]
Did you run setup.exe and are all required frameworks installed? Maybe the Visual Studio 2010 Tools for Office Runtime are missing, you can install it manually from [Microsoft Download Link](https://www.microsoft.com/en-us/download/details.aspx?id=48217)

**Comment by toomuchcookies** [comment]
Yes, i did install using setup.exe. And i did install Visual Studio 2010 Tools for Office Runtime even though the installer did not complain about anything. 
Maybe this might be the problem: My windows is having trouble installing the latest .Net Framework 4.6 Security update..

**Comment by aluxnimm** [comment]
What windows, Outlook and .Net versions are installed?

**Comment by toomuchcookies** [comment]
Windows 7,
Outlook 2016,
.Net 4.6

**Comment by toomuchcookies** [comment]
I was able to install the security update of the .Net framework (now the version is 4.6.1), but it didn't help with my problem! Any ideas?

**Comment by aluxnimm** [comment]
Maybe some issue with the Clickonce cache, try to clear it with
`rundll32 dfshim CleanOnlineAppCache`
then reboot and install again, see ticket
#81

**Comment by toomuchcookies** [comment]
Thanks for the suggestion, i seem to have a general problem, since i am getting the same error with the suggested command:

"Problem beim Starten von dfshim

dfshim ist keine zulässige Win32-Anwendung."
Any other suggestions?

**Comment by aluxnimm** [comment]
Maybe you need to scan or repair your windows installation.
