### ISSUE TITLE
Sync mit Einstellungen / Sync with Settings

### ISSUE THREAD

**Issue by RADIOMAGAZIN** [aluxnimm/outlookcaldavsynchronizer#128]
The Software was very good: So you can sync from Campany to private Account (CALDAV). But there are 1 big Problem. If i have in the company people in My Calender like a call and i sync ist, it is o.k.

BUT: If i delete it in my private Calender (CALDVAV) they sync too and all People in the Company get my private Mailadresse. So i need a settig field where i can Sync "not with contacts".

########################################################################
Die Software ist sehr gut: Ich kann so meine Firmentermine mit meinen privaten (CALDAV) synchronisieren. Aber es gibt 1 großes Problem. Wenn ich in der Firma Mailadressen zugeordnet habe dann wird zwar sauber synchronisiert, aber:

Wenn ich in meinem privaten Kalender dann den Termin lösche wird dieser ebenfalls gelöscht und alle erhalten meine private Mailadresse. Es fehlt also in den Einstellungen eine Option: Synchronisieren ohne Kontaktdaten.

**Comment by aluxnimm** [comment]
there already exists the option Map organizer and attendees in event mapping configuration ( expand the tree view in sync profile ). just uncheck it and no attendees are synchronized.
