### ISSUE TITLE
Slow startup after installation

### ISSUE THREAD

**Issue by HinzundKunz** [aluxnimm/outlookcaldavsynchronizer#130]
After installing, outlook takes much longer to start up. The plugin manager tells me that the caldavsynchronizer plugins takes 6750 ms to load.

I have set up two calendars, two tasks, and one contacts profile (huge, over 2.000 contacts).

**Comment by nertsch** [comment]
The number of contacts should  not affect the startup time.
Could you provide a DEBUG log file?

br
Gerhard

**Comment by HinzundKunz** [comment]
I have put a debug log file here: 
https://drive.google.com/open?id=0B4l-6eALFpLYSHNJTDFXUVZMcU0
It's rather big, though, as it's my wife's computer and I had it run for a few days (I was away).
Outlook reports that the plugin takes ~ seven seconds, sometimes only ~ four.

**Comment by aluxnimm** [comment]
Is it a slow old machine with slow hard drive? Just tested with 5 profiles and takes around 2 seconds on my laptop with an ssd drive. The addin just needs to set up each sync profile and read the profile config from disk. Normally, you wouldn't start Outlook every minute, so 5secs shouldn't be a problem anyway or?
