### ISSUE TITLE
Invalid overridden instance

### ISSUE THREAD

**Issue by hhasert** [aluxnimm/outlookcaldavsynchronizer#131]
I have raised the issue before and based on suggestions removed the ones giving me a sync issue. The problem is that a series recurring meetings is created all the time and individual appointments in the series get enhanced with information in the body or even rescheduled sometimes. Whenever something is done to an instance in the series, I get the error 'Invalid overridden instance'. 

Outlook is fine with these changes, but it looks like the caldav server is rejecting them. Is it possible to create a work around by removing the instance from the series and creating an new individual appointment in its place ? It is really annoying and I miss appointments that do not sync.

**Comment by aluxnimm** [comment]
question is why it is invalid. what caldav server?  can you post an example event ics file that causes this and the corresponding sync report with the error.

**Comment by hhasert** [comment]
I am using caldavd on the raspberry Pi (calendarserver_3.2+dfsg-5+b2_armhf.deb ). I think it is based on the sources at http://calendarserver.org/.

**Comment by hhasert** [comment]
The problem is that the information in the ics files is confidential (contains company email addresses and such), so I cannot post it here. I can send you a copy to your email if you like,

**Comment by hhasert** [comment]
I get a sync report on 3 failed items and I see them also on the calendarserver :

2016-05-12 18:48:01+0000 [-] [caldav-0]  [-] [txdav.caldav.datastore.index_file#error] Invalid instance 20160426T110000Z when indexing aabd4444-0a43-494a-849c-b84a5fb5d06a.ics in <txdav.caldav.datastore.file.CalendarStubResource object at 0x7509ea90>
2016-05-12 18:48:03+0000 [-] [caldav-0]  [-] [txdav.caldav.datastore.index_file#error] Invalid instance 20160426T080000Z when indexing 84764b18-d325-45e3-9891-32ddfb6778c7.ics in <txdav.caldav.datastore.file.CalendarStubResource object at 0x7505d930>
2016-05-12 18:48:03+0000 [-] [caldav-0]  [-] [txdav.caldav.datastore.index_file#error] Invalid instance 20160509T073000Z when indexing bb2bc433-a086-455e-be47-8c344a3ab01a.ics in <txdav.caldav.datastore.file.CalendarStubResource object at 0x75011630>

**Comment by aluxnimm** [comment]
just replace the email adresses and names

**Comment by hhasert** [comment]
From where do you want the ics file ?

**Comment by aluxnimm** [comment]
when possible from outlook and from the server and the sync report

**Comment by hhasert** [comment]
I open the sync report, click on the first error and send that as ics file to my email. Would that give you the outlook one ?

**Comment by aluxnimm** [comment]
when you click on server Id it is the server one when you click on outlook id the corresponding outlook appointment opens and you can export/send it as an ics file from outlook

**Comment by hhasert** [comment]
Server id is empty, only outlook id has a value

**Comment by aluxnimm** [comment]
ok then only the  outlook part.  thought it was a modification  abd not a newly created item.

**Comment by hhasert** [comment]
BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 14.0 MIMEDIR//EN
VERSION:2.0
METHOD:REQUEST
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16011028T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010325T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;CN="**removed**";RSVP=TRUE:mailto:**removed**
**Other attendees removed**
CLASS:PUBLIC
CREATED:20160512T185709Z
DESCRIPTION:**removed**\n
DTEND;TZID="W. Europe Standard Time":20160419T140000
DTSTAMP:20160503T104410Z
DTSTART;TZID="W. Europe Standard Time":20160419T130000
EXDATE;TZID="W. Europe Standard Time":20160419T130000
LAST-MODIFIED:20160512T185709Z
LOCATION:Webex / Call
ORGANIZER;CN="**removed**":mailto:**removed**
PRIORITY:5
RRULE:FREQ=WEEKLY;COUNT=11;BYDAY=TU
SEQUENCE:3
SUMMARY;LANGUAGE=nl:Subject of the meeting...
TRANSP:OPAQUE
UID:**removed**
X-ALT-DESC;**removed**
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MS-OLK-APPTSEQTIME:20160412T064833Z
X-MS-OLK-CONFTYPE:0
BEGIN:VALARM
TRIGGER:-PT15M
ACTION:DISPLAY
DESCRIPTION:Reminder
END:VALARM
END:VEVENT
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:20160512T185709Z
DESCRIPTION:26/4 > ** removed ** \n
DTEND:20160426T120000Z
DTSTAMP:20160426T090756Z
DTSTART:20160426T110000Z
LAST-MODIFIED:20160512T185709Z
PRIORITY:5
RECURRENCE-ID:20160426T110000Z
SEQUENCE:2
TRANSP:OPAQUE
UID:**removed**
X-ALT-DESC;**removed**
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
END:VEVENT
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:20160512T185709Z
DESCRIPTION:**removed**/n
DTEND:20160503T120000Z
DTSTAMP:20160503T104412Z
DTSTART:20160503T110000Z
LAST-MODIFIED:20160512T185709Z
LOCATION:Webex / Call
PRIORITY:5
RECURRENCE-ID:20160503T110000Z
SEQUENCE:4
SUMMARY;LANGUAGE=nl:Subject of the Meeting....
TRANSP:OPAQUE
UID:**removed**
X-ALT-DESC;BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 14.0 MIMEDIR//EN
VERSION:2.0
METHOD:REQUEST
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16011028T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010325T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;CN="**removed**";RSVP=TRUE:mailto:**removed**
**Other attendees removed**
CLASS:PUBLIC
CREATED:20160512T185709Z
DESCRIPTION:**removed**\n
DTEND;TZID="W. Europe Standard Time":20160419T140000
DTSTAMP:20160503T104410Z
DTSTART;TZID="W. Europe Standard Time":20160419T130000
EXDATE;TZID="W. Europe Standard Time":20160419T130000
LAST-MODIFIED:20160512T185709Z
LOCATION:Webex / Call
ORGANIZER;CN="**removed**":mailto:**removed**
PRIORITY:5
RRULE:FREQ=WEEKLY;COUNT=11;BYDAY=TU
SEQUENCE:3
SUMMARY;LANGUAGE=nl:Subject of the meeting....
TRANSP:OPAQUE
UID:**removed**
X-ALT-DESC;**removed**
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MS-OLK-APPTSEQTIME:20160412T064833Z
X-MS-OLK-CONFTYPE:0
BEGIN:VALARM
TRIGGER:-PT15M
ACTION:DISPLAY
DESCRIPTION:Reminder
END:VALARM
END:VEVENT
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:20160512T185709Z
DESCRIPTION:26/4 > ** removed ** \n
DTEND:20160426T120000Z
DTSTAMP:20160426T090756Z
DTSTART:20160426T110000Z
LAST-MODIFIED:20160512T185709Z
PRIORITY:5
RECURRENCE-ID:20160426T110000Z
SEQUENCE:2
TRANSP:OPAQUE
UID:**removed**
X-ALT-DESC;**removed**
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
END:VEVENT
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:20160512T185709Z
DESCRIPTION:**removed**/n
DTEND:20160503T120000Z
DTSTAMP:20160503T104412Z
DTSTART:20160503T110000Z
LAST-MODIFIED:20160512T185709Z
LOCATION:Webex / Call
PRIORITY:5
RECURRENCE-ID:20160503T110000Z
SEQUENCE:4
SUMMARY;LANGUAGE=nl:Subject of the meeting....
TRANSP:OPAQUE
UID:**removed**
X-ALT-DESC;**removed**
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MS-OLK-APPTLASTSEQUENCE:3
X-MS-OLK-APPTSEQTIME:20160412T064833Z
X-MS-OLK-AUTOSTARTCHECK:FALSE
X-MS-OLK-CONFTYPE:0
BEGIN:VALARM
TRIGGER:-PT15M
ACTION:DISPLAY
DESCRIPTION:Reminder
END:VALARM
END:VEVENT
END:VCALENDAR

X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MS-OLK-APPTLASTSEQUENCE:3
X-MS-OLK-APPTSEQTIME:20160412T064833Z
X-MS-OLK-AUTOSTARTCHECK:FALSE
X-MS-OLK-CONFTYPE:0
BEGIN:VALARM
TRIGGER:-PT15M
ACTION:DISPLAY
DESCRIPTION:Reminder
END:VALARM
END:VEVENT
END:VCALENDAR

**Comment by hhasert** [comment]
Took quite a bit of cleansing though ;-)

**Comment by hhasert** [comment]
I think the organizer creates it and then modifies it with the agenda. I see most issues when instances are modified after the sequence is created.

**Comment by aluxnimm** [comment]
can you check if the setting create events on server in UTC in event mapping configuration makes any difference?

**Comment by hhasert** [comment]
It was checked during the errors, but I now unchecked it and I do not seem to get the error. I will experiment a bit.

**Comment by aluxnimm** [comment]
better leave it unchecked  then. it is only needed for servers which have problems with windows timezone definitions and causes also problems with dst changes.

**Comment by hhasert** [comment]
Ok, it seems to be the cause of the errors. I will leave it unchecked and see if the errors do not return. When I check it and sync I immediately get the error, uncheck and status is ok. So that must be it. Thanks !! It solves a lot of curses every 30 minutes on a sync.
