### ISSUE TITLE
Could not get property PR_SMTP_ADDRESS for adressEntry

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [aluxnimm/outlookcaldavsynchronizer#132]
Hi there,
I am currently seeing a warning with one event in my calender:

    <?xml version="1.0" encoding="utf-16"?>
    <SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <ProfileName>OC</ProfileName>
      <ProfileId>8e3d561b-2db0-47ad-ac1a-990d6c76c2e9</ProfileId>
      <StartTime>2016-05-17T08:31:47.9928153Z</StartTime>
      <ADelta>Unchanged: 0 , Added: 1 , Deleted 0 ,  Changed 0</ADelta>
      <BDelta>Unchanged: 0 , Added: 0 , Deleted 0 ,  Changed 0</BDelta>
      <LoadErrors />
      <EntitySynchronizationReports>
        <EntitySynchronizationReport>
          <MappingErrors />
          <MappingWarnings>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x8004010F): Die http://schemas.microsoft.com/mapi/proptag/0x39FE001E-Eigenschaft ist unbekannt oder wurde nicht gefunden.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x8004010F): Die http://schemas.microsoft.com/mapi/proptag/0x39FE001E-Eigenschaft ist unbekannt oder wurde nicht gefunden.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x8004010F): Die http://schemas.microsoft.com/mapi/proptag/0x39FE001E-Eigenschaft ist unbekannt oder wurde nicht gefunden.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x8004010F): Die http://schemas.microsoft.com/mapi/proptag/0x39FE001E-Eigenschaft ist unbekannt oder wurde nicht gefunden.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x8004010F): Die http://schemas.microsoft.com/mapi/proptag/0x39FE001E-Eigenschaft ist unbekannt oder wurde nicht gefunden.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x8004010F): Die http://schemas.microsoft.com/mapi/proptag/0x39FE001E-Eigenschaft ist unbekannt oder wurde nicht gefunden.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
          </MappingWarnings>
          <AId>000000009A10AF670C4E4FE8BFAC47D5E70117D901000000050000004D8E2867D7DA6F4E80FE4B120C7AAD0200000000</AId>
          <BId>/owncloud/remote.php/caldav/calendars/owncloudusername/work/d03e4ddf-85c0-4608-83c7-01ea507edf2b.ics</BId>
        </EntitySynchronizationReport>
      </EntitySynchronizationReports>
      <Duration>00:00:01.0401040</Duration>
    </SynchronizationReport>

I know this is just a warning, and the event syncs just fine, but maybe this can be dealt with more nicely :)

Thanks again for your awesome plugin!

**Comment by aluxnimm** [comment]
what outlook version are you using? there shouldn't be any problem accessing this property in Outlook 2010 or higher.   If you want to ignore warnings you can set in the general options to show only sync reports with errors and not with warnings btw.

**Comment by 1337sup3rh4x0r** [comment]
Sorry for the sparse information. I am indeed using outlook 2007. Ignoring warnings is what I am doing currently.

**Comment by aluxnimm** [comment]
ok maybe you can upgrade your outlook.

**Comment by 1337sup3rh4x0r** [comment]
Tell my boss :)
