### ISSUE TITLE
Event invitation (iCloud)

### ISSUE THREAD

**Issue by foorschtbar** [aluxnimm/outlookcaldavsynchronizer#133]
Problem with an iClound event invitation. *.ics is attached.

System.ArgumentException: Der Vorgang konnte nicht abgeschlossen werden. Mindestens ein Parameterwert ist ungültig.
   bei Microsoft.Office.Interop.Outlook._AppointmentItem.Save()
   bei CalDavSynchronizer.Implementation.ComWrappers.AppointmentItemWrapper.SaveAndReload()
   bei CalDavSynchronizer.Implementation.Events.OutlookEventRepository.Create(Func`2 entityInitializer)
   bei GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.<PerformOperations>d__2.MoveNext()

[icloud.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/267776/icloud.txt)

**Comment by aluxnimm** [comment]
Can't reproduce any error with this event when syncing from my testserver. It appears in Outlook as "Cancelled: Laufen" since it is a cancelled inivte. Does this error happen everytime or was it only once? Does it make a difference if you disable sync of organizer and attendees in event mapping configuration.

**Comment by foorschtbar** [comment]
Since I got the invitation, the error repeated in each sync. In Outlook no event has been displayed. I can send you a full log and the two DAV Messages (Msg. with *icl Links and ics-File) via PM.

**Comment by aluxnimm** [comment]
yes please send everything including the config to aluxnimm at gmail.com

**Comment by aluxnimm** [comment]
Still can't reproduce the error with your data, Can you try if another declined invitation causes the same error?

**Comment by aluxnimm** [comment]
what version of the addin and outlook are you using? and what outlook folder type exchange imap  or local pst file?

**Comment by foorschtbar** [comment]
addin 2.1.2
Outlook 14.0.7163.5000 (32bit)
Exchange Folder

**Comment by aluxnimm** [comment]
And did you try with disabled sync of attendees and organizer in event mapping configuration? Just tu see if the error is because of the attendees format.

**Comment by foorschtbar** [comment]
Without mapping it works fine.

**Comment by aluxnimm** [comment]
The question is if it has something to do with your strange attendees and organizer principal urls instead of email adresses. Do you know where they come from,and if it makes any difference if you have standard attributes like  ORGANIZER;CN=John Smith:MAILTO:jsmith@host.com

**Comment by foorschtbar** [comment]
I think that comes from Apple, as they match the email address with iCloud. But I can life without the mapping of attendees and organizer.
