### ISSUE TITLE
Addressbook synchronization with OpenX-change gives "Root element is missing" error

### ISSUE THREAD

**Issue by frankneumann** [aluxnimm/outlookcaldavsynchronizer#135]
The calendar conection to my openxchnage server works fine.
When I try to setup a connection for the address book synchronization as well I run into a "Root element is missing" exception once I select the "Kontakte" folfer during "Test connection".
Here comes the stack:
ERROR 2016-05-21 17:56:29,465 [ VSTA_Main] tions.ViewModels.ServerSettingsViewModel . MoveNext                       - Exception while testing the connection.
System.Xml.XmlException: Das Stammelement ist nicht vorhanden.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   bei System.Xml.XmlTextReaderImpl.Read()
   bei System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   bei System.Xml.XmlDocument.Load(XmlReader reader)
   bei CalDavSynchronizer.DataAccess.WebDavClientBase.DeserializeXmlStream(Stream webDavXmlStream)
   bei CalDavSynchronizer.DataAccess.WebDavClientBase.CreateXmlDocument(Stream webDavXmlStream, Uri uri)
   bei CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CalDavSynchronizer.DataAccess.WebDavDataAccess.<IsResourceType>d__5.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CalDavSynchronizer.Ui.ConnectionTests.ConnectionTester.<TestConnection>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei CalDavSynchronizer.Ui.Options.OptionTasks.<TestWebDavConnection>d__15.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CalDavSynchronizer.Ui.Options.ViewModels.ServerSettingsViewModel.<TestConnectionAsync>d__38.MoveNext()

**Comment by aluxnimm** [comment]
sounds like a wrong server url. the server answers the request with an invalid empty response
