### ISSUE TITLE
Problem syncing with tin20

### ISSUE THREAD

**Issue by PatrickGoettsch** [aluxnimm/outlookcaldavsynchronizer#136]
I tried to setup the two way communication between tine20 and caldavsync. I get this error message:

System.Xml.XmlException: Es sind mehrere Stammelemente vorhanden. Zeile 2, Position 2.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   bei System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   bei System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   bei System.Xml.XmlDocument.Load(XmlReader reader)
   bei System.Xml.XmlDocument.Load(TextReader txtReader)
   bei CalDavSynchronizer.DataAccess.WebDavClientBase.DeserializeXmlStream(Stream webDavXmlStream)
   bei CalDavSynchronizer.DataAccess.WebDavClientBase.CreateXmlDocument(Stream webDavXmlStream, Uri uri)
   bei CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CalDavSynchronizer.DataAccess.CalDavDataAccess.<GetVersions>d__18.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CalDavSynchronizer.Implementation.CalDavRepository.<GetAllVersions>d__9.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GenSync.Synchronization.Synchronizer`7.<SynchronizeNoThrow>d__17.MoveNext()

How can I solve that issue?

Best regards

**Comment by aluxnimm** [comment]
are you using the correct dav url? the server sends an invalid  xml response. can you intercept the response with a tool like fiddler and post the xml?
