### ISSUE TITLE
[Feature Request] Create a CalDav Config File

### ISSUE THREAD

**Issue by Mannshoch** [aluxnimm/outlookcaldavsynchronizer#137]
I wish to distribute Owncloud CalDav to our Club member. They all have Outlook but are all normal users which are only able to click on something.

Please add a possibility to import CallDav information with pre-set configs.

1. variant
create a filetype a user can add with a double click
like `config.ocaldav`

2. variant
Let the Installer look if a config file is available in the same directory like the Installer. If it do, Import it while installing. So I can ship a ZIp file with Installer and config to my comrades.

**Comment by aluxnimm** [comment]
This is rather difficult, similar to https://sourceforge.net/p/outlookcaldavsynchronizer/features/36/

**Comment by Mannshoch** [comment]
Thanks for the hint. but I'm afraid that this is not practicable for us. I'ts dificoult to migrate users from paper to digital and the quote for accepting these sunk to ground if they have to do more then just click on something.

**Comment by nertsch** [comment]
Since the config file is just an Xml-File you can write a script/program, which starts the installer and creates the config file afterwards.

br
Gerhard

**Comment by extremeshok** [comment]
The developer could add support for SRV dns records which would make it far easier to deploy and allow for self discovery

The user enters their email address and the program checks for a caldav SRV dns record.

eg
````
_caldav._tcp.mymaildomain.com. IN SRV 5 0 8443 caldav.myservicecompany.com.
````

> Service: caldav-server.
> Protocol: tcp
> Host: mymaildomain.com
> TTL: 14400
> Type: SRV
> Priority: 5
> Weight: 0
> Port: 8443
> Points TO: caldav.myservicecompany.com
>

**Comment by Mannshoch** [comment]
Nice Idea.

**Comment by aluxnimm** [comment]
Will have a look into it and can implement the SRV and TXT lookups for autodiscovery maybe in one of the next releases.

**Comment by aluxnimm** [comment]
Implemented autodiscovery from email address via SRV and TXT lookups, will be in next release.
