### ISSUE TITLE
CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '502' ('BadGateway')

### ISSUE THREAD

**Issue by Maki-ikaM** [aluxnimm/outlookcaldavsynchronizer#138]
i have this problem when try to sync...

```
CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '502' ('BadGateway'). Message:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
```

**Comment by aluxnimm** [comment]
what server are you using?  you need to investigate the server logs since this is a server error. does test settings work and the caldav url is correct and works in the browser?

**Comment by Maki-ikaM** [comment]
![image](https://cloud.githubusercontent.com/assets/19834992/15928993/7ec8a4e0-2e4a-11e6-8ef7-6bfd5eb4e574.png)

same settings works on "kerio connect" on android device

i'm using this server: `https://dav.poczta.home.pl/caldav/57/`

and recieve this: `The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/caldav/57/">REPORT&nbsp;/caldav/57/</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>`

**Comment by aluxnimm** [comment]
The server responds very slow, maybe some timeout issues? You can increase timeout values, see reqdme.

**Comment by Maki-ikaM** [comment]
`calDavConnectTimeout` set to `00:05:00` and still the same problem.

When I change the server address to `https://dav.poczta.home.pl/` and press 'Test Settings' program automatically changes the address to `https://dav.poczta.home.pl/caldav/57/`

My provider says that i should put `dav.poczta.home.pl` in address bar but i can't.

**Comment by aluxnimm** [comment]
can you provide a test account?

**Comment by Maki-ikaM** [comment]
Sure, give me your @

**Comment by aluxnimm** [comment]
aluxnimm at gmail.com

**Comment by aluxnimm** [comment]
no feedback.
