### ISSUE TITLE
Bad url construction when multiples calendar-home-set.

### ISSUE THREAD

**Issue by flechilla** [aluxnimm/outlookcaldavsynchronizer#139]
If the principal has multiple DAV:calendar-home-set, so the server returns something like this:
` <C:calendar-home-set xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:D="DAV:">
          <D:href>/collections/users/aff31/</D:href>
          <D:href>/collections/groups/public/</D:href>
        </C:calendar-home-set>`
So the client concatenate the href of calendar-home-set, so it makes a request to the url
 `PROPFIND /collections/users/aff31//collections/groups/public/ HTTP/1.1`. 
It should not be like that, it should perfoms the PROFIND method to the hrefs in different requests.

**Comment by aluxnimm** [comment]
What server are you using? Never seen that but should be fixed if this is valid of course.

**Comment by flechilla** [comment]
I'm using my own server implementation. That doesn't matters because my server is returning the response that I mention before, which is OK. Maybe you haven't seen the bug before because the principal that you have tried doesn't have more than 1 calendar-home.
Sorry for not reply before.

**Comment by evert** [comment]
The issue itself is valid from a CalDAV protocol perspective, but also almost nobody actually supports multiple calendar homes (I don't know anyone who does).

**Comment by aluxnimm** [comment]
ok thx for clarification. so for Autodiscovery we should check all available home-sets.

**Comment by aluxnimm** [comment]
fix will be in next release.

**Comment by aluxnimm** [comment]
included in release 2.2.0.
