### ISSUE TITLE
Add option to hook into send/receive

### ISSUE THREAD

**Issue by F21** [aluxnimm/outlookcaldavsynchronizer#141]
It would be nice if there's an option to hook into the send/receive function in outlook. That means that when outlook performs a send/receive (either manually or periodically), the synchronizer will also sync.

This will emulate the behavior of outlook synchronizing contacts and calendars for an exchange account, so that the user will not have to go to the CalDav Synchronizer tab to force synchronization.

**Comment by aluxnimm** [comment]
interesting idea. will check if this is possible but there should be some event fired when send/ receive finishes

**Comment by F21** [comment]
I wonder if it's also possible to have the synchronization task integrated as a send/receive task, so that when send/receive is executed, it is listed as one of the tasks along with the fetching/receiving from mailboxes tasks.

**Comment by aluxnimm** [comment]
No, that is not possible from a VSTO C# addin, but an event is fired and we can trigger a manual sync right after the Outlook send/receive.

**Comment by aluxnimm** [comment]
general option to trigger sync after send/receive will be in next release.

**Comment by aluxnimm** [comment]
included in release 2.2.0.
