### ISSUE TITLE
New appointment saved in google main Calender

### ISSUE THREAD

**Issue by thomasober** [aluxnimm/outlookcaldavsynchronizer#142]
I im made a Profile to a google calender created with publich access. After adding a new appointment via Outlook, the appointment is syncronised to main callender with the status public.

**Comment by thomasober** [comment]
After some time, about 30 min, the appointment will be showen in browser as object of public calender 
as well. See Image. First appointment was made via Browser, second and third was Made via Outlook.

![googlecalender](https://cloud.githubusercontent.com/assets/16097152/16454035/4a1224d6-3e0f-11e6-8dc1-b2258bf5ea0b.PNG)

**Comment by aluxnimm** [comment]
I don't really understand your problem. What is the difference between those 3 events? if you don't want events in your public account then use another private one or set the event to private.
