### ISSUE TITLE
Recurring error: event contains multiple alarms - ignoring all except first

### ISSUE THREAD

**Issue by GMTA** [aluxnimm/outlookcaldavsynchronizer#143]
Every time I open up Outlook, CalDav Synchronizer starts synchronizing and gives me this error:

> Event contains multiple alarms. Ignoring all except first.

I understand why it gives me this error. I use this calendar in three places of which Outlook is the only one that does not support multiple alarms on an event.

However, I don't think this should be an error. I have set the "Show immediately" setting to "Just errors" and I expect them to be of a severe category, e.g. connection to the server failed, unresolvable conflicts, etcetera.

Would it be possible to lower this message from an error to a warning?

**Comment by aluxnimm** [comment]
yes should be warning only. will check it and fix it for next release.

**Comment by aluxnimm** [comment]
Actually those are already only warning and no errors. What version are you using and what are your general option settings exactly?

**Comment by GMTA** [comment]
I'm using version 2.2.0.0, and I guess the relevant settings are:
* Enable Tray Icon
* Log: Sync runs with errors or warnings
* Show immediately: Just errors
* Log Level: Info

The warning pops up as a tray notification.

**Comment by aluxnimm** [comment]
ah ok. then we need to disable tray notifications for warnings when show immediately is set to errors maybe.  this setting only effects the report window atm.

**Comment by aluxnimm** [comment]
will be in next release.
