### ISSUE TITLE
error 404 with owncloud 9 contact sync

### ISSUE THREAD

**Issue by ChinnChilla84** [aluxnimm/outlookcaldavsynchronizer#145]
Hey there,

I am getting the error below when I setup a contact sync with my hosted owncloud server and outlook 2016. Calendar and Task sync are working! and under options the test for the contact profile says that it should be working, too -but it doesn't.

I have tried this on several machines now with the same result.

I have asked my provider at https://portknox.net/ to check where the problem is, but he couldn't find anything after weeks of emails. Steffen Lindner <slindner@portknox.net>

Could you perhaps get in contact with him to find out together, what the problem is? I could create a guest account for you on my server for testing if that helps.

I hope we can solve this - everything else runs smoothly!

Thank you and best regards,
Bodo Schütze <contact@bodoschuetze.de>

<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>owncloud Kontakte</ProfileName>
  <ProfileId>e040e4bf-a4ba-4e40-8254-a18669610e94</ProfileId>
  <StartTime>2016-07-15T16:38:37.799633Z</StartTime>
  <LoadErrors />
  <EntitySynchronizationReports />
  <ExceptionThatLeadToAbortion>CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '404' ('NotFound'). Message:
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"&gt;
  &lt;s:sabredav-version&gt;3.0.9&lt;/s:sabredav-version&gt;
  &lt;s:exception&gt;Sabre\DAV\Exception\NotFound&lt;/s:exception&gt;
  &lt;s:message&gt;Card not found&lt;/s:message&gt;
&lt;/d:error&gt;

   bei CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;EnsureSuccessStatusCode&gt;d__10.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequest&gt;d__9.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequestAndReadResponse&gt;d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CalDavSynchronizer.DataAccess.CardDavDataAccess.&lt;GetEntities&gt;d__15.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CalDavSynchronizer.Implementation.Contacts.CardDavRepository.&lt;Get&gt;d__6.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GenSync.Synchronization.Synchronizer`7.EntityContainer.&lt;FillIfEmpty&gt;d__11.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei GenSync.Synchronization.Synchronizer`7.&lt;Synchronize&gt;d__21.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei GenSync.Synchronization.Synchronizer`7.&lt;SynchronizeNoThrow&gt;d__17.MoveNext()</ExceptionThatLeadToAbortion>
  <Duration>00:00:01.0974417</Duration>
</SynchronizationReport>

**Comment by aluxnimm** [comment]
Did you already try with another adressbook ? Or export all vcards and reimport them?

**Comment by ChinnChilla84** [comment]
Hey!

I have set up the contact sync on 3 different machines with 3 different user's adressbooks - giving the same error on all machines (different places, networks, etc.). All are win 10 x64 with Outlook 2016 though.

**Comment by ingoratsdorf** [comment]
Outlook 2016 runs okay with SabreDav. The error is 404, not found. So what are you giving CalDAVSynchronizer for a URL? And is that a autodetect one or manually entered one? And is your owncloud correctly synching with other caldav clients, ie, do we know it's not a server  issue?

**Comment by ChinnChilla84** [comment]
I am always copying the WebCal/Dav addresses directly from my owncloud dashboard. For me this looks like this: https://chinnchilla84.portknox.net/remote.php/dav/addressbooks/users/chinnchilla84/kontakte/ which is exactly what your tool finds, when I let it autodetect the address.

Both the calendar and the task synchronisation are working correctly on all 3 machines - whereas the contact sync is not working on any of them. (same 404 error)

I have sent this to the server administrator already but he said he couldnt find anything in the logs.

**Comment by ChinnChilla84** [comment]
syncing the contacts at the same address with an android phone does work without a problem for me and another user.

**Comment by aluxnimm** [comment]
can you provide full debug log?

**Comment by ChinnChilla84** [comment]
Sure >>
[log.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/367231/log.txt)

**Comment by aluxnimm** [comment]
Those two have unusual filenames and look strange and could cause problems:
/remote.php/dav/addressbooks/users/chinnchilla84/kontakte//remote.php/carddav/addressbooks/chinnchilla84/kontakte/3dda3c3d-cff3-4d63-bd05-2157a2f4789b%2540chinnchilla84.portknox.net.vcf.vcf'

/remote.php/dav/addressbooks/users/chinnchilla84/kontakte//remote.php/carddav/addressbooks/chinnchilla84/kontakte/8fd37e59-a2f6-450c-a8d9-7d513cd1582f%2540chinnchilla84.portknox.net.vcf.vcf'

Try to identify and delete those and sync again maybe.

**Comment by ChinnChilla84** [comment]
HolyCow. I guess this is a farewell gift from 1 1/2 years of pain with Comodo OutlookDAV.

Now it is not possible to delete this contact in the dashboard. I can not delete those two contacts.
I exported the addressbook as vcf card and manually corrected the problematic contacts. But I can't import the very vcf file again in the owncloud dashboard which I got from the dashboard oO.

In Android those contacts are not available.

Any Idea, how i can fix this? 

BEGIN:VCARD
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN
PRODID:-//Sabre//Sabre VObject 3.5.0//EN
PRODID:-//Comodo OutlookDAV/V5.0
UID:/remote.php/carddav/addressbooks/chinnchilla84/kontakte/3dda3c3d-cff3-4
 d63-bd05-2157a2f4789b%40chinnchilla84.portknox.net.vcf
N:;Karleijn;;;
FN:Karleijn
ORG:;
ADR;TYPE=WORK:;;;;;;
ADR;TYPE=HOME:;;;;;;
ADR;TYPE=POSTAL:;;;;;;
EMAIL;TYPE=PREF,INTERNET:vlaardingerbroek@hotmail.com
REV:2016-04-29T07:58:15+00:00
X-MS-CARDPICTURE:ÿØÿà
X-MS-OL-DESIGN:<card xmlns="http://schemas.microsoft.com/office/outlook/12/
 electronicbusinesscards" ver="1.0" layout="left" bgcolor="ffffff"><img xml
 ns="" align="fit" area="16" use="cardpicture"/><fld xmlns="" prop="name" a
 lign="left" dir="ltr" style="b" color="000000" size="10"/><fld xmlns="" pr
 op="blank" size="8"/><fld xmlns="" prop="email" align="left" dir="ltr" col
 or="d48d2a" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" p
 rop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" p
 rop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" p
 rop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" p
 rop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" p
 rop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" p
 rop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/></card>
END:VCARD

**Comment by aluxnimm** [comment]
since the only relevant data is name abd email in this vcard just create a new card in the owncloud dashboard? or do you mean you can't  import all other cards as well? then try to import them kn outlook and sync outlook -> server to a new empty  adressbook.

**Comment by ChinnChilla84** [comment]
ok, I have exported a vcf with all contacts inside from owncloud. Then I have used a vcf splitter to get this data into outlook one by one for several hundred contacts. Then I have created a new adressbook in owncloud and set up the sync to this url.

Finally it is working. Nice way to spend 3 hours -_-

I guess I will have to do this with my other users, too - but they have more than 500 contacts oO

Do you have any idea how to do this in a more efficient way? Outlook is so damn restrictive.

Thank you so far!

**Comment by aluxnimm** [comment]
maybe import them on the phone and sync them to the server?

**Comment by ChinnChilla84** [comment]
Thx for the idea - I think going around outlook is a good idea. I'll try it soon.

My best regards!
Bodo Schütze

**Comment by ingoratsdorf** [comment]
I am not using owncloud but Tine20, which uses SabreDAV as a syn backend too.
What I did with such entries in the past is to change the UID directly in the database (owncloud in your instance). This comes at your own RISK. Should work, but hey,... as I said I am not using owncloud, so no idea how picky owncloud is with changes. You will have to change the etag or sequence field too, so clients sync again.
