### ISSUE TITLE
Invalid value for BYMINUTE in RRULE

### ISSUE THREAD

**Issue by aluxnimm** [aluxnimm/outlookcaldavsynchronizer#146]
Some of our users with SabreDAV 3.2 and latest GroupOffice report the following error with the stricter parsing:

 Response status code does not indicate success: '415' ('UnsupportedMediaType'). Message:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>3.2.0-beta1</s:sabredav-version>
<s:exception>Sabre\DAV\Exception\UnsupportedMediaType</s:exception>
<s:message>Validation error in iCalendar: Invalid value for BYMINUTE in RRULE</s:message>
</d:error>

Example vevent reported on Sourceforge was;

BEGIN:VEVENT
CLASS:PUBLIC
DTEND;TZID=W. Europe Standard Time:20160714T093000
DTSTAMP:20160714T135335Z
DTSTART;TZID=W. Europe Standard Time:20160714T083000
PRIORITY:5
RRULE:FREQ=WEEKLY;BYDAY=TH
SEQUENCE:0
SUMMARY:test
TRANSP:OPAQUE
UID:c9df35fd-a281-4943-86a5-c0368fb04010
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
END:VEVENT

Since it doesn't even contain BYMINUTE I guess the problem is the VTIMEZONE maybe:
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU;BYHOUR=3;BYMINUTE=0
TZNAME:Mitteleuropäische Zeit
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0
TZNAME:Mitteleuropäische Sommerzeit
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE

@evert Anything wrong with that regarding the icalendar specs?

**Comment by aluxnimm** [comment]
related ticket on SF
https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/336/

**Comment by evert** [comment]
No this is definitely our bug. We're working on a new release.

**Comment by evert** [comment]
We have an update for sabre/vobject, so if people have a composer-based installation, they can just run composer update to get the latest fixes.

**Comment by aluxnimm** [comment]
Thx for fast reply and fix!
