### ISSUE TITLE
Task alarm is not supported

### ISSUE THREAD

**Issue by tomas-chrastina** [aluxnimm/outlookcaldavsynchronizer#150]
Hi,

it would be nice to implement support for **task alarms**.

- Server calendar in OwnCloud
- Different e-mail clients are synchronizing calendar/tasks: Thunderbird, Outlook, WebMail, ...

As for now in Outlook after synchronization we've got warning:
```
<MappingWarnings>
    <string>Task alarm is not supported. Ignoring.</string>
</MappingWarnings>
```

This means:
1. If we set reminder/alarm, Outlook won't get it
2. On any change from Outlook (even title), reminder is cleared on server side

--
Best regards,
Tomas.

**Comment by aluxnimm** [comment]
relative task alarms are supported. can you provide an ics file of a vtodo with an alarm that triggers that warning?

**Comment by aluxnimm** [comment]
Added support for task alarms with absolute date/time triggers, will be in next release.
