### ISSUE TITLE
Kalendereinladung Verdreifachung via Outlook

### ISSUE THREAD

**Issue by R-Nimmersatt** [aluxnimm/outlookcaldavsynchronizer#153]
Hallo zusammen,

erst mal vielen dank für dieses klasse Programm. Wir setzen es schon seit geraumer Zeit ein um Outlook-Clients mit unserem Zimbra-Server kommunizieren zu lassen. :+1: 

Einziges Problem welches wir bis dato noch nicht lösen konnten sind Verdreifachungen bei Einladungen welche über die Outlook-GUI erstellt werden.

Die erste Einladung stammt dann passender weise von:

`X-Mailer: Microsoft Outlook 16.0`

Die weiteren Einladung werden automatisch bei der Synchronisation mit dem calDAV-Server generiert, je nach dem ob das sofort oder nach einem Intervall passiert, können die Einladungen Nr. 2 und Nr. 3 mit ein paar Minuten Verzögerung beim Empfänger eintreffen.

Absender sind hier jeweils

`X-Mailer: Zimbra 8.6.0_GA_1153 (CalDavSynchronizer/2.3)`

Wichtig ist vielleicht noch zu erwähnen das wir E-Mail-Aliase im Einsatz haben. So gibt es sowohl vor dem @-Zeichen zwei Möglichkeiten als auch zwei TLD's welche nur Aliase fungieren.

Grüße
R. Nimmersatt

PS.: Ich habe noch ein altes Ticket ausgegraben welche von Termin-Duplikationen handelt: https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/115/

**Comment by aluxnimm** [comment]
Danke!

Die Frage ist, warum Zimbra Einladungen versendet? Wird die Set SCHEDULING-AGENT=CLIENT als Option verwendet? Unterstützt Zimbra das beim Organizer?

Weiters haben wir die neue Option Cleanup duplicate events after each sync run. Bitte damit mal testen.

**Comment by aluxnimm** [comment]
some fixes in 2.7.0. and option use global appointmentid as uid should also help in your scenario
