### ISSUE TITLE
Tasks not "done" in Outlook

### ISSUE THREAD

**Issue by starfool** [aluxnimm/outlookcaldavsynchronizer#154]
Hey there!
I love the tool. Everything seems to work fine, except one thing: the task-synchronization.
I use baikal as the server, outlook 2010 as the mail client and the newest version of caldavsynchronizer.
The problem is: Although the tasks I added via iPod touch were added to Outlook, they seem not to get the status information.
Tasks, that I marked as done (e. g. on the iPod) are shown like expected on the iPod, in the "infcloud"-Webinterface and in Thunderbird. Only Outlook doesn't mark them as "done".
Is it an outlook thing or a synchronizing problem?
Hope you are able to help. Didn't find any help for this...

---
Jetzt habe ich gesehen, dass ihr auch Deutsch versteht :D
Also in Kurzfassung: Auf anderen Geräten erstellte Aufgaben werden auch auf Outlook übertragen, aber der "erledigt" status wird offenbar nicht erkannt / nicht übermittelt / was auch immer.
Habe ich etwas verkehrt gemacht? Oder habe ich vielleicht einen kleinen Bug entdeckt? ;)

**Comment by starfool** [comment]
Habe nun Folgendes festgestellt:
Wenn ich in Outlook, Thunderbird oder Infcloud eine Aufgabe "abhake", erhält sie den Status "erledigt" und einen Fortschritt von 100%. Diesen Status übernimmt Outlook dann auch.
Der nicht übernommene Status kommt von Aufgaben, die ich auf dem iPod als "erledigt" markiert habe. Hier wird offenbar dann nur der Fortschritt auf 100% gesetzt, aber der Status nicht auf "erledigt" gesetzt.
Das scheint also eher ein Kommunikationsproblem zwischen iPod und baikal zu sein...
----
Observed the following:
When marking a task as done (checkmark) in Thunderbird, Outlook or Infcloud, the task seems to get the status "done" and a progress of 100%. When checking a task on the iPod the task only receives a progress of 100% but not the "done" status.
Seems to be a communication problem of iPod and baikal.

**Comment by aluxnimm** [comment]
Maybe we should set completed when progress is 100% anyway?

**Comment by starfool** [comment]
Could be a solution. I just thought about how it would affect the separation of progress and status. But looking at the fact, that tasks in Outlook automatically are set to 100% when clicking the checkmark, Outlook seems to mix it itself. (Tried also to set only the 100% manually and Outlook marked the task as "done".)
So if it is possible to set tasks as completed with 100% progress it should be worth a try ;)

**Comment by aluxnimm** [comment]
but outlook needs also a date for completion and we have none to set in that case when syncing from the server.  So could only use sync time which is not what one wants possibly.

**Comment by starfool** [comment]
Ah okay, I see. For me it should be okay, because nothing depends on that date. It's just for a to do list on my mini-server (Raspberry Pi). But other people may have problmes with that.
Well, maybe another server will solve the problem. I didn't try it with other ones yet.

**Comment by starfool** [comment]
I just looked at what the database entry looks like. There seems to be a completion-date:
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VTODO
CREATED:20160816T224133Z
DTSTAMP:20160817T112253Z
LAST-MODIFIED:20160817T112253Z
PERCENT-COMPLETE:100
SEQUENCE:0
SUMMARY:TK anrufen
UID:5F4A0ED0-E73D-48BE-BDBC-93825A5D9CC5
STATUS:COMPLETED
COMPLETED:20160817T132253Z
END:VTODO
PRODID:-//Inf-IT//InfCloud 0.13.1//EN
END:VCALENDAR

**Comment by aluxnimm** [comment]
Oh you edited the example, because your first comment also had STATUS:COMPLETED.
So the problem is that our library sets the missing STATUS to NEEDS-ACTION and we map that to olTaskWaiting. I will change that to olTaskComplete when there is a completed date and percent-complete at 100. This will fix your issue, will be in next release.

**Comment by starfool** [comment]
Yeah, my first comment was another database-entry with the completed status (another task), sorry :)
Sounds good, many thanks! Is it possible to donate somewhere?

**Comment by aluxnimm** [comment]
you are welcome!
you can donate via donate link in about dialog or via
https://sourceforge.net/projects/outlookcaldavsynchronizer/

**Comment by starfool** [comment]
Tried the update today, works like a charm. Thank you very much! Donation is on its way :)

**Comment by aluxnimm** [comment]
thx for confirmation and donation!
