### ISSUE TITLE
Outlook Termine werden nach der 2. Synchronisation in Outlook gelöscht!

### ISSUE THREAD

**Issue by Jo-Achim** [aluxnimm/outlookcaldavsynchronizer#155]
Zunächst vielen Dank für das Tool.

Allerdings habe ich ein großes Problem: Nach der 2. Synchronisation sind einige Kalender-Termine - hier Serien-Termine wie beispielsweise Geburtstage - gelöscht! 
Dieser Fehler tritt reproduzierbar auf und ist leicht zu verifizieren.

Test-Umgebung:
1x Outlook 2010 (32-Bit (Windows 10)) mit 'Outlook CalDAV Synchronizer' (v 2.3.1 oder v 2.4.0) sowie 1x Synology DS716+ (DSM 6.x und WebDAV-Server); jeweils aktuelle Versionen / Pakete. 
Keine VBA-Projekte in Outlook. 
Info: Bei der Installation von CalDAV wird die Meldung ausgegeben: "Connection test successfully BUT: - The specified Url does not support calendar queries. Some features like time range filter may not work!"

Test-Bedingungen / Allgemeine Vorbereitung (letzter Test: 19.08.2016 mit 'Outlook CalDAV Synchronizer' (v 2.4.0)): 
Outlook 2010 und CalDAV Synchronizer sind installiert; die Verbindung von CalDAV zum WebDAV funktioniert. Das Kalender-Verzeichnis unter WebDAV enthält keine .ics - Dateien.
Outlook.pst löschen / umbenennen damit Outlook beim Starten eine neue Outlook.pst anlegt. Dem Profile in 'CalDAV Synchronizer' nun den neuen 'Kalender' bekannt machen, ggf. den 'Cache leeren' und das "Synchronization interval (minutes)" auf "Manual only" setzen; "Synchronize items immediately after change" ist nicht selektiert. 
Unter CalDAVs "General Options" ggf. "Show reports and notify:" ggf. auf "Errors and warnings" setzen.
Alle anderen CalDAV-Einstellungen bleiben unverändert.

Test-Termine:
1. Serien-Testtermin: 23.08.2016, ganztags, z.B. "Geburtstag 08/1969", Serie: jährlich, Beginn-Datum 23.08.1969 (wichtig: vor 1970), kein Endtermin. 
2. Serien-Testtermin: 23.08.2016, ganztags, z.B. "Geburtstag 08/1970", Serie: jährlich, Beginn-Datum 23.08.1970, kein Endtermin. (Der Termin kann auch beispielsweise für den 24.08. erstellt werden.) 

Erste CalDAV-Synchronisierung ausführen. Beide Termine sind noch immer in Outlook.
Zweite CalDAV-Synchronisierung durchführen. Nun fehlt der Termin "Geburtstag 08/1969" in Outlook. Unter WebDAV sind alle Termine unverändert vorhanden (bezogen auf ihren Zustand nach der 1. Synchronisation, verifiziert mit "WinMerge"). 

Dieses Problem ist beliebig wiederholbar - auch mit der Profil-Einstellung "Outlook Wins" statt "Automatic" ('CalDAV Synchronizer's "Conflict Resolution"). 
'Outlook CalDAV Synchronizer' meldet keine Fehler oder Warnungen; der Status lautet: ok.
Änderungen von "Fix invalid settings" / "Accept invalid chars in server response" haben keinen Einfluss auf den Fehler.

Info: öffnet man nach dem Herunterladen der .ics - Dateien vom WebDAV-Verzeichnis des NAS diese per Doppelklick, werden die Termine korrekt nach Outlook importiert. Allerdings werden die geöffneten Serien am Ende der Zeile "Serie:" mit dem Zusatz "(GMT+01:00) (no TZ description)" angezeigt.

War der Fehler bis hierhin einfach, weil ein Zusammenhang mit dem Beginn-Datum des Serientermins (1969/1970) zu bestehen scheint, geht es noch etwas komplexer...

Nach Wiederherstellung der Ausgangssituation ("Test-Bedingungen / Allgemeine Vorbereitung:") werden zunächst wieder die beiden obigen Testtermine erstellt.
Des Weiteren:
3. Serien-Testtermin: 31.12.2015, ganztags, z.B. "Geburtstag 12/1969", Serie: jährlich, Beginn-Datum 31.12.1969, kein Endtermin. 
4. Serien-Testtermin: 31.12.2015, ganztags, z.B. "Geburtstag 12/1970", Serie: jährlich, Beginn-Datum 31.12.1970, kein Endtermin. 
5. Serien-Testtermin: 01.01.2016, ganztags, z.B. "Geburtstag 01/1969", Serie: jährlich, Beginn-Datum 01.01.1969, kein Endtermin. 
6. Serien-Testtermin: 01.01.2016, ganztags, z.B. "Geburtstag 01/1970", Serie: jährlich, Beginn-Datum 01.01.1970, kein Endtermin. 

Die erste CalDAV-Synchronisation bringt wieder alle Outlook-Termine in das Kalenderverzeichnis von WebDAV; die Einträge in Outlook sind vorhanden.
Mit der zweiten Synchronisation - wiederum ohne irgendwelche sonstige Änderungen o.ä. - geht wieder der Termin "Geburtstag 08/1969" verloren; aber alle übrigen Termine, auch die vom 31.12.2015 bzw. 01.01.2016 bleiben erhalten! 
D.h. ein so einfacher Zusammenhang mit dem Serien-Termin-Beginn-Datum scheint es nicht zu sein.

Zusammengefasst gehen mit der 2. Synchronisierung bei meinen Kalenderdaten mindestens 15 Termine verloren.

Gibt es einen gangbaren Workaround zum 'Termin-Verlust-Problem'? 
Steht das Problem evtl. in irgendeinem Zusammenhang mit dem "(GMT+01:00) (no TZ description)"-Problem, dass auf dem Weg von Outlook zum WebDAV-Server passieren sollte?

**Comment by aluxnimm** [comment]
do you have time range filter activated? try without if so, because synology could have problems with that.

**Comment by nertsch** [comment]
Hallo,

Der 01.01.1970 ist die "Unix-Epoch". Ich kenne Synology nicht, aber möglicherweise läuft es unter Linux und die CalDAV Implementierung verwendet irgendwelche C-Biliotheksfunktionen, die für Datümer vor dem 01.01.1970 falsche Ergebnisse liefern.
Das ist aber nur eine Vermutung.

Ohne den Time-Range-Filter sollte es jedenfalls funktionieren, denn da sollte Synology alle verfügbaren Termine melden. 
Jedenfalls sollte es mithilfe des Logfiles (im DEBUG Modus) möglich sein den Fehler zu lokalisieren. 
Falls nicht, bitte den Fehler reproduzieren (mit und ohne TimeRange-Filter) und das Logfile hier als Attachment  posten.

Gruß
Gerhard

**Comment by Jo-Achim** [comment]
Thanks / Danke, für Eure Antworten!

Ja, das Problem war der eingeschaltete "Use time range filter". Ausgerechnet diese Option hatte ich nicht getestet, weil die verlorenen Termine auch außerhalb dieses Ranges lagen und ich die Option eigentlich gebraucht hätte bzw. nutzen wollte. Insofern habe ich wohl die Installationsmeldung falsch interpretiert. 

Nochmals besten Dank für die Hilfe und das tolle Tool.
