### ISSUE TITLE
Installing new version after update notification blocks UI

### ISSUE THREAD

**Issue by GMTA** [aluxnimm/outlookcaldavsynchronizer#156]
Whenever a new update of Outlook CalDAV synchronizer is released, an update window is shown with an "Install new version" button. If I click that, the UI hangs for a few seconds - presumably while downloading the installer - before proceeding with the setup. It would be better to show a progress bar or a spinner instead of locking up the UI.

**Comment by aluxnimm** [comment]
downloading 3mb shouldn't take that long but you are right of course.

**Comment by GMTA** [comment]
It shouldn't, but it still takes anywhere between 3 and 6 seconds for me :)

**Comment by aluxnimm** [comment]
Implemented async download with progressBar in dd7640b502e488053ed1eb1a0193f9345191a6c9
