### ISSUE TITLE
Countrycode prefix altered in phone numbers

### ISSUE THREAD

**Issue by AndiKreiner** [aluxnimm/outlookcaldavsynchronizer#158]
Many of my hundreds of phone numbers were altered in one of the recent syncs. I had them all with a + like +43, +44 etc. They were altered to just 43 or 44 and now no longer work when I call from my phone. I need to edit now dozens or even hundreds of phone numbers.
Extremely annoying. Renders the service worthless if it actually ruins valid data.

**Comment by aluxnimm** [comment]
what sync direction? what sync profile?  carddav or Google native api?

**Comment by AndiKreiner** [comment]
Hallo Alex
Cannot say which direction, the numbers were correct both in outlook and mobilewhat do you mean which profile?
Google native api

**Comment by aluxnimm** [comment]
Can't reproduce and has nothing to do with the synchronizer I believe.

This is a Outlook/Windows configuration issue, you need to define your correct location and country code in the Windows system panel.

Similar issue is discussed in
https://sourceforge.net/p/googlesyncmod/bugs/525/

**Comment by AndiKreiner** [comment]
My windows settings are correct and have not changed. I have not changed Outlook2007. Also it does not affect only the phone numbers of one country or phone numbers without a country code. It has affected seemingly 30% of all phone numbers of various country codes that had a plus to indicate country code. What has changed is the synchronizer. 

And very odd: I have now spent 2 hours correcting all numbers in Outlook. Forced several synchs. But none of the corrected numbers made their way to the mobile phone (via GMAIL to iPhone).

 

Von: Alex Nimmervoll [ <mailto:notifications@github.com> mailto:notifications@github.com] 
Gesendet: 22 August 2016 22:24
An: aluxnimm/outlookcaldavsynchronizer
Cc: AndiKreiner; Author
Betreff: Re: [aluxnimm/outlookcaldavsynchronizer] Countrycode prefix altered in phone numbers (#158)

 

Can't reproduce and has nothing to do with the synchronizer I believe.

This is a Outlook/Windows configuration issue, you need to define your correct location and country code in the Windows system panel.

Similar issue is discussed in
 <https://sourceforge.net/p/googlesyncmod/bugs/525/> https://sourceforge.net/p/googlesyncmod/bugs/525/

**Comment by aluxnimm** [comment]
We didn't change anything in last versions regarding telephone numbers but we only tested google native API in Outlook versions >2010.
Did the sync upload anything to Gmail? Are the numbers correct there, check the Googl,e contacts app in the browser?  We can't control gmail -> Iphone sync and I don't have any Iphone to test.

**Comment by AndiKreiner** [comment]
The changes in Outlook regarding country code (ie. adding a + to all numbers) were NOT sync’d to Google contacts.

New contacts I added were sync to iphone like a day later. I do not know when they were synced to google contacts.

I have now merged 22 contacts in google and they were correctly updated in outlook.

 

Do you sync with icloud as well?

 

Von: Alex Nimmervoll [mailto:notifications@github.com] 
Gesendet: 23 August 2016 11:19
An: aluxnimm/outlookcaldavsynchronizer
Cc: AndiKreiner; Author
Betreff: Re: [aluxnimm/outlookcaldavsynchronizer] Countrycode prefix altered in phone numbers (#158)

 

We didn't change anything in last versions regarding telephone numbers but we only tested google native API in Outlook versions >2010.
Did the sync upload anything to Gmail? Are the numbers correct there, check the Googl,e contacts app in the browser? We can't control gmail -> Iphone sync and I don't have any Iphone to test.

**Comment by aluxnimm** [comment]
We don't have any iphone or icloud account to test atm, but others reported icloud working as server.
