### ISSUE TITLE
Reminders broken (again) in Outlook 2016/Office 365

### ISSUE THREAD

**Issue by Todo18** [aluxnimm/outlookcaldavsynchronizer#161]
While this is a fantastic add-in, we are having troubles enabling reminders within Outlook 2016. We've read the previous (dates back to 2013) issue, where .PST-files had to be explicitly set to 'show' reminders (Outlook 2013), but not only does Outlook 2016 not offer this option anymore (not in the app, nor in the settings in the Control Panel), it also doesn't seem related.

Problem: The error message 'The reminder for <X> will not appear because the item is in a folder that doesn't support reminders' shows up when an attempt is made to add a new item (with a reminder set) to a CalDAV-calendar inside Outlook 2016. The CalDAV-calendar is running on a sabre/dav webserver, and has worked before in Mozilla Thunderbird, for example. Synchronisation works as you'd expect. New items show up everywhere, deleted items are properly disposed of.

Moving the calendar from one 'folder' (.PST-file) to another does nothing to resolve the issue. The option that older versions of Outlook offered ('Show reminders...') is no longer available, and thus no solution.

Any thoughts? Many thanks!

**Comment by aluxnimm** [comment]
Use another folder type or maybe this one helps
http://answers.microsoft.com/en-us/office/forum/office_2016-outlook/outlook-2016-calendar-reminders/8f40bcdd-e3fc-4f29-acaf-544f48d63992

**Comment by Todo18** [comment]
Like we said: that option doesn't work (anymore). We think we may have found a solution, however, which may be useful for other users/the future: connecting to the server as-is, will add that CalDAV calendar (at least in our case) to the default 'Internet-subscriptions' folder, which is a special case, since you can't make it the default folder. Creating a new folder (.PST-file) via the account options, making it the default, and moving the calendar to that folder, solved the issue for us. Reminders are not only saved (as they did before ?), but are also shown.

Thanks!

**Comment by Todo18** [comment]
If anyone requires a more detailed explanation, I'll gladly provide one. :)

**Comment by aluxnimm** [comment]
if you can provide detailed steps we can add it to the readme and wiki.

**Comment by Todo18** [comment]
Okay, here goes. To fix this problem in Outlook 2013, do as follows:
1. Create a new storage folder in Outlook via the File menu, Info, Account Settings. In the Data Files tab, you can Add a new (.pst) data file. After the file has been added, Make it the default [data file], and close the dialog.
2. Go to the Calendar window, right click on the calendar that's giving you problems, and select Move Calendar. In the dialog, pick the data file that you created in the first step, and confirm.
Should do the trick!

**Comment by Todo18** [comment]
Thanks. Added detailed instructions.

 

 

Van: Alex Nimmervoll [mailto:notifications@github.com] 
Verzonden: dinsdag 6 september 2016 18:01
Aan: aluxnimm/outlookcaldavsynchronizer <outlookcaldavsynchronizer@noreply.github.com>
CC: Todo18 <porfavor19@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [aluxnimm/outlookcaldavsynchronizer] Reminders broken (again) in Outlook 2016/Office 365 (#161)

 

Closed #161 <https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/161> .

**Comment by aluxnimm** [comment]
thx! will add it.
