### ISSUE TITLE
Outlook 2007 - Tasks Sync mit falscher Zeit

### ISSUE THREAD

**Issue by blueskyfeeling** [aluxnimm/outlookcaldavsynchronizer#166]
Hallo, verwende seit kurzer Zeit outlookcaldavsynchronizer für Termine und Aufgaben. Allerdings werden die Aufgaben vom PC auf das Handy zeitlich nicht korrekt angegeben. Auf dem Handy erscheint immer 23:59 Uhr obwohl anders vorgegeben. 

Vom Handy auf den PC wird sogar gar keine Zeit übertragen.

Woran kann das liegen?

**Comment by aluxnimm** [comment]
Outlook tasks haben keine Uhrzeit sondern nur ein Datum. Beim Sync entsteht dann eben 0.00 bis 23.59 für full day.

**Comment by blueskyfeeling** [comment]
Hallo, vielen Dank für die Antwort. Mit Uhrzeit meine ich die Erinnerungszeit? Wird diese mit diesem Tool nicht berücksichtigt?

**Comment by aluxnimm** [comment]
Doch Task Alarme sollten gesynct werden. Welcher Server wird verwendet?  wie sieht ein BeispielTask als ics File aus? irgendwelche Fehler oder Warnings im Logfile?

**Comment by blueskyfeeling** [comment]
Die ganze Synchronisation läuft über Raspberry/Owncloud. Fehler gibt es meines Erachtens keine. Wenn ich in Outlook z.B. eine Aufgabe mit Beginn und Fälligkeit 19.09.2016 mit Erinnerung 19.09.2016 um 20:15 Uhr eingeben, steht auf dem Handy (Android über DAVdroid) nach Sync die Aufgabe mit Fälligkeit 19.09.2016 23:59 Uhr.

**Comment by aluxnimm** [comment]
Die Frage ist was steht in Owncloud?

**Comment by blueskyfeeling** [comment]
Sorry? Habe mich vertan. Nicht Owncloud sondern Baikal. Und in Baikal weiß ich nicht, wie ich die Daten anschauen kann,

**Comment by aluxnimm** [comment]
In dem oben beschriebenen Beispiel erzeugen wir einen Alarm 20H15M nach dem Start des Tasks, also korrekt. Vielleicht kann aber Baikal und/oder Davdroid den Alarm relativ zur Startzeit nicht richtig darstellen, sondern erwartet eine absolute Alarmzeit?

**Comment by blueskyfeeling** [comment]
Könnte sein....ich google diesbezüglich mal weiter....dennoch - vielen Dank!

**Comment by aluxnimm** [comment]
Task alarms anscheinend nicht supported in OpenTasks/Android, siehe
https://github.com/dmfs/opentasks/issues/15
