### ISSUE TITLE
after Outlook start there is a ErrorMsg displayed

### ISSUE THREAD

**Issue by haderlump22** [aluxnimm/outlookcaldavsynchronizer#168]
Followig Message is diplayed and the AddIn is deaktivated.

`Name:

Von: file:///C:/Program Files/Gerhard Zehetbauer/CalDavSynchronizer/CalDavSynchronizer.vsto

 

************** Ausnahmetext **************

System.UnauthorizedAccessException: Zugriff verweigert (Ausnahme von HRESULT: 0x80070005 (E_ACCESSDENIED))

   bei System.Deployment.Internal.Isolation.IsolationInterop.GetUserStore(UInt32 Flags, IntPtr hToken, Guid& riid)

   bei System.Deployment.Internal.Isolation.IsolationInterop.GetUserStore()

   bei System.Deployment.Application.ComponentStore..ctor(ComponentStoreType storeType, SubscriptionStore subStore)

   bei System.Deployment.Application.SubscriptionStore..ctor(String deployPath, String tempPath, ComponentStoreType storeType)

   bei System.Deployment.Application.SubscriptionStore.get_CurrentUser()

   bei System.Deployment.Application.DeploymentManager..ctor(Uri deploymentSource, Boolean isUpdate, Boolean isConfirmed, DownloadOptions downloadOptions, AsyncOperation optionalAsyncOp)

   bei System.Deployment.Application.InPlaceHostingManager..ctor(Uri deploymentManifest, Boolean launchInHostProcess)

   bei Microsoft.VisualStudio.Tools.Applications.Deployment.IPHMProxy..ctor(Uri uri)

   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.get_Proxy()

   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)

   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()`

Is a UnauthorizedAccessException, ok.
But the Details, where the AddIn can't read some Settings, 
could be better. So in can't find and correct the Settings.

**Comment by aluxnimm** [comment]
Did you install the addin as current user? Our installer doesn't work for All users deployment at the moment.

**Comment by haderlump22** [comment]
no, i installed it as "Admin" but for "All Users".

Ok i try the installation as current user.

**Comment by haderlump22** [comment]
is the same Problem. What will the addin read an can't access. its not clear describe in the errormsg. When i know what regpath or what else it would read, i can look the accessconfig and manipulate it so, that the addin can read it.

**Comment by aluxnimm** [comment]
Did you install as current user but with admin rights?

**Comment by haderlump22** [comment]
In the first Step no. But in try for the second time with Admin rights for the user....
Same Msg. I look under c:\user\name\appdata\Local. There aren't the Folder witch is created by the other users on the other Clients.
I create the Folder by Hand, but with the same Error.

**Comment by aluxnimm** [comment]
Maybe this discussion can help:
https://social.msdn.microsoft.com/Forums/windows/en-US/ef690458-22bc-4d72-a36c-773c1cc6fa15/clickonce-application-cannot-be-started-help?forum=winformssetup

**Comment by haderlump22** [comment]
Yeahhh!!! It Works....

- log off the User
- log on as admin
- delete the file %userprofile%\AppData\Local\Microsoft\Windows\UsrClass.dat from the User 
- log on as User

AddIn is now loading :-)

Thanks for the link to diskussion!
