### ISSUE TITLE
binary zip for 2.6.0

### ISSUE THREAD

**Issue by peterbeck** [aluxnimm/outlookcaldavsynchronizer#169]
is there no binary release for 2.6.0 ? I prefer downloading via github as I am using nuget packages ([link](https://winpkg.foo.li/src/?specialType=singlePackage&id=outlookcaldavsync&version=2.5.1)) and don't like the sourceforge mirros. will there be no further binary releases on github or was it just an "accident" ?

**Comment by aluxnimm** [comment]
please use 2.6.1 since 2.6.0 had issues with the task cache.

**Comment by peterbeck** [comment]
ah sorry, did not recognize there is already an update. thanks a lot!
