### ISSUE TITLE
groups / distribution list feature

### ISSUE THREAD

**Issue by alexcha** [aluxnimm/outlookcaldavsynchronizer#170]
It is well used.

groups / distribution list feature When will there be available?

**Comment by aluxnimm** [comment]
see also 
https://sourceforge.net/p/outlookcaldavsynchronizer/features/2/

what server are  you using?  there are different possibilities to define groups.

But hopefully we can add distribution lists this year somehow.

**Comment by alexcha** [comment]
짐브라 8.7을 사용 하고 있습니다.
내가 착각을 했다.  그룹리스트 동기화 기능이 정상 적으로 된다. 
고마워.
