### ISSUE TITLE
SOGo, Outlook 2010

### ISSUE THREAD

**Issue by AlessioSpoto** [aluxnimm/outlookcaldavsynchronizer#171]
Sogo with Outlook 2010
, Local PST, Contacts folder 

Hangs during sync

**Comment by aluxnimm** [comment]
You need to provide the debug log file.

**Comment by AlessioSpoto** [comment]
[log.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/517812/log.txt)

**Comment by aluxnimm** [comment]
no error in the log. can you try a different  contact folder?

**Comment by aluxnimm** [comment]
no feedback
