### ISSUE TITLE
Resizing Sync Profiles window does not result in a scrollbar / Position of window not saved

### ISSUE THREAD

**Issue by drew7579** [aluxnimm/outlookcaldavsynchronizer#176]
My work laptop has a paltry 1366x768 resolution, and the Sync Profiles window for CalDavSync does fit in the screen, but just barely. I tried resizing the window to make it smaller, which does work, but it makes it so I can't access anything that's below the edge of the window, because there is no scrollbar. It would seem logical to either prevent resizing of the window or put in a scrollbar if the size of the content in the window is larger than the window itself. (See attached for example)

Also, the placement of the Sync Profiles window does not save, so every time I open it, it extends past the bottom of my screen and I have to move the window in order to access it.

Thanks!
![fullwindow](https://cloud.githubusercontent.com/assets/23193423/19894102/1ff56fee-a022-11e6-989a-89731804b728.png)
![resizedwindow](https://cloud.githubusercontent.com/assets/23193423/19894101/1ff39278-a022-11e6-9c7b-28d243e0b324.png)

**Comment by aluxnimm** [comment]
sure, we should add a scrollbar. will be fixed for next release.

**Comment by drew7579** [comment]
Fantastic, thank you!

**Comment by aluxnimm** [comment]
fixed in f4f0725
