### ISSUE TITLE
Outlook 2007 - high cpu usage in Synchronization Profiles 

### ISSUE THREAD

**Issue by tslben** [aluxnimm/outlookcaldavsynchronizer#177]
Version 2.10.0

Clicking "Synchronization Profiles" results in CPU going to 100%+ for several minutes.  During this time the system is unresponsive.   The dialog is drawn eventually - first an empty window, then after another minute or two the widgets appear.  Clicking + to add a new profile results in another delay.

Closing and re-opening Synchronization Profiles works ok.

This behaviour happens every time if a profile does not exist.  Once a profile has been created, the dialog mostly opens ok.

**Comment by aluxnimm** [comment]
anything in the log.txt during that delay?

**Comment by tslben** [comment]
No.  Cleared log, set debug as log level , opened dialog.

 INFO  2016-11-10 07:22:57,516 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . MoveNext                       - Startup entered.
 INFO  2016-11-10 07:22:57,547 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . .ctor                          - Startup...
 INFO  2016-11-10 07:22:57,718 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . MoveNext                       - Initializing component container.
 INFO  2016-11-10 07:22:57,718 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . MoveNext

**Comment by tslben** [comment]
FYI:
Windows 7 (64 bit)
Visual C++ 2010 Redist version 10.0.40219
Exchange is not being used.
.NET 4.5.1

**Comment by aluxnimm** [comment]
so it only happens when the profile window is empty  and no profile configured yet?
does disabling general option
Expand all nodes in Synchronization profiles
make any difference?

you can also update to latest .net 4.6.x framework of course

**Comment by tslben** [comment]
It occurred when the profile window was empty.  It also occurred if there was a profile and I expanded it and selected one of the child items in the tree  (eg: "Network Settings")

But the bad news (or good, depending on your viewpoint) is that this morning the problem is mostly gone - I am seeing rare delays of a couple of seconds only.  So am unable to test turning off "Expand all nodes".
I tried uninstalling and reinstalling in order to force the issue to return, but nothing.

speculation:  Could be the C++ Redis install required a reboot, although the installer did not ask for one.

**Comment by aluxnimm** [comment]
do you really mean  c++ redis? installer should have installed 
Microsoft Visual Studio 2010 Tools for Office Runtime  ( VSTO )

reboot could be required maybe yes

**Comment by tslben** [comment]
Sorry, you're right.  I do mean the VSTO.

Followed the link to https://www.microsoft.com/en-us/download/details.aspx?id=48217 and downloaded and installed the VSTO first before running your installer.  This is because I would expect to be deploying via WPKG and internet will not be available at installation time.

**Comment by aluxnimm** [comment]
Ok so maybe your VSTO install also installed c++ redis which needs a reboot. Closing, since it seems to work now after reboot.
