### ISSUE TITLE
calender sync error

### ISSUE THREAD

**Issue by gjuecat** [aluxnimm/outlookcaldavsynchronizer#180]
it's not possible to sync my MS outlook calender 2016  any more

I don't know what else to try, also sync of 1 day doesn't work, any ideas?

Windows 7 +Office 2016
CalDav 2.11.0.0
Baikal 0.4.6

![image](https://cloud.githubusercontent.com/assets/24219395/20660125/111d6130-b548-11e6-9eeb-79b96f6d30ae.png)
![image](https://cloud.githubusercontent.com/assets/24219395/20660139/246791f2-b548-11e6-9278-0fbb8fcd8ff7.png)

**Comment by aluxnimm** [comment]
since the  sync attempt lasts 90 secs which is the default timeout, you have  a  server timeout issue. check servef logs  and/ or  restart  your  server.

**Comment by gjuecat** [comment]
Server restart was not successful, where can I find the server logs?

**Comment by aluxnimm** [comment]
You need to check the baikal documentation and your web server. How should know the config of your baikal server?

**Comment by gjuecat** [comment]
deleting the calendar on baikal and starting with a new one was the solution, now it's working

**Comment by aluxnimm** [comment]
good news!
