### ISSUE TITLE
iCloud CardDAV vcf file injecting crlf on photo URL causing a 401 error in logs

### ISSUE THREAD

**Issue by iamGavinJ** [aluxnimm/outlookcaldavsynchronizer#182]
Contact photos aren't being downloaded from iCloud because the vcf file returned has a carriage-return/line-feed in the photo URL after `/WBS`.

e.g.
`PHOTO;TYPE=JPEG;VALUE=uri:https://p02-contacts.icloud.com:443/<MY ID>/wbs
 /015d400012d0217002d3372af883ca28f0014f5851`

The mapping warning report show the following .NET exception
`
Could not add picture for contact. : System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.Contacts.ContactEntityMapper.&lt;MapPhoto2To1&gt;d__20.MoveNext()
`

**Comment by aluxnimm** [comment]
Never tested iCloud with contact photos.
The problem is not the cr/lf in the photo attribute but the missing authentication.
When trying the url in the browser, it complains about missing
X-APPLE-WEBAUTH-TOKEN

We would need to fetch that somehow especially for icloud similar to
https://codedump.io/share/OGoCdrXWqeKu/1/get-icloud-contact-list-in-c

**Comment by iamGavinJ** [comment]
Ah, it must have been using cached credentials/cookie because I pasted the link into a browser and it pulled back the image ok.

**Comment by VincentvgNn** [comment]
Hi,
Even if you have no Apple devices you can easily setup a free iCloud account for testing.
I tried the OpenProtocols Connector with iCloud and that works fine for syncing pictures. Unfortunately I could not get that connector working for fruux and the menu is by far not that versatile.
It would be an advantage if the Outlook CalDav Synchronizer could manage picture links from iCloud and that the iCloud logo could be added to the optional synchronization profiles.

**Comment by aluxnimm** [comment]
Support for iCloud contact profiles with working picture sync and even sync of Outlook distribution lists to iCloud contact groups implemented in 2.24.0.

**Comment by iamGavinJ** [comment]
@aluxnimm works fantastically!!!  Thank you so much.  Awesome work.

**Comment by arpena** [comment]
Doesn't work for me. There is some preference that I have to change?

**Comment by aluxnimm** [comment]
Yes this is disabled by default. Advanced settings, contact mapping configuration, enable "Map Distribution lists" and choose iCloud groups for DAV contact groups format.
