### ISSUE TITLE
OwnCloud VCARD contains phone number but does not show up in Outlook

### ISSUE THREAD

**Issue by GMTA** [aluxnimm/outlookcaldavsynchronizer#187]
The contact's card shows a phone number when displayed in OwnCloud or in the Contacts app on my phone, but not in Outlook. I've tried resyncing and clearing the cache. Using version 2.14.1.0 of CalDav Synchronizer.

The VCARD:
```
BEGIN:VCARD
VERSION:3.0
N:Name;Name;;;
FN:Name\, Name
CLASS:PUBLIC
EMAIL;TYPE=INTERNET;TYPE=WORK:info@example.com
EMAIL;TYPE=INTERNET;TYPE=HOME:info@example.net
ORG:Organisation
TEL;TYPE=PREF;TYPE=MAIN:+31 612345678
UID:ABC2FD39-C9FE-4D53-BEFA-2369C34B4BCE
END:VCARD
```

**Comment by aluxnimm** [comment]
Did you try to open the details of the contact, the problem seems to be the TYPE attribute. TYPE MAIN get's synced to Outlook PrimaryTelephoneNumber which doesn't show up in every dialog.

**Comment by GMTA** [comment]
So if I click on the link underneath "View Source" I get a more detailed view on the contact and the phone number is indeed there, it's only displayed in the contact's card and for the field called "Primary Phone".

I just performed a scan through all my contacts and this was the only card with a phone number stored in this way. I suspect the error originated in one of the other CardDAV clients. Thanks for the hint!
