### ISSUE TITLE
version 2.18 won't show up on Outllook 2007 toolbar - it was previously working

### ISSUE THREAD

**Issue by mottycruz** [aluxnimm/outlookcaldavsynchronizer#191]
Hi Caldav Sync was working fine until few days ago I noticed it was deleted from the toolbar, I tried re-installing but does not show up in Outlook 2007 toolbar. I have the latest updates of .net framework & SP3 installed. Any ideas?

**Comment by aluxnimm** [comment]
Is it enabled in the Addins page? see
http://www.tech-recipes.com/rx/1959/outlook_2007_disabling_enabling_add_ins/

**Comment by mottycruz** [comment]
Thanks Aluxnimm. you're right is not enable, and I can't enable it. 
'c:\Program Files (x86)\CalDavSynchronizer\CalDavSynchronizer.vsto' is not a valid office add-in.

**Comment by aluxnimm** [comment]
Visual Studio 2010 Tools for Office Runtime is installed, if not check
https://www.microsoft.com/en-us/download/details.aspx?id=54251
 
And you did install the addin for the current user only? Installation for Everyone is not supported in 2007.

**Comment by mottycruz** [comment]
correct I installed it "current user only". Also, VS2010 Runtime is installed as well.

**Comment by aluxnimm** [comment]
Check if the registry entries are correct in
HKEY_CURRENT_USER\Software\Microsoft\Office\Outlook\AddIns\CalDavSynchronizer

Manifest should be file:///C:\Program Files (x86)\CalDavSynchronizer\CalDavSynchronizer.vsto|vstolocal

if c:\Program Files (x86)\CalDavSynchronizer is the correct install folder

**Comment by mottycruz** [comment]
Thank you very much, I got it fixed. It was set to: 
Manifest should be file:///C:\Program Files (x86)\CalDavSynchronizer\CalDavSynchronizer.vsto|vstolocal

and I set it to
Manifest should be C:\Program Files (x86)\CalDavSynchronizer\CalDavSynchronizer.vsto|vstolocal

now is working. I deleted "file:///". 

Thanks again!

**Comment by aluxnimm** [comment]
Ok strange, but good news that it is working.

**Comment by mottycruz** [comment]
Yes very strange indeed! couldn't done it without your help! 

Thanks
Motty
