### ISSUE TITLE
Email addresses for Home and Work get swapped in Outlook

### ISSUE THREAD

**Issue by VincentvgNn** [aluxnimm/outlookcaldavsynchronizer#193]
I'm using Windows 10 and Office 365 and tried coupling the Outlook address book with Fruux, FastMail and iCloud.
A killing issue is that the email addresses in Outlook denoted as "Email", "Email 2" and "Email 3" do not match as "Home", "Work" and "Other".
- "Email" should be equal to the "Home" address and not to "Work" address.
- "Email 2" should be equal to the "Work" address and not to "Home" address.
- "Email 3" should be equal to the "Other" address. That seems to be OK.

Copying addresses in Outlook from e.g. the Fruux or the FastMail address book to the Outlook.com address book is only possible when that sequence is kept OK.

**Comment by aluxnimm** [comment]
This could be easily fixed of course but I am not sure if someone needed it exactly the other way round :(  Need to check this and if so, we would need to make it configurable.

**Comment by VincentvgNn** [comment]
You are surprising me by the idea to make in configurable!
Whether wrong or not, it would be good to keep all users satisfied.
Thanks a lot.

**Comment by aluxnimm** [comment]
what does outlook do when importing/exporting a vcard manually?  did you check if in this case also  email1 is mapped to home?

**Comment by VincentvgNn** [comment]
The Outlook Web Access (Outlook.com account) maps to Outlook in a way similar to what that I proposed.
Personal  <--> Email
Work       <--> Email 2
Other      <--> Email 3
This is the first evidence on how it should be.

Exporting vCards from Outlook does not pass a well-defined type indication. Example:
BEGIN:VCARD
VERSION:2.1              (yes, truly a 1996 standard!)
N;LANGUAGE=nl:vCard;John
FN:John vCard
X-MS-OL-DEFAULT-POSTAL-ADDRESS:0
EMAIL;PREF;INTERNET:email@mail.com
EMAIL;INTERNET:email2@mail.com
EMAIL;INTERNET:email3@mail.com

I fear that Microsoft is mainly using the sequence of the mailaccounts and not so much the added type parameter. Therefore I followed the rule "Home" first, "Work" second and "Other" third. Then I had no problems.

On my Android smartphone I have "Nine - Outlook for Android" installed to connect with my Outlook.com address book using Exchange Active Sync. There in Nine the type indication is Email, Email2 and Email3.
When I merge that with the phone's address book, it automatically results in:
Email   <--> Private address (Home)
Email2  <--> Business address (Work)
Email3  <--> Other address (Other)
This is the second evidence on how it should be.

I use eM Client as a vCard manager that uses vCard v3.0 and that can be synced to other systems.
A vCard from an EAS connection with outlook.com shows:
  FN:John vCard
  EMAIL;X-CN=John vCard (email@mail.com);TYPE=PREF:email@mail.com
  EMAIL;X-CN=John vCard (email2@mail.com):email2@mail.com
  EMAIL;X-CN=John vCard (email3@mail.com):email3@mail.com
When I copy that vCard within eM Client to an iCloud account the result is that iCloud assigns the label "E-mail" to all, just because there is no better type parameter.

**Comment by aluxnimm** [comment]
Ok thanks, will check if I find the discussion about the other way round. If not, I will just change it this way since it sounds reasonable enough.

**Comment by aluxnimm** [comment]
Swapped mapping in  ab4a14b
Will be in next release.

**Comment by aluxnimm** [comment]
Finally made mapping configurable, b9f1df3.
Will be in next release.

**Comment by VincentvgNn** [comment]
Thanks a lot for your previous modification.
At this moment it works fine when connecting to Fruux and Google.
I have no evidence that it go's wrong somewhere. Maybe for existing users of previous versions of your Add-in?
Can you make the current mapping as a default setting in the configurable mapping?

**Comment by aluxnimm** [comment]
it will be default yes. but mailbox.org needs it the other way round for example
