### ISSUE TITLE
System.InvalidCastException: Das Objekt des Typs "System.String" kann nicht in Typ "System.Byte[]" umgewandelt werden.

### ISSUE THREAD

**Issue by gjuecat** [aluxnimm/outlookcaldavsynchronizer#195]
Hi,

I'm using the synchronizer for some month to sync Outlook to Baikal to smartphone (2 way). Since some days I get some sync errors for contacts, as far as I have found out mostly for contacts which I called with my phone.
`<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>Kontakte Firma</ProfileName>
  <ProfileId>8fcd0681-1738-4a5b-bfb6-3878bf01bd87</ProfileId>
  <StartTime>2017-05-15T04:15:42.4661264Z</StartTime>
  <ADelta>Unchanged: 125 , Added: 0 , Deleted 0 ,  Changed 1</ADelta>
  <BDelta>Unchanged: 124 , Added: 0 , Deleted 0 ,  Changed 2</BDelta>
  <AJobsInfo>Create 0 , Update 0 , Delete 0</AJobsInfo>
  <BJobsInfo>Create 0 , Update 0 , Delete 0</BJobsInfo>
  <LoadErrors>
    <LoadError>
      <EntityId>/dav.php/addressbooks/Stuetz/juergenfirma/9ca3ff16-a75c-4f42-a565-094ade8af986.vcf</EntityId>
      <Error>System.InvalidCastException: Das Objekt des Typs "System.String" kann nicht in Typ "System.Byte[]" umgewandelt werden.
   bei Thought.vCards.vCardStandardReader.ReadInto_KEY(vCard card, vCardProperty property)
   bei Thought.vCards.vCardStandardReader.ReadInto(vCard card, vCardProperty property)
   bei Thought.vCards.vCardStandardReader.ReadInto(vCard card, TextReader reader)
   bei CalDavSynchronizer.Implementation.Contacts.CardDavRepository`1.Deserialize(String vcardData, vCardStandardReader serializer)
   bei CalDavSynchronizer.Implementation.Contacts.CardDavRepository`1.TryDeserialize(String vcardData, vCard&amp; vcard, WebResourceName uriOfAddressbookForLogging, vCardStandardReader deserializer, ILoadEntityLogger logger)</Error>
      <IsAEntity>false</IsAEntity>
    </LoadError>
    <LoadError>
      <EntityId>/dav.php/addressbooks/Stuetz/juergenfirma/4b60a692-e810-4874-88b5-9255dd901035.vcf</EntityId>
      <Error>System.InvalidCastException: Das Objekt des Typs "System.String" kann nicht in Typ "System.Byte[]" umgewandelt werden.
   bei Thought.vCards.vCardStandardReader.ReadInto_KEY(vCard card, vCardProperty property)
   bei Thought.vCards.vCardStandardReader.ReadInto(vCard card, vCardProperty property)
   bei Thought.vCards.vCardStandardReader.ReadInto(vCard card, TextReader reader)
   bei CalDavSynchronizer.Implementation.Contacts.CardDavRepository`1.Deserialize(String vcardData, vCardStandardReader serializer)
   bei CalDavSynchronizer.Implementation.Contacts.CardDavRepository`1.TryDeserialize(String vcardData, vCard&amp; vcard, WebResourceName uriOfAddressbookForLogging, vCardStandardReader deserializer, ILoadEntityLogger logger)</Error>
      <IsAEntity>false</IsAEntity>
    </LoadError>
  </LoadErrors>
  <EntitySynchronizationReports />
  <ConsiderExceptionThatLeadToAbortionAsWarning>false</ConsiderExceptionThatLeadToAbortionAsWarning>
  <Duration>00:00:01.3370754</Duration>
</SynchronizationReport>`

I'm using the latest version of CalDav Synchronizer.

What's wrong?
Thx

**Comment by aluxnimm** [comment]
Please provide the vcard which causes the error (/dav.php/addressbooks/Stuetz/juergenfirma/9ca3ff16-a75c-4f42-a565-094ade8af986.vcf)
It seems to have an invalid or wrong encoded certificate.

**Comment by aluxnimm** [comment]
Fixed in 6dcf0ff, will be in next release.

**Comment by aluxnimm** [comment]
As a workaround meanwhile you can also add
KEY;ENCODING=b;TYPE=X509
to the key attribute
