### ISSUE TITLE
Sync from Outlook to as DaviCal Server creates a .in Resource

### ISSUE THREAD

**Issue by haderlump22** [aluxnimm/outlookcaldavsynchronizer#196]
Some People, where i installed the caldavsync, it creates a <.in> Recource. First time i note the "Problem"  with WIN10 and Outlook2016. In the last few Month, it happens in some more Constelaetions.

It bring some Sync Problems, and i musst delete the <.in> Recource manually. 

I found nothing in a SyncProfile, where i can disabled the Creation of the <.in> Resource.

Any Idea where that come from?

nice Day!

**Comment by aluxnimm** [comment]
where  does it  create what exactly?  please be more precise and provide a concrete example and log where the sync creates something it shouldn't.
