### ISSUE TITLE
Outlook contact note format not synced.

### ISSUE THREAD

**Issue by younix70** [aluxnimm/outlookcaldavsynchronizer#200]
Hi, everyone.
Thank you for this powerful tool.

When I edit a contact note format (for example BOLD some text and change right to left alignment) and then sync it with carddav server (Radicale), other clients that use this resource doesn't see note format.

Is this a problem related to CalDAV synchronizer or outlook?
If yes how to fix this issue?

**Comment by aluxnimm** [comment]
Outlook stores the formatting as RTF, which is not supported by the NOTE attribute of vcards and most other non MS clients. So we can't sync the formatting atm sorry. A workaround with extended attributes exists only for the description of calendar appointments.

**Comment by younix70** [comment]
Thank you @aluxnimm .Is it possible to encode Outlook RTF format to base64 and then save it to note section of vcard? like in the PHOTO section of vcard?

**Comment by aluxnimm** [comment]
NOTE should be plain text, other clients won't decode the base64 value anyway and it would violate the RFC. Only possibility would be some X-attribute and save it as HTML similar to X-ALT-DESC for appointments. But even Outlook itself doesn't preserve the formatting when exporting and reimporting a vcard.
