### ISSUE TITLE
"Sync Report" window grabs focus on sync errors

### ISSUE THREAD

**Issue by otdftr** [aluxnimm/outlookcaldavsynchronizer#201]
On a sync error, the "Synchronization Reports" window appears and grabs the focus. This is quite annoying if you have bad connectivity (e.g. during a train ride) and serveral sync profiles in place.

Would prefer a systray notification / balloon or the like.

My config & environment:
- OLK 2007 / Caldav Synchr 2.22.1 / Win 7 
- "check internet connection before sync run" is on, 
- "show reports and notify" is set to "errors an warnings"

(BTW, this should be said: This is really a great piece of software! Best functionality from the very early versions on, good coding, and - as far as I can see with OLK and CalDAV/Own/Nextcloud - excellent data handling, lossless recovery from sync and network errors, and following the standards thoroughly. Thanks a lot!)

**Comment by aluxnimm** [comment]
thank you!

there is also a systray icon and you can disable the popup of the sync report window in general options.
