### ISSUE TITLE
REV Property not updated on sync

### ISSUE THREAD

**Issue by mmfriedel** [aluxnimm/outlookcaldavsynchronizer#204]
The REV: property is not updated when I change a contact in Outlook.

I did the following. Created a contact on my CarDav server. Synced it to outlook. Edited in Outlook (added email) and waited until is was synced back.
The REV property was still that of the original contact.

The REV property should not stay the same if the content of the vCard changes.
See [RFC 6350](https://tools.ietf.org/html/rfc6350#section-6.7.4)

**Comment by aluxnimm** [comment]
what server are you using and what timestamp format is written to the REV property? 

But you are right we aren't writing/updating REV yet and should do so.

**Comment by mmfriedel** [comment]
I have several servers. saber/dav , CalendarServer.
The REV: property is either

REV:2017-07-23T21:30:21Z
or
REV:2017072323021Z

mostly the latter.

Michael

**Comment by aluxnimm** [comment]
Fixed in 0b2189c , will be in next release.
