### ISSUE TITLE
Problem with Proxy-Server (Deny Authentication in NTLM)

### ISSUE THREAD

**Issue by neupertd** [aluxnimm/outlookcaldavsynchronizer#207]
Hello We use a Proxy-Server with transparent NTLM-Authentication (Sophos).
Since last Update, CalDavSynchronizer kills the Authentication and the User will be blocked at Win-Domain.
The normal Proxy-Settings inside CalDavSynchronizer works as well before.

Profile --> Network Settings -->  Use preemtive authenticaten = yes    and at Proxy Setting use system Default = yes

CalDSavSynchronise 2.23.0.0
Windows 7 Prof
Ouitlook 2010
[log.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/1241876/log.txt)

**Comment by aluxnimm** [comment]
What do you mean by "the normal proxy settings work as well before" ?
The versions before 2.23.0 did work with your proxy and the google profile?

**Comment by neupertd** [comment]
Yes it worked before, but i do a downgrade and it dont want work to.
I will talk to my Firewall-Admin to check this. I will tell you more soon.

Best regards
Dirk Neupert


Ja, es lief bisher. Allerdings läuft es trotz eines Downgrades auf die
vorherige Version immer noch nicht. Ich werde das noch einmal mit meinem
Firewall-Admin klären und melde mich dann wieder falls ich eine Info habe.
Zur Info unserem Proxy-Servers. Es handelt sich dabei um ein Sophos-System,
dass per NTLM über die jeweilige Domänenkennung den Zugang in das Netz
freigibt. Die Authentifzierung erfolgt dabei transparent ohne Eingriff des
Nutzers.

Viele Grüße
Dirk Neupert


2017-09-12 21:04 GMT+02:00 Alex Nimmervoll <notifications@github.com>:

**Comment by neupertd** [comment]
Works fine with new Release 2.24.0
