### ISSUE TITLE
Wrong recurrence pattern for 'last Friday in september'

### ISSUE THREAD

**Issue by donestefan** [aluxnimm/outlookcaldavsynchronizer#208]
When creating new recurring events like "last friday in september" the resulting ical will contain 
```
RRULE:FREQ=YEARLY;BYDAY=FR;BYMONTH=9;BYSETPOS=-1
```
Other calendar tools (like emclient for win or acalendar for android) have trouble reading this.
They seem to expect something like
```
RRULE:FREQ=YEARLY;BYDAY=-1FR;BYMONTH=9
```

Do you see a way to switch the format you use when creating these kind of events?

I use outlook 2013 on win7 with CalDav Synchronizer 2.23 and 
caldav server at posteo.de (whatever caldav server they use).

My problem seems to be remotely related to closed sourceforge Tickets:
https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/57/
https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/46/

Sorry for not opening the ticket at your sourceforge site, but I was not able to solve their captcha and now the signup form is blocked... :(

**Comment by aluxnimm** [comment]
But the BYSETPOS isn't wrong, is it? So if some client can't parse it, shouldn't you open a ticket there, so that it can be fixed there. We  had some issues with various clients and servers and ended up with this serialization.

**Comment by donestefan** [comment]
Your have a point there. But I was hoping you could add an option to switch the behaviour in your tool. Especially since people keep having issues with various clients and servers.
The other apps I'm using are a free version of an commercial app, so there is basically no support on the other end.
I would understand if you decide to not fix anything on your end, since you are technically right.

**Comment by aluxnimm** [comment]
We have no resources to fix anything which isn't broken and another config option would confuse users as well I believe, since it is not clear which client/server combination will support which recurrence rule.
