### ISSUE TITLE
How can I use it for Mac OS X

### ISSUE THREAD

**Issue by Kangtle** [aluxnimm/outlookcaldavsynchronizer#216]
Hello.
It is amazing library and thank you for your trouble.
I was wondering if it is able to use with Outlook for OS X.
Please help me.
Thank you.

**Comment by aluxnimm** [comment]
Lot of tickets and discussion about that already. We don't plan any OS X version, is not possible since it is an C# VSTO addin which is not supported on Mac OS X.
