### ISSUE TITLE
Synchronization Status window no longer shows current status

### ISSUE THREAD

**Issue by markus0m** [aluxnimm/outlookcaldavsynchronizer#217]
Since the last few versions, the Synchronization Status window no longer shows any data.
It doesn't matter whether the last sync succeeded or failed or how it was triggered, the fields remain empty.

![2017-12-01 12_12_17-synchronization status](https://user-images.githubusercontent.com/13851981/33480526-37488108-d691-11e7-876f-0d6b74b32e5a.png)

**Comment by plauzenbaer** [comment]
me encounter the same since last version

**Comment by nertsch** [comment]
logfile?
