### ISSUE TITLE
Could not get property PR_SMTP_ADDRESS for adressEntry

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [aluxnimm/outlookcaldavsynchronizer#218]
Hi there,
I am as of today seeing a similar error as reported before in #132. Back then it was dismissed as being related to the old Outlook 2007 I was using.

Now I am using Outlook 2016 and also upgrade to nextcloud 12 on the webdav side.

The error looks like this

    <?xml version="1.0" encoding="utf-16"?>
    <SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <ProfileName>Workcalendar</ProfileName>
      <ProfileId>24a36c72-1549-4529-b57c-0ff52113c4cc</ProfileId>
      <StartTime>2017-12-05T10:28:15.0161454Z</StartTime>
      <ADelta>Unchanged: 94 , Added: 0 , Deleted 0 ,  Changed 2</ADelta>
      <BDelta>Unchanged: 96 , Added: 0 , Deleted 0 ,  Changed 0</BDelta>
      <AJobsInfo>Create 0 , Update 0 , Delete 0</AJobsInfo>
      <BJobsInfo>Create 0 , Update 2 , Delete 0</BJobsInfo>
      <LoadErrors />
      <EntitySynchronizationReports>
        <EntitySynchronizationReport>
          <MappingErrors />
          <MappingWarnings>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x80040201): Fehler beim Ausführen der Operation.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
          </MappingWarnings>
          <AId>000000000FEB40D401C06C4DB129A9F235B7D7750700E24DC21FB7AC584488FBB43A5330D69B00000000010D0000E24DC21FB7AC584488FBB43A5330D69B000000000D460000</AId>
          <BId>/nextcloud/remote.php/dav/calendars/username/work/00af4ec4-2967-4e3b-af50-448ddc0c7c31.ics</BId>
          <Operation>UpdateInB</Operation>
        </EntitySynchronizationReport>
        <EntitySynchronizationReport>
          <MappingErrors />
          <MappingWarnings>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x80040201): Fehler beim Ausführen der Operation.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x80040201): Fehler beim Ausführen der Operation.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x80040201): Fehler beim Ausführen der Operation.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x80040201): Fehler beim Ausführen der Operation.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x80040201): Fehler beim Ausführen der Operation.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
            <string>Could not get property PR_SMTP_ADDRESS for adressEntry : System.Runtime.InteropServices.COMException (0x80040201): Fehler beim Ausführen der Operation.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.ComWrappers.OutlookObjectExtensions.GetPropertySafe(PropertyAccessor accessor, String propertyName)
       bei CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)</string>
          </MappingWarnings>
          <AId>000000000FEB40D401C06C4DB129A9F235B7D7750700E24DC21FB7AC584488FBB43A5330D69B00000000010D0000E24DC21FB7AC584488FBB43A5330D69B000000000D5D0000</AId>
          <BId>/nextcloud/remote.php/dav/calendars/username/work/cceb6335-6d62-40e0-9b9a-c64928679780.ics</BId>
          <Operation>UpdateInB</Operation>
        </EntitySynchronizationReport>
      </EntitySynchronizationReports>
      <ConsiderExceptionThatLeadToAbortionAsWarning>false</ConsiderExceptionThatLeadToAbortionAsWarning>
      <Duration>00:00:03.6132225</Duration>
    </SynchronizationReport>

**Comment by 1337sup3rh4x0r** [comment]
How could I determine the problematic item and delete it?

**Comment by aluxnimm** [comment]
Click on the Outlook ID in the sync report and it should open the appointment

**Comment by 1337sup3rh4x0r** [comment]
Thanks, that helped deleting the item at least. But I don't get what went wrong there.
