### ISSUE TITLE
Problems syncronizing with CPanel server

### ISSUE THREAD

**Issue by alenguav** [aluxnimm/outlookcaldavsynchronizer#220]
Hello,
I followed the indications of the following link to configure  your plugin in Outlook 2016
https://documentation.cpanel.net/display/CKB/How+to+Set+Up+Calendars+and+Contacts#c3f2a276f2494da28d845d8d82b698c4
however I am receiving an error message regarding Protocol Infraction
and as a result it is not working as expected.

**Comment by aluxnimm** [comment]
Check the documentation or various tickets and messages about CPanel, you need to enable the general option "Enable useUnsafeHeaderParsing" in the plugin.
