### ISSUE TITLE
Tasks created by Marking Mails as Task in Outlook are not synced to nextcloud

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [aluxnimm/outlookcaldavsynchronizer#222]
Hi all,
not sure if this is a bug or just an unsupported feature of Outlook.

In Outlook I can click a red flag next to the email header and it is marked as a task. It then appears in my task list in outlook.
However, these items are not synced to my nextcloud.

I am using Outlook 2016 and latest nextlcoud 12.

Thank you for your awesome work with this piece of software!

**Comment by ingoratsdorf** [comment]
That's an Outlook feature. Outlook has at least two corrections for tasks, one is tasks and one is to - do items.
In outlook default setup, both are never into one view but are two collections. If you move your created to - do item into your synced takes lists that CalDAVSynchronizer synvhronizes, then this should get transferred to nextcloud.
But you'll then loose the Metadaten and connection to your original email that was part of the original outlook item. 
So you kinda downgraded it.
