### ISSUE TITLE
Outlook automatic send/receive emails is broke since CalDavSynchronizer V2.2.0 

### ISSUE THREAD

**Issue by muXxer** [aluxnimm/outlookcaldavsynchronizer#224]
Hi everybody!
I have a strange problem. Outlook 2013 stops receiving emails if the CalDavSynchronizer AddIn is activated. If it is deactivated, everything works fine. If it is activated, i have to click "Send/Received Emails" on my own every time. Automatic send/receive doesn't work anymore. I installed it on a lot of workstations (around 20) and only 2 have this problem. I also reinstalled windows and tried a fresh installation, but it didn't work.

I tested a lot of old versions to find the root of the bug. The last version of CalDavSynchronizer without this problem was **V2.1.3** and the first version with this bug is **V2.2.0**. In the commit history, there is a commit message "*Add general option to trigger sync after Outlook Send/Receive finishes, github issue 141.*" between these two versions. Maybe something is buggy with this?
 ```
1) Windows Version
    Windows 7 Professional x64 SP1

2) Outlook Version
    Outlook 2013

3) CalDavSynchronizer Version
    3.1

4) CalDav/Cardav Server and Version
    NextCloud 12.0.5
```
Btw: Thank you very much for this wonderful software! I like it very much!

**Comment by aluxnimm** [comment]
There is a ticket about this on sourceforge and a office kb fixes it. Please check if you find it, on mobile now...

**Comment by muXxer** [comment]
Thank you very much! A simple "Windows Update" did the trick. Sorry!

Here is the ticket on sourceforge:
https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/761/

And here is the Hotfix from the comments in sourceforge:
http://support.microsoft.com/kb/2878323/EN-US
