### ISSUE TITLE
Usage/Sync of VTODO Calendar Objects from CalDAV Owncloud/Nextcloud

### ISSUE THREAD

**Issue by thommierother** [aluxnimm/outlookcaldavsynchronizer#225]
I can not find any documentation how to integrate VTODO tasks from Owncloud/Nextcloud for synchronisation with Outlook 2016. Both VTODO and VEVENT are part of the same CalDAV collection, but how can I get the VEVENTs in the Outlook calendar and the VTODOs in the outlook task list? Do I need a separate profile for the tasks, with the same CalDAV URL but a different outlook folder? Tested with  3.1.0.0.

**Comment by aluxnimm** [comment]
Yes, create a new profilr, same URL, but a Outlook task folder.
