### ISSUE TITLE
Can't parse calendar data: Invalid property

### ISSUE THREAD

**Issue by Daywalker01** [aluxnimm/outlookcaldavsynchronizer#226]
Hi

I have the issue that people tend to create Outlook calendar entries with CIFS Share Paths to (in our case MS Onenote) documents. (S:\one\random\share\path\...)
The target macOS  CalDAV Server is unwilling to accept that string in the DESCRIPTION Field

The error message reads:
```
<?xml version='1.0' encoding='UTF-8'?>
<error xmlns='DAV:'>
  <valid-calendar-data xmlns='urn:ietf:params:xml:ns:caldav'/>
<error-description xmlns='http://twistedmatrix.com/xml_namespace/dav/'><![CDATA[Can't parse calendar data: Invalid property: 'TextValue: '\o' not allowed': DESCRIPTION:Terminserie [CUT]...[/CUT] Besprechungsprotokolle siehe S:\one\random\share\path\Protokolle.one
...
```

Maybe some kind of (optional) custom regex replace (eg. select Field name, enter sed style rules) would be nice?
Or automated escaping?
Or the possibility to just skip such entries?
Or some other/better idea?

**Comment by aluxnimm** [comment]
This is a bug in our used library, which doesn't escape single backslashes properly. We will need a workaround and fix it of course.

**Comment by aluxnimm** [comment]
Will be in next release, commit  527526a
