### ISSUE TITLE
[Question] DAV support for Application

### ISSUE THREAD

**Issue by Mannshoch** [aluxnimm/outlookcaldavsynchronizer#230]
I wish to write an Enhancement request for DAV support to get and write data to CAL/CARD DAV for an Software which is developed by a single developer which does it his sparetime. Is there an recommendation for a library or Program for Visual Studio I could tell him which could help him to do it with as low work as possible? I am not a developer, so I do not now much about this.

**Comment by aluxnimm** [comment]
Please use discussion on SourceForge forum for such questions, since it is no bug or feature request.
