### ISSUE TITLE
[Question] Remove Outlook Private Flag or set it to Default/Public

### ISSUE THREAD

**Issue by feutl** [aluxnimm/outlookcaldavsynchronizer#234]
I am syncing my Outlook Calendar with Nextcloud. So far so good.
I want to remove the private flag I have set in Outlook when syncing to Nextcloud.

How can I accomplish it, I haven't found anything helpful.

Thanks

**Comment by aluxnimm** [comment]
There is no option for that atm.

**Comment by feutl** [comment]
Is there any chance to get the feature implemented or is there another way/workaround to make that happen?
I am syncing to nextcloud and perhaps I can do that on the server with a script or anything else manually/automated.

thanks

**Comment by aluxnimm** [comment]
What do you want to accomplish? There is already the option to map Outlook private to CLASS:CONFIDENTIAL instead of PRIVATE which allows you to share it.

**Comment by feutl** [comment]
I handling all my scheduling using my company calendar. There I mark private appointments as private.
I cannot share this calendar with others (family) so I export it to nextcloud what my whole family is using, but the privately marked appointements cannot be seen by them.
Even if I set CLASS:CONFIDENTIAL they only sie "busy" but not the complete information which they should be able to see.

I handled multiple calendars for quite some time and messed up things quite some times as well :D And this would be the "easiest" way for me to let my family see my appointments and only have my company calendar with private flags as a single source.

I know it is quite special but perhaps I can find a solution for that :)

**Comment by aluxnimm** [comment]
Then you need some script which changes the CLASS attribute on the nextcloud server in the database for example or change the source and recompile CalDavSynchronizer, but this is such a limited use case atm that another option to change Outlook private flag to PUBLIC would be an overkill.

**Comment by feutl** [comment]
Thanks,
I just hoped that there is a possibility to use the "custom mapping" to accomplish this somehow, but ok, would have been to easy ;)

Thanks

**Comment by rumich** [comment]
Just wanted to say that I have exactly the same use case / challenge and no solution yet.

**Comment by christian-hofstetter** [comment]
+1 I am also interested in this option as I have the exact same use case between Outlook and Gmail. FYI https://www.outlookgooglecalendarsync.com/ has it as a feature.
