### ISSUE TITLE
Wrong mailto when using attendees via LDAP

### ISSUE THREAD

**Issue by krombel** [aluxnimm/outlookcaldavsynchronizer#235]
I get several errors like the following:
```
Invalid email address Uri 'mailto:/o=MyOrg/ou=Group/cn=RecipientID' for attendee.
```
I try to sync my Calendar from Exchange to a sabreDav location.
I am using 3.2.0.0

**Comment by aluxnimm** [comment]
These are just warnings where the email adress of an exchange user attendee cant be detected. You can ignore it.
