### ISSUE TITLE
Snychronizing Open-XChange 

### ISSUE THREAD

**Issue by nickbe** [aluxnimm/outlookcaldavsynchronizer#236]
We're trying to sync OpenXChange to Outlook. 
Problem ist that there's an adress book under the Synchronizer tab in outlook which does show an adressbook, but the contacts doesn't show up in the standard outlook adress book.

**Comment by aluxnimm** [comment]
What synchronizer tab? Did you create a sync profile for that server adressbook and map it to the standard outlook contact folder?

**Comment by nickbe** [comment]
We found the problem. We had to map every adressbook to a new file in outlook. 
Thanks.
