### ISSUE TITLE
google calendar: switch from tasks to reminders

### ISSUE THREAD

**Issue by seba-eng** [aluxnimm/outlookcaldavsynchronizer#237]
The google calendar app on android only shows reminders but this plugin only synchronizes tasks. It would be great if it although  would be be possible to sync reminders.

**Comment by aluxnimm** [comment]
can't you sync google reminders to outlook calendar reminders? Are those reminders stand-alone or attached to a calendar event?

**Comment by seba-eng** [comment]
Reminders are stand alone, I have to admit, I don't quite get the difference to googles tasks, but you can't make the app show the tasks. Reminders seem to replace tasks slowly. 
Either I'm doing it wrong, or you can't sync google reminders to out outlook tasks.

**Comment by aluxnimm** [comment]
There is no reminder Api so we can't create or sync reminders, see

https://issuetracker.google.com/issues/36760283
