### ISSUE TITLE
SameOrganizerForAllComponentsException

### ISSUE THREAD

**Issue by maybeec** [aluxnimm/outlookcaldavsynchronizer#240]
Latestly, I get an SameOrganizerForAllComponentsException on each synchronization of an existing series, which has not been changed in the last months. The sync is configured with Outlook -> Server only. So there should be no "conflicts" at all.

Exception:

```
CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '500' ('Internal Server Error'). Message:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\VObject\ITip\SameOrganizerForAllComponentsException</s:exception>
  <s:message>Every instance of the event must have the same organizer.</s:message>
</d:error>

   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<EnsureSuccessStatusCode>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReturnResponseHeaders>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<TryUpdateEntity>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.<TryUpdate>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at CalDavSynchronizer.Implementation.CalDavRepository`1.<TryUpdate>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.<PerformOperations>d__3.MoveNext()
```

I am running the latest Nextcloud stable and Outlook 365.

**Comment by aluxnimm** [comment]
And does Outlook show different organizers for some events in the series? Somehow Outlook changes that field in rare circumstances. Check the ics file of that event.

**Comment by maybeec** [comment]
How can I check the organizers? The appointment is three times a week and runs already over a year ;) Do you know any shortcut rather then trying to go through every occurrence? The organizer maybe changes as of AD update of that contact?

**Comment by aluxnimm** [comment]
Can you export the whole series as ics file and check the organizer field in there?

**Comment by aluxnimm** [comment]
That's the line folding from the ICS format, yes. So it looks the same for every instance in the series? So the only difference is SCHEDULE-AGENT? Try to change that option Set SCHEDULE-AGENGT=CLIENT in the event mapping configuration and see if that changes anything?

**Comment by maybeec** [comment]
I enabled the option `Set SCHEDULE-AGENGT=CLIENT`, but without success, the error continues occurring on every sync attempt.

**Comment by aluxnimm** [comment]
And really no different organizer in any of the single events of the recurrence? Can't be, because the error says that "Every instance of the event must have the same organizer."

**Comment by maybeec** [comment]
yes, but how can I assure / check that? Bascially, there are thousands occurrences already. I cannot click through all of them and the exported series ics does not show different organizers.

**Comment by maybeec** [comment]
Now I start to have it with an additional series appointment as well, which I added about one month ago.
My observation is, that it starts so synchronize occurrences from the future, which have not yet been synchronized as of the synchronization window configured in outlookcaldavsynchronizer. For some reason afterwards added occurrences seem to not match the organizer anymore although I cannot see any change. Here one example of such synchronization:

![grafik](https://user-images.githubusercontent.com/1427255/46569369-5f69b880-c954-11e8-849d-084a0cf12b82.png)

**Comment by aluxnimm** [comment]
So if you remove the time filtering and use for example WebDAV collection sync instead it doesn't occur?

**Comment by maybeec** [comment]
Seems to work, thanks!!!
What is the difference here? I saw, that I am not able anymore to specify a sync range. So will that upload/sync whatever is available?

**Comment by aluxnimm** [comment]
Yes this is a different approach, see https://tools.ietf.org/html/rfc6578
A sync token is used to send only the delta since the last sync, which saves bandwith, but can't be combined with a timerange since this uses a different query.
But we should investigate the organizer and the timerange window in more detail to reproduce your bug.

**Comment by maybeec** [comment]
Now it starts again for one of the appointments to run into the same issue again :(. 
The other is fine for now.

**Comment by nertsch** [comment]
There must be one exception in Outlook which has a different Organizer.
Finding this out can be done in a few minutes with the following steps:
1) Open the Synchronization Profiles Dialog
2) Copy the affected profile and select (Maybe this is done automatically) the copy in the Treeview, to edit it
3) Make sure that the Mode is "Outlook -> Server (Replicate)"
4) Set the DAV Url to "file://D:/Temp/Events/"
5) Close the Dialog by clicking Ok
6) Make Sure the Directory "D:/Temp/Events/" exists
7) Click on "Synchronize now"
8) Find the ics File for the affected appointment (Can be done via search multiple Files with a text editor e.g. Notepad++)
9) Open the ics-File and check which Organizer is different from the others

br
Gerhard

**Comment by maybeec** [comment]
Ok did it.
First: The result is a successful synchronization with the file system with multiple warnings of "invalid email address Uri" for basically multiple appointments.

Second: I searched for the errorneous synchronized series appointment running into errors at my original sync job. I do not really understand the syntax/semantics of ics format, but here is what I observed. There are three different organizers, which are the same person.
1. 
```
ORGANIZER;CN="<the persons AD name>";SCHEDULE-AGENT=CL
 IENT:
```
2.
```
ORGANIZER;CN="<the persons AD name>";SCHEDULE-AGENT=CL
 IENT:mailto:<mail address>
```
3.
```
ORGANIZER;CN="<the persons AD name>";SCHEDULE-AGENT=CL
 IENT;SCHEDULE-STATUS=1.1:
```

**Comment by maybeec** [comment]
Any news on that? Maybe it's anything related to the Nextcloud 13.0.8 version? It starts with Nextcloud 13.0.7 or Nextcloud 13.0.6 as far as I know. But I am not sure, whether there was an update of outlookcaldavsynchronizer as well in between.

**Comment by aluxnimm** [comment]
Latest commit should fix the exception 8ec7cc43fd1a79abd446e47baf7aa8155570e7c3
We just force the organizer to be the same.

Still the issue with the invalid mail uris needs to be solved.

**Comment by maybeec** [comment]
:+1: waiting for a release to provide you feedback. Thanks.

**Comment by maybeec** [comment]
seems to work for now.
