### ISSUE TITLE
Contact groups are not synchronized

### ISSUE THREAD

**Issue by dkellenb** [aluxnimm/outlookcaldavsynchronizer#242]
Steps to reproduce

1. Create a new contact group on nextcloud
1. Add a new synchronization profile in outlook
1. Create two contacts in Outlook => They are well synchronized
1. Create contact group with those two contacts => Bug: Contact group not synchronized

Also contact groups created in nextcloud are not synchronized to Outlook

Tested with CalDav Synchronizer Version 3.2.1.0 and Outlook 2016

Note that when enabling `[x] Map Disstribution Lists` both settings (`vCard with KIND:group` and `iCloud group`) mentioned on https://github.com/aluxnimm/outlookcaldavsynchronizer#distribution-lists will create a contact group as contact entry, but in nextcloud it's visible not as group but as an empty contact.

**Comment by aluxnimm** [comment]
> but in nextcloud it's visible not as group but as an empty contact.
You mean the contact app in Nextcloud? Contact groups as group vcards are not supported there.
This is a pending feature request in Nextcloud but can't be solved by CalDavSynchronizer, our usecase is to sync them back to another Outlook client via the Nextcloud server and that should work even if the group is shown empty on the server contact app.

See
https://github.com/nextcloud/contacts/issues/213
