### ISSUE TITLE
Length of generated name-part in URL

### ISSUE THREAD

**Issue by ralfbecker** [aluxnimm/outlookcaldavsynchronizer#243]
In EGroupware (www.egroupware.org) we have a limit of 128 characters on the name-part (last component) of resource URIs and UIDs. I noticed that CalDAVSynchronizer sometimes generates longer ones. Do you have a maximum length, so we can adapt our database schema to it?

**Comment by aluxnimm** [comment]
Related to
https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/1036/

Name is dependant on UID, should be max 255 but in some cases is longer it seems.
