### ISSUE TITLE
CalDavSynchronizer bringt Outlook zum Absturz

### ISSUE THREAD

**Issue by silas229** [aluxnimm/outlookcaldavsynchronizer#246]
(german)
Eine Neuinstallation bringt nichts. Ich kann es auch nicht wieder aktivieren.
http://go.silas229.de/z5c0x

**Comment by aluxnimm** [comment]
Try to follow
https://blogs.msdn.microsoft.com/emeamsgdev/2017/08/02/outlooks-slow-add-ins-resiliency-logic-and-how-to-always-enable-slow-add-ins/
