### ISSUE TITLE
synchronization fails with error "CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '405' ('Not Allowed')."

### ISSUE THREAD

**Issue by pascalhubacher** [aluxnimm/outlookcaldavsynchronizer#249]
**os:** win 10 fall update
**software:** outloock 2016
caldav service: synology 514 running claendar app
**Error message:**
CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '405' ('Not Allowed'). Message:
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
**description:**
this error is shown in the caldavsynchronizer. if I open the link in the browser I get the following error:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /volume1/@appstore/Calendar/awl/inc/iCalendar.php on line 171 

if I use another user, same config otherwise it works. in the web browser i get a calendar element to download.

**Comment by aluxnimm** [comment]
Attach full debug log.txt and sync report. Don't paste half of the error message. What does "Test or discover settings" say in the sync profile? Looks like a wrong URL and server issues with php setup or some endless loop in php code on serverside maybe caused by an invalid appointment.

**Comment by pascalhubacher** [comment]
![testordiscoversettings2019-01-16 183633](https://user-images.githubusercontent.com/26918784/51267331-bce2bc00-19bd-11e9-9380-974401e416e4.jpg)

**Comment by pascalhubacher** [comment]
the test and discover button comes back with connection sucessfully.

**Comment by pascalhubacher** [comment]
[SynchronizationReports.zip](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/2765405/SynchronizationReports.zip)

**Comment by pascalhubacher** [comment]
The exception says:
ExceptionThatLeadToAbortion>CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '504' ('Gateway Time-out'). Message

the calendar seems to be too big.

**Comment by pascalhubacher** [comment]
is there a way to extend the timeout?

on the synology calendar app running in the browser it takes quite long until the calendar items show up.

**Comment by aluxnimm** [comment]
Did you try to reduce the timerange filter settings in the advanced options and sync only some months for example? Otherwise you need to change server settings (php, web server, etc. to increase timeouts) or change proxy/firewall settings if that causes the timeout.

**Comment by pascalhubacher** [comment]
after changing the time range it works.

thanks for your help.
