### ISSUE TITLE
Issue with Synchronisation of Calendar Categories

### ISSUE THREAD

**Issue by Oswald-Boelcke** [aluxnimm/outlookcaldavsynchronizer#251]
OS Windows 10 Pro 64-bit Version 1803 OS build 17134.677
Outlook MS Office Professional Plus 2016 Version 1902 Build 11328.20158
Synchronisation of Calendar and Contacts with a Posteo account (remark: Synchronisation of Posteo with Android via DAVx5).

I'd changed colours of the categories (all in the master category list), afterwards CalDavSynchroniser (CDS) started into an endless loop of failing attempts to synchronise the calendar (synchronosation reports attached). During this loop, Outlook was not usuable due to the continously opening reports. Outlook had to be forcely closed through task manager.

Work around in order to be able to work with Outlook and to perform synchronisations again: Uninstalled CDS, modified Outlook categories by removing all categories from the master category list and setting colours to "none". Re-installed CDS.
Currently (since about 24 hours) synchronising without any issue.
[SynchronizationReports.zip](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/2992041/SynchronizationReports.zip)

**Comment by aluxnimm** [comment]
Thx. Fixed in 4e6ae93. Will be in next release.
