### ISSUE TITLE
Question: Is there a roadmap for the project?

### ISSUE THREAD

**Issue by SeppPenner** [aluxnimm/outlookcaldavsynchronizer#252]
I was just curious if there is a roadmap to see what changes are planned in the next release(s)?

**Comment by aluxnimm** [comment]
No official roadmap atm, but good point. We should provide one in the future. 
 
Next release will just be some minor bugfixes and mapping of some missing contact fields and will be available next week.

**Comment by SeppPenner** [comment]
Just one short idea: You could use https://help.github.com/en/articles/about-project-boards. Seems to be the easiest solution.
