### ISSUE TITLE
Outlook Add-In can be activated after self-deactivation (this add-in has caused a crash of outlook)

### ISSUE THREAD

**Issue by laberkeks** [aluxnimm/outlookcaldavsynchronizer#262]
After an outlook crash the add-in has been disabled (v3.6.2)
Activation isn't possible, clicking on the button has no effect
I tryed to uninstall v3.6.2 and installed v3.6.1, but no change

Outlook version: 1803 Build 9126.2388

![grafik](https://user-images.githubusercontent.com/12297861/62029884-0c633980-b1e4-11e9-9b4b-3e42d32b6243.png)

**Comment by aluxnimm** [comment]
You need to delete some registry keys, see for example
https://developermessaging.azurewebsites.net/2017/08/02/outlooks-slow-add-ins-resiliency-logic-and-how-to-always-enable-slow-add-ins/

Especially DisabledItems and CrashingAddinList are relevant here.
