### ISSUE TITLE
Outlook for iOS

### ISSUE THREAD

**Issue by tcdaly** [aluxnimm/outlookcaldavsynchronizer#268]
Does this work with Outlook for iOS?

**Comment by aluxnimm** [comment]
No, it's a VSTO C# Addin only for Windows and there are no MacOS versions available and the architecture is completely different.

**Comment by tcdaly** [comment]
Thank you.  Just to be clear, then it's not possible to sync Outlook for Mac or iOS to a CalDav/CardDav server?

**Comment by nertsch** [comment]
Yes, it is not possible to sync Outlook for Mac or iOS to a CalDav/CardDav server with THIS plugin, because this is a Windows-Plugin.

Maybe there are other ways for do achieve that on iOS, but that is beyond our knowledge.

**Comment by tcdaly** [comment]
I see, thank you
