### ISSUE TITLE
Installer file missing

### ISSUE THREAD

**Issue by sundrb** [aluxnimm/outlookcaldavsynchronizer#277]
Couldnt find installer folder
![image](https://user-images.githubusercontent.com/55596936/80527829-9b3ef580-89b2-11ea-896c-c9311c4518cf.png)
Please guide

**Comment by rikroe** [comment]
Don't clone the repository or download the source code, go to the release page of this repository https://github.com/aluxnimm/outlookcaldavsynchronizer/releases and download the latest zip with the verison number in (i.e. OutlookCalDavSynchronizer-3.8.0.zip).
