### ISSUE TITLE
Events disappear in Outlook after sync with Horde

### ISSUE THREAD

**Issue by mytickets617** [aluxnimm/outlookcaldavsynchronizer#283]
After sync:
1) No events, old and new, from Horde appear in Outlook.
2) All event, old and new, from Outlook appear in Horde and disappear in Outlook.

Same issue with log/reports/config and detailed description is reported here:
https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/1431/

**Comment by dpetrov67** [comment]
Here is what was done to fix the issue:

1. Increased memory limit in php.ini to 256M:
memory_limit = 256M

Apparently some operations related to CalDav may require way more than 128M of memory for PHP process.

2. Performed the following updates in horde database:

UPDATE kronolith_events SET event_baseid="" WHERE event_baseid IS NULL;
ALTER TABLE kronolith_events MODIFY event_baseid varchar(255) NOT NULL DEFAULT "";

Everywhere is the code the assumption is that event_baseid can not be null.
Additionally, when the event_baseid field was added (via migration), it was supposed to have empty string as default value, but in our case for whatever reason its default was set to NULL.
We also added NOT NULL constraint there, just in case.
Without this change some events (specificaly events that were created by Outlook CalDav synchronizer were assigned NULL event_baseid and were never retrieved from Kronolith to Outlook. This causes their disappearance in Outlook.

3. Replaced horde/kronolith/lib/Kronolith.php with the modified version with 2 specific fixes (we can provide a patch).
    One is to address exception happening when startDate is not set in addEvents() call.
    The other is to added issue with empty list of events generated if the end date was not specified.

With this fixes the synchronization now works okay. And also it is now possible to open calendars via horde/rpc.php and browse individual events.
