### ISSUE TITLE
401 Unauthorized Error on Azure Single Sign-On

### ISSUE THREAD

**Issue by twes3** [aluxnimm/outlookcaldavsynchronizer#288]
We use Confluence as a platform and would like to use CalDav-Synchronizer to Synch Calendars between Confluence and Outlook. 
To log into Confluence we recently switched to Azure AD and Single Sign On. 

However, now CalDav can't access Confluence any more, even though the credentials are correct. 
Up until this point, the calendar synchronization was working perfectly well.

I've attached the error message:

![grafik](https://user-images.githubusercontent.com/45464588/95203649-5467ee00-07e3-11eb-98de-e6e3eb6b2409.png)

Any help is appreciated.

**Comment by aluxnimm** [comment]
Did you try different auth options? 

If you expand the tree view of the profile you can configure network and proxy options and mapping configuration options. (only in advanced settings)

See force basic auth/preemptive auth settings there.

**Comment by twes3** [comment]
Thank you for the answer, unfortunately it didn't solve the problem. 
I tried any combination of basic auth/preemptive auth without luck. 

Any other suggestions?

**Comment by tpenndorf** [comment]
Hi,
the question is: Is the outlook synchronizer able to authenticate via SAML?

**Comment by twes3** [comment]
We managed to find a working solution for this issue:

When using SAML SSO in Confluence Datacenter/ Server and Team Calendars from Atlassian, [https://marketplace.atlassian.com/apps/72307/team-calendars-for-confluence?hosting=server&tab=overview](https://marketplace.atlassian.com/apps/72307/team-calendars-for-confluence?hosting=server&tab=overview), you can use this API Token app [https://marketplace.atlassian.com/apps/72307/team-calendars-for-confluence?hosting=server&tab=overview](https://marketplace.atlassian.com/apps/1221608/api-token-authentication-confluence?hosting=server&tab=overview). Since it's latest release (1.5.1, released on 11/10/2020) it also supports CalDAV. Every user can then create a personal token which replaces the password in the CalDAV Synchronizer Outlook profile.
Confluence Cloud already provides API Tokens by default, so it should also work.
