### ISSUE TITLE
Import an exported profile from file

### ISSUE THREAD

**Issue by CrysK** [aluxnimm/outlookcaldavsynchronizer#310]
I got Caldavsynchronizer 4.0.0, Outlook 365 and some Nextcloud profiles. These are running fine on my device A. There I click in Caldavsynchronizer on "Export profiles to file" and on device B (with the same configuration) on "Import profiles from file" now I get the following error message and no profile is imported:
![grafik](https://user-images.githubusercontent.com/43782371/112846980-e53ec880-90a6-11eb-9a5d-3d03925cf13e.png)

**Comment by aluxnimm** [comment]
Should be fixed in next release. There is an access problem to one of the exchange folders.
