### ISSUE TITLE
Is it possible to use this in the online (pwa) version

### ISSUE THREAD

**Issue by coxackie** [aluxnimm/outlookcaldavsynchronizer#311]
Hi there. This is not a bug, but a question / feature request. I am a Linux user, and can only use Outlook (officially) from the web app. I checked the add-ins for the calendar, and `caldavsynchronizer` is not there. Would it be possible to port it, so that users outside of Windows can benefit from such integration?

Many thanks in advance for your consideration.

**Comment by nertsch** [comment]
Outlookcaldavsynchronizer is a COM-Addin and as far as I know it cannot be used with "Outlook on the Web".
Currently we have no plans to port that to a JavaScript-Addin suitable for "Outlook on the Web".

br
GErhard
