### ISSUE TITLE
setup.exe

### ISSUE THREAD

**Issue by armonica17** [aluxnimm/outlookcaldavsynchronizer#313]
Hi. Time for me to be embarrassed I have a feeling. I downloaded the git .zip into a dir named c:\other. I didn't see setup.exe in the file explorer. I think I read the instructions. I extracted the zip into c:\other. I expected to see a setup.exe file where README.md is contained. I'm not finding the setup.exe file anywhere. Maybe it's missing or I missed it?

Thanks,
Rob

**Comment by nertsch** [comment]
You downloaded the sourcecode.
The binaries (setup.exe) can be found here: https://sourceforge.net/projects/outlookcaldavsynchronizer/ 
by clicking on the green download button
