### ISSUE TITLE
Sync stuck with "Both COUNT and UNTIL cannot be supplied together; they are mutually exclusive." -> error logging unclear

### ISSUE THREAD

**Issue by khaliddermoumi** [aluxnimm/outlookcaldavsynchronizer#332]
Hi! I have observed calendar, which is stuck on sync with an error:  "Both COUNT and UNTIL cannot be supplied together; they are mutually exclusive."

See: 
[SynchronizationReport-2021-09-28.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/7243942/SynchronizationReport-2021-09-28.txt)

I see 3 problems with this behaviour:

* most of all, the error log does not say which entry is causing the problem. The log should say, which entry at which date causes the problem. Otherwise, the user will not be able to fix anything.
* also, the log should be clear whether the error is in the remote calendar, or the local, so the user can take appropriate means
* the sync should not just look like it got stuck with an error, but be clear about what happened in the operation, just like:
    * "Sync: 23 events synced successfully, 1 failure when synching (see error log)", so it is clear to end users what has happened

Right now I am guessing what happened here: I believe there is a data error in the remote calendar, and the synchronizer belches on this, but I am not sure what has happened, because the error is not logged in a really informative way.

**Comment by aluxnimm** [comment]
Actually you can click on the server id in the sync report to see which entry causes this and the error is clearly stated in the log together with the id of the remote element:
/owncloud/remote.php/dav/calendars/vera/personal/46af470f-da62-4185-8f0d-156b28d30c98.ics</EntityId>
      <Error>System.ArgumentException: Both COUNT and UNTIL cannot be supplied together; they are mutually exclusive.

So you just need to fix/delete that entry and the error is gone.
