### ISSUE TITLE
Daily task with no end date does not sync correctly

### ISSUE THREAD

**Issue by meichthys** [aluxnimm/outlookcaldavsynchronizer#334]
Syncing a Daily task that has no end date does not sync correctly to Outlook. I've tested syncing from different backends (Radicale, Nextcloud, etc), and creating the task from different front ends (Outlook, Thunderbird).

How to reproduce:

1. Create Daily task (this example uses Thunderbird):
![image](https://user-images.githubusercontent.com/10717998/136438098-4cc40044-3d60-4845-af2d-5fee8ee0175c.png)
2. Sync with backend that supports reoccurring tasks (Radicale, Nextcloud, etc)
3. Sync with Outlook (different outlook if using outlook to create the task):
4. Note that the task has changed from no end date, to having an end date:
![image](https://user-images.githubusercontent.com/10717998/136438722-bd006f1e-5ca1-41ce-95f6-342ae090caa3.png)

For reference I'm attaching exported ics files from Thunderbird before outlook imported it, and one that is created in outlook, synced to thunderbird, then exported:

[Created in Thunderbird and Exported in Thunderbird.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/7306045/Created.in.Thunderbird.and.Exported.in.Thunderbird.txt)
[Created in Outlook and Exported in Thunderbird.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/7306044/Created.in.Outlook.and.Exported.in.Thunderbird.txt)

**Comment by aluxnimm** [comment]
Thank you and sorry for late reply. Same problem for recurring events too with no enddate, need to set Property NoEndDate to true explicitely. Will be fixed in next release.
