### ISSUE TITLE
is-ti working with Outlook 2021 ???

### ISSUE THREAD

**Issue by pnoelfr** [aluxnimm/outlookcaldavsynchronizer#336]
Hi
i have tested
But it seem doesn't work
CPU 100%

**Comment by swalterfub** [comment]
I'm also interested if this works. On the web page of caldavsynchronizer, it says compatible with 365 and 2019, but does not explicitly mention 2021.

**Comment by aluxnimm** [comment]
Yes it should work also with Outlook 2021.

**Comment by swalterfub** [comment]
Yes I can confirm it!
