### ISSUE TITLE
Virus on  last version 4.2.0 ? 

### ISSUE THREAD

**Issue by Benoit75** [aluxnimm/outlookcaldavsynchronizer#344]
Hi, 
I download the last version on https://caldavsynchronizer.org/download-2/ (url https://github.com/aluxnimm/outlookcaldavsynchronizer/releases/download/v4.2.0/OutlookCalDavSynchronizer-4.2.0.zip)
and Avast give an alert ** Win32: Malware-gen ** on CalDavSynchroniser.resources.DLL. Please this Screen capture attached. 
Any thought ? 

Thank you, 
B.
![Capture](https://user-images.githubusercontent.com/5913621/156532472-3f31670c-a32a-43fe-bfb2-61872cdf7787.JPG)

**Comment by aluxnimm** [comment]
This is just the resource dll with the translation texts for each language.

**Comment by Benoit75** [comment]
So it's a false positive ?

**Comment by aluxnimm** [comment]
yes, hopefully they will update their database after our new release, sometimes takes some days.

**Comment by Benoit75** [comment]
Seems to be Ok now.
Thank's
