### ISSUE TITLE
Option to disable all error messaging windows?

### ISSUE THREAD

**Issue by Spanni26** [aluxnimm/outlookcaldavsynchronizer#348]
Hello,

great tool so far 👍 

But one wish: 
My caldav-server is reachable only, if I'm connected via VPN. When I'm not connected, I get error messaging window.

An option to suppress this Window would be nice :)

**Comment by aluxnimm** [comment]
Actually this setting exists, check general options/synchronization reports and choose "No" in dropdown for show reports and popup.
