### ISSUE TITLE
CalDAV synchronizing error with error messages

### ISSUE THREAD

**Issue by eungmo** [aluxnimm/outlookcaldavsynchronizer#349]
I got this error message.
"System.Xml.XmlException: '', hexadecimal value 0x08, is an invalid character. Line 3668. position 9.

It happened with only few calendars.
I have 10 calendars and the 2 calendars are not synchronized with this exception. (8 calendars are OK)
![image001](https://user-images.githubusercontent.com/1171393/161499924-4577140d-c435-40e2-95b5-e3f6a2cfab4a.png)

I checked my caldav server and access log provide non error code and error message.
I think caldav server provided the schedules data but the client (CalDAV Synchronizer) cannot parsing data.
Could anyone help me to solve this issue?

- Outlook version: 2019 MSO (16.0.10384.20023) 64bit
- CalDAV Synchronizer version: 4.2.0.0

**Comment by mgrn0** [comment]
I am having the same problem, except the hexadecimal value being complained about is 0x15 – and I do have the setting "Accept invalid chars in server response" enabled, but it does not help.

How can I figure out which (calender) event is causing the issue? It seems to be bound to individual events since some days sync works and a few days later it stops (and repeating...)

**Comment by eungmo** [comment]
I totally agree with you.
If I can notice what event makes this error, then it would be really help me.
(Could anyone provide the event uid on the message when the error (System.Xml.XmlException) occurred?)

**Comment by mgrn0** [comment]
In my case I have to fiddle around with the amount of days to sync in the future (try and error between 5 and 15 days) in order to get a sync working at all; this ends up in dozens of duplicated entries for my recurring events :/

**Comment by mgrn0** [comment]
I have set the synchronizer to 'just' mirror all events (to wipe everything on sync and just mirror events in one direction), however I end up with dozens of duplicates while the above error occurs. Is this normal?

**Comment by mgrn0** [comment]
really nobody having same / similar issues? it's such an annoying bug…

**Comment by aluxnimm** [comment]
You need to export the whole calendar as an ics file from the server, open with notepad++ and find that invalid characters.
We will hopefully fix the issue and filter our invalid xml characters in our next release.

**Comment by mgrn0** [comment]
just want to leave that here: synchronization works flawless for me since that last release. never again had the problem / error showing up. thanks for fixing this!
