### ISSUE TITLE
Import doesn't work System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by T-D3V** [aluxnimm/outlookcaldavsynchronizer#381]
Import of exported profiles doesn't work.

Exported Machine: OS: Windows 11 PRO
Imported Machine: OS: Windows Server 2019
Don't ask why just know it doesn't work.
Also I can't figure out if it's related to fs permissions or exchange permissions.

![caldav](https://user-images.githubusercontent.com/40610605/216549614-6a17630b-ae4a-48c3-bb5a-bb61a1db4e37.png)

**Comment by aluxnimm** [comment]
Must be exchange permissions issue.

**Comment by aluxnimm** [comment]
Should be fixed in next release when we catch that exception and ignore that folder with missing access rights.
