### ISSUE TITLE
Sync public read-only calendar

### ISSUE THREAD

**Issue by q-wertz** [aluxnimm/outlookcaldavsynchronizer#383]
Not sure if missing or a configuration issue on my side.

Currently it looks like it is impossible to add a one way sync of a public shared calendar.

1. Leaving credentials empty and pressing the test button raises an error
2. Leaving credentials empty skip test and just go on raises an error on next sync
3. Adding fake credentials raises an error

Setup:

Nextcloud read-only calendar shared via link. Tested 
1. https: `https://test.com/apps/calendar/p/RRGfHC6KgrmPqDWP`
2. webcal: `webcal://test.com/remote.php/dav/public-calendars/RRGfHC6KgrmPqDWP`
3. webcal link with appended `?export`: `webcal://test.com/remote.php/dav/public-calendars/RRGfHC6KgrmPqDWP/?export`
In Thunderbird the webcal calendars work as expected…

Adding the 3rd link as network calendar directly Outlook only downloads the ics file once and later added items are not synced.

**Comment by aluxnimm** [comment]
Those webcals urls are just ics files which can be downloaded by a client but they are not CalDAV resources and can't be used in our client. You can only use them as readonly network calendar in Outlook, 2nd url shoud work there as well maybe.

**Comment by q-wertz** [comment]
Sorry for the noise.

It works now (at least kind of). One requires link #3 (at least on Nextcloud instances) and a lot of patience. 

We most likely are running into a combination of [Not possible to add an internet calendar](https://learn.microsoft.com/en-us/outlook/troubleshoot/calendaring/cannot-add-an-internet-calendar) ([*irony on*] many thanks to the "new modern authentication stack" of Microsoft [*irony off*]) and [Subscribed internet calendars do not sync](https://answers.microsoft.com/en-us/outlook_com/forum/all/outlook-365-subscribed-internet-calendars-do-not/d3085181-c105-4ee7-ada4-9ead19116eec).
