### ISSUE TITLE
Allow synchronization of alarms to be reminded after event start

### ISSUE THREAD

**Issue by ebfdhac** [aluxnimm/outlookcaldavsynchronizer#384]
I've been using outlookcaldavsynchronizer to sync my calendars for a while. The calendars are managed on a Synology DSM and maintained via the IOS calendar client, the Synology web interface and Outlook. This works very well so far.

However, I keep getting the warning message `Alarm has an invalid duration or is not before event start. Ignoring.` if I want to be reminded for an all-day appointment at 8:00 a.m. on the day of the event, for example. 

Why are alarms not allowed during the appointment period? Can this be customized?

**Comment by aluxnimm** [comment]
It's an Outlook limitation, not on our side. So we have to ignore iCalendar alarms after the event start time.
