### ISSUE TITLE
Issue on recurring events with COUNT != 0 ?

### ISSUE THREAD

**Issue by armoisan** [aluxnimm/outlookcaldavsynchronizer#388]
Hello, 

by playing with sabre/dav server and caldavsynchronizer 4.4.0 on outlook (Microsoft® Outlook® LTSC MSO (16.0.14332.20478) 64 bit) , the recurring events with RRULE:FREQ=DAILY;COUNT=xxx seem to be considered with no end date in outlook.

Could it be a problem of the format of the events or an issue from to the latest modification done in 4.4.0 related to the NoEndDate ?

**Comment by aluxnimm** [comment]
You are right, we fixed the UNTIL handling but broke the COUNT it seems. Need to look into it. Thanks for reporting!

**Comment by aluxnimm** [comment]
fixed in 4.4.1.

**Comment by armoisan** [comment]
hello, thanks a lot for this quick fix

**Comment by Jisco** [comment]
Hi,
I don't know exactly whether my error is related to this, but if I create a recurring appointment and set it to end after X appointments, it now works (with Version 4.4.1). But as soon as I edit this appointment somehow, this information is lost and the appointment becomes "infinite" again.

**Comment by Jisco** [comment]
Created new Issue: #434
