### ISSUE TITLE
Outlook meetings are not synced

### ISSUE THREAD

**Issue by skaphod** [aluxnimm/outlookcaldavsynchronizer#52]
simple calendar entries are working wonderfully, but meetings with organisers are not synced

**Comment by aluxnimm** [comment]
Organizer and attendees are supported aswell. Please provide a debug sync log (for details see readme) and details to outlook version and which caldav server you use

**Comment by skaphod** [comment]
Outlook 2010. Calendar entries created with business calendar app on android phone via active sync (ms exchange) are created as meetings since version 2 of business calendar. I moved these meetings to an owncloud calendar via Outlook 2010 and the cFOS CalDAV plugin for Outlook. When using Outlook CalDav Synchronizer to sync that owncloud calendar into a new calendar folder in Outlook 2010 these meetings are not showing up in Outlook.

**Comment by aluxnimm** [comment]
Nice sync scenario ;-)
Then we need a sync log and an example of an ics file of an event in Owncloud that doesn't show up in Outlook to see where the problem could be.

**Comment by skaphod** [comment]
does that help?

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Microsoft Corporation//Outlook 14.0 MIMEDIR//EN
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:20150730T135235Z
DTEND:20150907T160000Z
DTSTAMP:20150730T135235Z
DTSTART:20150907T060000Z
LAST-MODIFIED:20150730T135235Z
PRIORITY:5
SEQUENCE:0
SUMMARY;LANGUAGE=de:Test
TRANSP:OPAQUE
UID:9b7afadc-bc4a-481b-a30f-99ba3ef306c0
X-ALT-DESC;FMTTYPE=text/html:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//E
 N">\n<HTML>\n<HEAD>\n<META NAME="Generator" CONTENT="MS Exchange Server ve
 rsion 14.02.5004.000">\n<TITLE></TITLE>\n</HEAD>\n<BODY>\n\n\n</BODY>\n</HTML>
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
X-MS-OLK-AUTOFILLLOCATION:TRUE
ORGANIZER;CN:MAILTO:unknown@cfos.de
END:VEVENT
END:VCALENDAR

line 21:13: expecting "EQUAL", found ':'
 ERROR 2015-07-30 15:52:48,926 [7] hronizer.Implementation.CalDavRepository . TryDeserializeCalendar         - Could not deserilaize ICalData of '###.ics':

**Comment by aluxnimm** [comment]
Yes that helps!

Your ics file is invalid.
The organizer CN property has to have a value, e.g. CN=Testuser
So your CFOS plugin generates wrong ics files and uploads them to Owncloud. 

Try to upload them with our tool instead and report any problems. We can't and won't import invalid ics files. You can validate your file for example at
http://severinghaus.org/projects/icv/

**Comment by skaphod** [comment]
and the ics (i replaced personal information with ###):

BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 14.0 MIMEDIR//EN
VERSION:2.0
METHOD:REQUEST
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VEVENT
CLASS:PRIVATE
CREATED:20150730T135209Z
DTEND:20150907T160000Z
DTSTAMP:20150730T135209Z
DTSTART:20150907T060000Z
LAST-MODIFIED:20150730T135209Z
ORGANIZER;CN="###":mailto:###@###.de
PRIORITY:5
SEQUENCE:0
SUMMARY;LANGUAGE=de:Test
TRANSP:OPAQUE
UID:9b7afadc-bc4a-481b-a30f-99ba3ef306c0
X-ALT-DESC;FMTTYPE=text/html:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//E
	N">\n<HTML>\n<HEAD>\n<META NAME="Generator" CONTENT="MS Exchange Server ve
	rsion 14.02.5004.000">\n<TITLE></TITLE>\n</HEAD>\n<BODY>\n\n\n</BODY>\n</HTML>
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
X-MS-OLK-AUTOFILLLOCATION:TRUE
END:VEVENT
END:VCALENDAR

**Comment by skaphod** [comment]
ok thanks a lot! I was just wondering about that unknown@cfos stuff...
