### ISSUE TITLE
Free/busy doesn't work

### ISSUE THREAD

**Issue by lukasde** [aluxnimm/outlookcaldavsynchronizer#53]
At first I thank you for good software. But I found that free/busy doesn't work. Is it implemented? Or do you have it in roadmap?

Thanks

**Comment by aluxnimm** [comment]
what caldav server do you use and what sync direction to you plan to use for free/busy information? you can configure Outlook with a global free/busy url from your caldav server which matches your email domain with placeholder like %NAME%@yourdomain.com. For that you don't need the plugin.

**Comment by lukasde** [comment]
Hi,
thank you for reply. I tried it with SOGo, but I will use DAViCAL in 
future.

I didn't know about global free/busy in Outlook. I will test it, but I 
think that better is use plugin what is checking free/busy status online 
with caldav server
Do you have also carddav plugin in roadmap? :-)


br, Lukas



------ Původní zpráva ------
Od: "Alex Nimmervoll" <notifications@github.com>
Komu: "aluxnimm/outlookcaldavsynchronizer" 
<outlookcaldavsynchronizer@noreply.github.com>
Kopie: "lukasde" <lukas@deseyve.cz>
Odesláno: 06.08.2015 13:06:05
Předmět: Re: [outlookcaldavsynchronizer] Free/busy doesn't work (#53)

**Comment by aluxnimm** [comment]
yes carddav is planned but will take some time. priority is to fix last caldav bugs and finish work with tasks/vtodo first.

**Comment by aluxnimm** [comment]
carddav is available now.

**Comment by Jerome-Maurin** [comment]
Hi, thank for the great quality of your software.

I was wondering if you plan to support https://tools.ietf.org/html/rfc6638#section-5 regarding the ability to check for "Busy Time Information" ?

In my case, I'm using Nextcloud witch doesn't provide a "free/busy url" to my knowledge (https://github.com/nextcloud/calendar/issues/39#issuecomment-432623211).

Thanks
