### ISSUE TITLE
Outlook 2007 support

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [aluxnimm/outlookcaldavsynchronizer#54]
Hi, great project you have here!

Is this certain not to work with Outlook 2007 due to technical differences or did you just not check yet?
Is it worth a try?

**Comment by aluxnimm** [comment]
No we only support Ol 2010/13. you won't even see the gui because Ol 2007 doesn't  support ribbon ui. theoreticallyrics it would be possible to change some code to support 2007 but we won't bother. feel free to clone the repo or update your Ol :)

**Comment by aluxnimm** [comment]
Implemented support for OL2007 in version 1.3.4.

**Comment by 1337sup3rh4x0r** [comment]
Thank you very much! It works great
