### ISSUE TITLE
Allow updates and automatic upgrades

### ISSUE THREAD

**Issue by extremeshok** [aluxnimm/outlookcaldavsynchronizer#55]
Hi

Please could you allow the installer to update the app, without first requiring an uninstall via add-remove programs, if this is not possible please allow the installer to do the uninstall the old version before it installs the new one.

Any chance for an automatic upgrade feature ?

**Comment by nertsch** [comment]
I will take care about this in the next few weeks.
Please note that I do NOT maintain Tickets on github.
I will create Tickets for this issues on Sourceforge:
https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/?source=navbar
