### ISSUE TITLE
Cannot connect Google CalDAV new endpoint

### ISSUE THREAD

**Issue by fangchih** [aluxnimm/outlookcaldavsynchronizer#57]
Hi,

Because the old endpoint was deprecated, can you add support for new endpoint?
It need https + oauth2 authentication.
Please refer: https://developers.google.com/google-apps/calendar/caldav/v2/guide

many thanks.
Fangchih.

**Comment by nertsch** [comment]
HI,

Please create an issue at  https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/?source=navbar
I'm not working with github. It serves just as a mirror.

br
Gerhard

**Comment by aluxnimm** [comment]
Implemented in 1.1.10

**Comment by fangchih** [comment]
tks.
