### ISSUE TITLE
INTERVAL in RRULE must be a positive integer!

### ISSUE THREAD

**Issue by fajabird** [aluxnimm/outlookcaldavsynchronizer#58]
This is what I see when trying to sync from outlook to my owncloud server:

 INFO  2015-08-25 11:03:08,535 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . MoveNext                       - Synchronization manually triggered
 INFO  2015-08-25 11:03:08,537 [ VSTA_Main] ronizer.Scheduling.SynchronizationWorker . MoveNext                       - Starting 'Running synchronization profile 'Owncloud''
 INFO  2015-08-25 11:03:08,546 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Entered. Syncstrategy 'OneWayInitialSyncStateCreationStrategy_AToB`6' with Atype='AppointmentItemWrapper' and Btype='IICalendar'
 INFO  2015-08-25 11:03:08,578 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Starting 'CalDavRepository.GetVersions'
 INFO  2015-08-25 11:03:09,212 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Duration of 'CalDavRepository.GetVersions': 00:00:00.6321631
 ERROR 2015-08-25 11:03:09,213 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Status: ProtocolError
StatusCode: InternalServerError
StatusDescription: Internal Server Error
Body: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.3</s:sabredav-version>
  <s:exception>InvalidArgumentException</s:exception>
  <s:message>INTERVAL in RRULE must be a positive integer!</s:message>
</d:error>

System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (500) Interner Serverfehler.
   bei System.Net.HttpWebRequest.GetResponse()
   bei CalDavSynchronizer.DataAccess.WebDavClient.ExecuteWebDavRequest(Uri url, Action`1 modifier, String requestBody)
   bei CalDavSynchronizer.DataAccess.WebDavClient.ExecuteWebDavRequestAndReadResponse(Uri url, Action`1 modifier, String requestBody)
   bei CalDavSynchronizer.DataAccess.CalDavDataAccess.GetEntities(Nullable`1 range, String entityType)
   bei CalDavSynchronizer.DataAccess.CalDavDataAccess.GetEvents(Nullable`1 range)
   bei CalDavSynchronizer.Implementation.CalDavRepository.GetVersions()
   bei GenSync.Synchronization.Synchronizer`6.<Synchronize>d__10.MoveNext()
 INFO  2015-08-25 11:03:09,225 [ VSTA_Main] ronizer.Scheduling.SynchronizationWorker . MoveNext                       - Duration of 'Running synchronization profile 'Owncloud'': 00:00:00.6788975

**Comment by fajabird** [comment]
BTW: I even get this error with an empty outlook calendar, must be some general issue. Maybe rfc-2445 is relevant.

**Comment by fajabird** [comment]
BTW: I installed version 1.03 from http://sourceforge.net/projects/outlookcaldavsynchronizer/

**Comment by nertsch** [comment]
Hi,
"(500) Interner Serverfehler." means that the Bug lies inside your Server (SabreDAV)
Please turn on DEBUG log and retry it (Intructions can be found at https://sourceforge.net/p/outlookcaldavsynchronizer/code/ci/master/tree/README.md ) Then you can see the URI of the event which caused the error in the logfile. 
If you paste this URI into the address bar of your browser you should get the same error.

br
Gerhard

**Comment by nertsch** [comment]
Sorry, now I saw, that the error occurs when the List of Events is fetched (turning on DEBUG won't bring more information)
It seems that there is one Event with corrupt data, which causes an error. 
How this this Data get into the Server. Was it imported via CalDav Synchronizer ?

br
Gerhard

**Comment by fajabird** [comment]
At work I have a outlook 2010 client which connects to an exhange server. Now I want to use your tool to sync my calendar events over to my owncloud server into a empty calendar.

**Comment by nertsch** [comment]
As you can see in the logfile CalDav Synchronizer is Querying the Server for Events in a specific time range. If this results in a Internal Server Error with the Message "INTERVAL in RRULE must be a positive integer" , although the calendar is empty than this is a Bug of the Server.

br
Gerhard

**Comment by fajabird** [comment]
Seems that synchronization does work, even I get this error. But there is another problem: when I enable the time filter most events are not synced. So currently I left it off and works very well after the first (very long) run.

**Comment by nertsch** [comment]
There is an Bug in 1.0.3
Please use 1.0.4

**Comment by fajabird** [comment]
Just looked into the code, kind of funny this error :-)

Thanks for responding that fast. Already installed the new version.

**Comment by aluxnimm** [comment]
Maybe caused from an event in Owncloud with INTERVAL=0, a every workday recurrence wrongly synced from Outlook, see https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/99

Fixed from our side in latest commit, will be in next release.

**Comment by may-bee** [comment]
I again get this issue with the latest version (1.14.2):

```xml
<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>CalDAV</ProfileName>
  <ProfileId>4664dc15-b502-4591-9c6c-ce98ca8d7dca</ProfileId>
  <StartTime>2016-01-21T13:42:55.0330674Z</StartTime>
  <InitialEntityMatchingPerformed>false</InitialEntityMatchingPerformed>
  <LoadErrors />
  <EntitySynchronizationReports />
  <ExceptionThatLeadToAbortion>System.Net.Http.HttpRequestException: Response status code does not indicate success: '500' ('InternalServerError'). Message:
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"&gt;
  &lt;s:sabredav-version&gt;2.1.7&lt;/s:sabredav-version&gt;
  &lt;s:exception&gt;InvalidArgumentException&lt;/s:exception&gt;
  &lt;s:message&gt;INTERVAL in RRULE must be a positive integer!&lt;/s:message&gt;
&lt;/d:error&gt;

   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;EnsureSuccessStatusCode&gt;d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequest&gt;d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequestAndReadResponse&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.&lt;GetEntities&gt;d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.Synchronization.Synchronizer`6.&lt;SynchronizeNoThrow&gt;d__4.MoveNext()</ExceptionThatLeadToAbortion>
  <Duration>00:00:03.9703970</Duration>
</SynchronizationReport>
```

If you need further log information, tell me what you need.

**Comment by aluxnimm** [comment]
we fixed that, we don't create such events but you have to find events with interval 0 in the owncloud db and remove them as mentioned above.  this error comes from the server when fetching the events. nothing we can do about it.
