### ISSUE TITLE
Feature Request: (HTTP)-Proxy support for corporate networks

### ISSUE THREAD

**Issue by fajabird** [aluxnimm/outlookcaldavsynchronizer#59]
I'd like to use this great application in my corporate network to sync outlook calendars to my phone via owncloud. We are using http-proxies, thus I cannot get a connection to my outside server. A proper http-proxy configuration would requiere either NTLM support or static username and password boxes along the http-proxy url box.

**Comment by nertsch** [comment]
Please see https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/69/ for answer.

**Comment by aluxnimm** [comment]
Proxy support in GUI with basic auth and NTLM implemented in 1.5.1
