### ISSUE TITLE
Issue when synching from OwnCloud when the event was created from Android using iCal to sync

### ISSUE THREAD

**Issue by captainwasabi** [aluxnimm/outlookcaldavsynchronizer#61]
Here is the logfile from the last sync (Note: is there an Android calendar app that is known to work?):

INFO  2015-09-22 11:30:21,053 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . MoveNext                       - Synchronization manually triggered
 INFO  2015-09-22 11:30:21,053 [ VSTA_Main] ronizer.Scheduling.SynchronizationWorker . MoveNext                       - Starting 'Running synchronization profile 'DAS Cloud2''
 INFO  2015-09-22 11:30:21,053 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`6' with Atype='AppointmentItemWrapper' and Btype='IICalendar'
 INFO  2015-09-22 11:30:21,068 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Starting 'CalDavRepository.GetVersions'
 INFO  2015-09-22 11:30:21,068 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Duration of 'CalDavRepository.GetVersions': 00:00:00.0001924
 INFO  2015-09-22 11:30:21,681 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Atype delta: Unchanged: 2 , Added: 0 , Deleted 0 ,  Changed 0
 INFO  2015-09-22 11:30:21,696 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Btype delta: Unchanged: 2 , Added: 1 , Deleted 0 ,  Changed 0
 INFO  2015-09-22 11:30:21,712 [ VSTA_Main] hronizer.Implementation.CalDavRepository . MoveNext                       - Starting 'CalDavRepository.Get (1 entitie(s))'
 ERROR 2015-09-22 11:30:22,245 [        15] hronizer.Implementation.CalDavRepository . TryDeserializeCalendar         - Could not deserilaize ICalData of '/remote.php/caldav/calendars/631B1CCB-5B96-4278-9BA8-D27A9B389DD5/chuckdas2/a6670fc9-957c-40ef-85a7-287d4de551f0.ics':
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//NTBAB//Android//CalendarSync//13.43
BEGIN:VTIMEZONE
TZID:America/New_York
BEGIN:STANDARD
DTSTART:20071104T020000
TZOFFSETTO:-0500
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
TZOFFSETFROM:-0400
TZNAME:EST
END:STANDARD
BEGIN:STANDARD
DTSTART:18831118T120358
TZOFFSETTO:-0500
RDATE:18831118T120358
TZOFFSETFROM:-0456
TZNAME:EST
END:STANDARD
BEGIN:STANDARD
DTSTART:19181027T020000
TZOFFSETTO:-0500
RDATE:19181027T020000
RDATE:19191026T020000
RDATE:19201031T020000
RDATE:19210925T020000
RDATE:19220924T020000
RDATE:19230930T020000
RDATE:19240928T020000
RDATE:19250927T020000
RDATE:19260926T020000
RDATE:19270925T020000
RDATE:19280930T020000
RDATE:19290929T020000
RDATE:19300928T020000
RDATE:19310927T020000
RDATE:19320925T020000
RDATE:19330924T020000
RDATE:19340930T020000
RDATE:19350929T020000
RDATE:19360927T020000
RDATE:19370926T020000
RDATE:19380925T020000
RDATE:19390924T020000
RDATE:19400929T020000
RDATE:19410928T020000
RDATE:19450930T020000
RDATE:19460929T020000
RDATE:19470928T020000
RDATE:19480926T020000
RDATE:19490925T020000
RDATE:19500924T020000
RDATE:19510930T020000
RDATE:19520928T020000
RDATE:19530927T020000
RDATE:19540926T020000
RDATE:19551030T020000
RDATE:19561028T020000
RDATE:19571027T020000
RDATE:19581026T020000
RDATE:19591025T020000
RDATE:19601030T020000
RDATE:19611029T020000
RDATE:19621028T020000
RDATE:19631027T020000
RDATE:19641025T020000
RDATE:19651031T020000
RDATE:19661030T020000
RDATE:19671029T020000
RDATE:19681027T020000
RDATE:19691026T020000
RDATE:19701025T020000
RDATE:19711031T020000
RDATE:19721029T020000
RDATE:19731028T020000
RDATE:19741027T020000
RDATE:19751026T020000
RDATE:19761031T020000
RDATE:19771030T020000
RDATE:19781029T020000
RDATE:19791028T020000
RDATE:19801026T020000
RDATE:19811025T020000
RDATE:19821031T020000
RDATE:19831030T020000
RDATE:19841028T020000
RDATE:19851027T020000
RDATE:19861026T020000
RDATE:19871025T020000
RDATE:19881030T020000
RDATE:19891029T020000
RDATE:19901028T020000
RDATE:19911027T020000
RDATE:19921025T020000
RDATE:19931031T020000
RDATE:19941030T020000
RDATE:19951029T020000
RDATE:19961027T020000
RDATE:19971026T020000
RDATE:19981025T020000
RDATE:19991031T020000
RDATE:20001029T020000
RDATE:20011028T020000
RDATE:20021027T020000
RDATE:20031026T020000
RDATE:20041031T020000
RDATE:20051030T020000
RDATE:20061029T020000
TZOFFSETFROM:-0400
TZNAME:EST
END:STANDARD
BEGIN:STANDARD
DTSTART:19200101T000000
TZOFFSETTO:-0500
RDATE:19200101T000000
RDATE:19420101T000000
RDATE:19460101T000000
RDATE:19670101T000000
TZOFFSETFROM:-0500
TZNAME:EST
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20070311T030000
TZOFFSETTO:-0400
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
TZOFFSETFROM:-0500
TZNAME:EDT
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19180331T030000
TZOFFSETTO:-0400
RDATE:19180331T030000
RDATE:19190330T030000
RDATE:19200328T030000
RDATE:19210424T030000
RDATE:19220430T030000
RDATE:19230429T030000
RDATE:19240427T030000
RDATE:19250426T030000
RDATE:19260425T030000
RDATE:19270424T030000
RDATE:19280429T030000
RDATE:19290428T030000
RDATE:19300427T030000
RDATE:19310426T030000
RDATE:19320424T030000
RDATE:19330430T030000
RDATE:19340429T030000
RDATE:19350428T030000
RDATE:19360426T030000
RDATE:19370425T030000
RDATE:19380424T030000
RDATE:19390430T030000
RDATE:19400428T030000
RDATE:19410427T030000
RDATE:19460428T030000
RDATE:19470427T030000
RDATE:19480425T030000
RDATE:19490424T030000
RDATE:19500430T030000
RDATE:19510429T030000
RDATE:19520427T030000
RDATE:19530426T030000
RDATE:19540425T030000
RDATE:19550424T030000
RDATE:19560429T030000
RDATE:19570428T030000
RDATE:19580427T030000
RDATE:19590426T030000
RDATE:19600424T030000
RDATE:19610430T030000
RDATE:19620429T030000
RDATE:19630428T030000
RDATE:19640426T030000
RDATE:19650425T030000
RDATE:19660424T030000
RDATE:19670430T030000
RDATE:19680428T030000
RDATE:19690427T030000
RDATE:19700426T030000
RDATE:19710425T030000
RDATE:19720430T030000
RDATE:19730429T030000
RDATE:19740106T030000
RDATE:19750223T030000
RDATE:19760425T030000
RDATE:19770424T030000
RDATE:19780430T030000
RDATE:19790429T030000
RDATE:19800427T030000
RDATE:19810426T030000
RDATE:19820425T030000
RDATE:19830424T030000
RDATE:19840429T030000
RDATE:19850428T030000
RDATE:19860427T030000
RDATE:19870405T030000
RDATE:19880403T030000
RDATE:19890402T030000
RDATE:19900401T030000
RDATE:19910407T030000
RDATE:19920405T030000
RDATE:19930404T030000
RDATE:19940403T030000
RDATE:19950402T030000
RDATE:19960407T030000
RDATE:19970406T030000
RDATE:19980405T030000
RDATE:19990404T030000
RDATE:20000402T030000
RDATE:20010401T030000
RDATE:20020407T030000
RDATE:20030406T030000
RDATE:20040404T030000
RDATE:20050403T030000
RDATE:20060402T030000
TZOFFSETFROM:-0500
TZNAME:EDT
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19420209T030000
TZOFFSETTO:-0400
RDATE:19420209T030000
TZOFFSETFROM:-0500
TZNAME:EWT
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19450814T190000
TZOFFSETTO:-0400
RDATE:19450814T190000
TZOFFSETFROM:-0400
TZNAME:EPT
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=America/New_York:20150922T120000
LAST-MODIFIED:20150922T152500Z
UID:a6670fc9-957c-40ef-85a7-287d4de551f0
STATUS:TENTATIVE
CREATED:20150922T152500Z
CLASS:PUBLIC
SUMMARY:Test 3 from Android
DTSTAMP:20150922T152500Z
TRANSP:OPAQUE
DTEND;TZID=America/New_York:20150922T130000
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Alarm
TRIGGER:-PT15M
END:VALARM
END:VEVENT
END:VCALENDAR

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DDay.iCal.iCalTimeZoneInfo.<>c__DisplayClass2.<GetObservance>b__0(IPeriod p)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DDay.iCal.iCalTimeZoneInfo.GetObservance(IDateTime dt)
   at DDay.iCal.iCalTimeZone.GetTimeZoneObservance(IDateTime dt)
   at DDay.iCal.iCalDateTime.GetTimeZoneObservance()
   at DDay.iCal.iCalDateTime.get_UTC()
   at DDay.iCal.iCalDateTime.op_Subtraction(iCalDateTime left, IDateTime right)
   at DDay.iCal.iCalDateTime.Subtract(IDateTime dt)
   at DDay.iCal.Event.ExtrapolateTimes()
   at DDay.iCal.Event.OnDeserialized(StreamingContext context)
   at DDay.iCal.CalendarObject.DeserializedInternal(StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at DDay.iCal.SerializationUtil.OnDeserialized(Object obj)
   at DDay.iCal.iCalParser.component(ISerializationContext ctx, ISerializerFactory sf, ICalendarComponentFactory cf, ICalendarObject o)
   at DDay.iCal.iCalParser.icalbody(ISerializationContext ctx, IICalendar iCal)
   at DDay.iCal.iCalParser.icalendar(ISerializationContext ctx)
   at DDay.iCal.Serialization.iCalendar.iCalendarSerializer.Deserialize(TextReader tr)
   at CalDavSynchronizer.Implementation.CalDavRepository.DeserializeCalendar(String iCalData, IStringSerializer calendarSerializer)
   at CalDavSynchronizer.Implementation.CalDavRepository.TryDeserializeCalendar(String iCalData, IICalendar& calendar, Uri uriOfCalendarForLogging, IStringSerializer calendarSerializer)
 INFO  2015-09-22 11:30:22,260 [ VSTA_Main] hronizer.Implementation.CalDavRepository . MoveNext                       - Duration of 'CalDavRepository.Get (1 entitie(s))': 00:00:00.5456409
 INFO  2015-09-22 11:30:22,260 [ VSTA_Main] nSync.Synchronization.States.CreateInA`6 . FetchRequiredEntities          - Could not fetch entity '/remote.php/caldav/calendars/631B1CCB-5B96-4278-9BA8-D27A9B389DD5/chuckdas2/a6670fc9-957c-40ef-85a7-287d4de551f0.ics'. Discarding operation.
 INFO  2015-09-22 11:30:22,260 [ VSTA_Main] ronizer.Scheduling.SynchronizationWorker . MoveNext                       - Duration of 'Running synchronization profile 'DAS Cloud2'': 00:00:01.2064862

**Comment by aluxnimm** [comment]
Very strange timezone definition.
Try using CalDAV-sync or DAVDroid. They work very well.

**Comment by captainwasabi** [comment]
OK, passed that info on to my user, also asked him to make sure the timezone data is set to the same on every device (although I think they should really all autodetect the timezone).  

Thanks,  will post results

**Comment by captainwasabi** [comment]
User purchased CalDAV-sync.  Issue solved.

Thanks!
