### ISSUE TITLE
Issue with recurring events

### ISSUE THREAD

**Issue by captainwasabi** [aluxnimm/outlookcaldavsynchronizer#62]
User reports that if he adds a recurring event it crashes the plugin.  Log below. (I have asked for additional information regarding where the event was created (outlook, owncloud,or android)

 INFO  2015-09-22 13:50:49,286 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . MoveNext                       - Synchronization manually triggered
 INFO  2015-09-22 13:50:49,302 [ VSTA_Main] ronizer.Scheduling.SynchronizationWorker . MoveNext                       - Starting 'Running synchronization profile 'Chuck DAS Cloud''
 INFO  2015-09-22 13:50:49,302 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`6' with Atype='AppointmentItemWrapper' and Btype='IICalendar'
 INFO  2015-09-22 13:50:49,317 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Starting 'CalDavRepository.GetVersions'
 INFO  2015-09-22 13:50:49,317 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Duration of 'CalDavRepository.GetVersions': 00:00:00.0001818
 ERROR 2015-09-22 13:50:50,052 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - 
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<GetEntities>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.Synchronization.Synchronizer`6.<Synchronize>d__14.MoveNext()
 INFO  2015-09-22 13:50:50,084 [ VSTA_Main] ronizer.Scheduling.SynchronizationWorker . MoveNext                       - Duration of 'Running synchronization profile 'Chuck DAS Cloud'': 00:00:00.7759855
 INFO  2015-09-22 13:50:53,698 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . MoveNext                       - Synchronization manually triggered
 INFO  2015-09-22 13:50:53,698 [ VSTA_Main] ronizer.Scheduling.SynchronizationWorker . MoveNext                       - Starting 'Running synchronization profile 'Chuck DAS Cloud''
 INFO  2015-09-22 13:50:53,714 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`6' with Atype='AppointmentItemWrapper' and Btype='IICalendar'
 INFO  2015-09-22 13:50:53,714 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Starting 'CalDavRepository.GetVersions'
 INFO  2015-09-22 13:50:53,730 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Duration of 'CalDavRepository.GetVersions': 00:00:00.0001458
 ERROR 2015-09-22 13:50:54,376 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - 
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<GetEntities>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.Synchronization.Synchronizer`6.<Synchronize>d__14.MoveNext()
 INFO  2015-09-22 13:50:54,407 [ VSTA_Main] ronizer.Scheduling.SynchronizationWorker . MoveNext                       - Duration of 'Running synchronization profile 'Chuck DAS Cloud'': 00:00:00.6946256

**Comment by captainwasabi** [comment]
additional info from the user:  recurring event was created in outlook.  Failed synchronizing to owncloud.  event was deleted in outlook but the synchronizations continue to fail.

**Comment by aluxnimm** [comment]
Owncloud returns 500 Internal Server Error, so you have to check the owncloud server logs to see what caused the error.

**Comment by nertsch** [comment]
You can also Download http://sourceforge.net/projects/outlookcaldavsynchronizer/files/1.2.1.Logging/CalDavSynchronizer.zip/download , which will write the server response in the logfile.

**Comment by captainwasabi** [comment]
Fatal	caldav	
Exception: {"Message":"INTERVAL in RRULE must be a positive integer!","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Recur\/RRuleIterator.php(36): Sabre\\VObject\\Recur\\RRuleIterator->parseRRule(Array)\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Recur\/EventIterator.php(186): Sabre\\VObject\\Recur\\RRuleIterator->__construct(Array, Object(DateTime))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Component\/VEvent.php(33): Sabre\\VObject\\Recur\\EventIterator->__construct(Object(Sabre\\VObject\\Component\\VEvent))\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(291): Sabre\\VObject\\Component\\VEvent->isInTimeRange(Object(DateTime), Object(DateTime))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(79): Sabre\\CalDAV\\CalendarQueryValidator->validateTimeRange(Object(Sabre\\VObject\\Component\\VEvent), Object(DateTime), Object(DateTime))\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(41): Sabre\\CalDAV\\CalendarQueryValidator->validateCompFilters(Object(Sabre\\VObject\\Component\\VCalendar), Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(145): Sabre\\CalDAV\\CalendarQueryValidator->validate(Object(Sabre\\VObject\\Component\\VCalendar), Array)\n#7 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(115): Sabre\\CalDAV\\Backend\\AbstractBackend->validateFilterForObject(Array, Array)\n#8 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Calendar.php(427): Sabre\\CalDAV\\Backend\\AbstractBackend->calendarQuery('8', Array)\n#9 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(635): Sabre\\CalDAV\\Calendar->calendarQuery(Array)\n#10 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(232): Sabre\\CalDAV\\Plugin->calendarQueryReport(Object(DOMDocument))\n#11 [internal function]: Sabre\\CalDAV\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\/631B1...')\n#12 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#13 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(705): Sabre\\Event\\EventEmitter->emit('report', Array)\n#14 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#15 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#16 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#17 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#18 \/var\/www\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#19 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#20 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Recur\/RRuleIterator.php","Line":662}	2015-09-22T21:25:21+

**Comment by nertsch** [comment]
The logfile says, that this error happens, when CalDavSynchronizer tries to fetch the events from CalDAV. Synchronization didn't even start.

That seems to be a Bug in SabreDav.
See: https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/58  

br
Gerhard

**Comment by aluxnimm** [comment]
Maybe caused from an event in Owncloud with INTERVAL=0, a every workday recurrence wrongly synced from Outlook, see https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/99

Fixed from our side in latest commit, will be in next release.
