### ISSUE TITLE
Outllook Error

### ISSUE THREAD

**Issue by NameVergessen** [aluxnimm/outlookcaldavsynchronizer#63]
Version 1.2.0 and Version 1.2.1

When i install the programm and start outlook this happens.
It also happens wenn I just start the .vsto.

Name: 
Von: file:///C:/Program Files (x86)/Gerhard Zehetbauer/CalDavSynchronizer/CalDavSynchronizer.vsto

************** Ausnahmetext **************
System.Deployment.Application.InvalidDeploymentException: Ausnahme beim Lesen des Manifests aus 'file:///C:/Program%20Files%20(x86)/Gerhard%20Zehetbauer/CalDavSynchronizer/CalDavSynchronizer.vsto': Das Manifest ist möglicherweise ungültig, oder die Datei konnte nicht geöffnet werden. ---> System.Deployment.Application.InvalidDeploymentException: Die XML-Signatur des Manifests ist ungültig. ---> System.Security.Cryptography.CryptographicException: SignatureDescription konnte für den angegebenen Signaturalgorithmus nicht erstellt werden.
   bei System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
   bei System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
   bei System.Deployment.Internal.CodeSigning.SignedCmiManifest.Verify(CmiManifestVerifyFlags verifyFlags)
   bei System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
   bei System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

**Comment by aluxnimm** [comment]
Did you run setup.exe and install all dependencies?

**Comment by NameVergessen** [comment]
Sure did. Multiple times. I also found the file in question in my default install folder.

 

Von: Alex Nimmervoll [mailto:notifications@github.com] 
Gesendet: Mittwoch, 23. September 2015 23:13
An: aluxnimm/outlookcaldavsynchronizer
Cc: NameVergessen
Betreff: Re: [outlookcaldavsynchronizer] Outllook Error (#63)

 

Did you run setup.exe and install all dependencies?

**Comment by aluxnimm** [comment]
missing vsto tools for office runtime could cause this. can be installed manually,  see readme.
