### ISSUE TITLE
davical + outlook sync issue

### ISSUE THREAD

**Issue by alexseymer** [aluxnimm/outlookcaldavsynchronizer#64]
Hi,

first of all - thank you for the excellent app!

Concerning my problem: I run a davical server and syncronize my mobile (Android + Davdroid) and my pc (Win 10 + Outlook 2013). The sync with my davical server works without problems with the Mozilla Lightning addon for Thunderbird and across devices (android tablet). When I make changes in Outlook and sync them, the changes are pushed to davical and later to my mobile. When I add something in my mobile the changes are pushed to davical (other devices receive the update), but Outlook is not receiving the update. And now it becomes really weird. A newly  added appointment in Thunderbird Lightning is pushed to the mobile and Outlook. Long story short: The two-way sync seems to be more a one-way one. I can provide you with the logfiles if needed.

If you don't have access to a davical setup, I can provide you with a temporary account for my server in order to assess the issue.

Thanks for your help!

**Comment by aluxnimm** [comment]
yes please send me your logs and a davical test account. we didn't test against davical so far.

**Comment by alexseymer** [comment]
ok, I will send you the details by email.

Am 06.10.2015 um 16:34 schrieb Alex Nimmervoll:
