### ISSUE TITLE
Incorrect time of day synced to Cozy Cloud CalDAV server

### ISSUE THREAD

**Issue by drschwabe** [aluxnimm/outlookcaldavsynchronizer#66]
Hi there, 

Events entered via Outlook / OutlookCaldavsyncrhonizer plugin are syncing to our CalDAV server with incorrect time of day.   By 6 hours.  

If we punch in events on iPhone the dates/times are always correct, so the CalDAV server seems to not necessarily be the problem. 

Affecting Outlook 2010 and 2013 from our testing. 

I have also cross-posted the issue on the CalDAV server's repo (Cozy Cloud) on the chance that it may be a problem on their side. 

https://github.com/cozy/cozy-calendar/issues/425

**Comment by aluxnimm** [comment]
can you provide an ics file of such an event?
aby errors in the log file if the plugin ?

**Comment by aluxnimm** [comment]
no feedback, closing.

**Comment by Dinduks** [comment]
Hi,

I use Cozy Cloud too and this happened to me as well (and made me miss an important appointment :cry:).

Here is the ICS file in question: https://gist.github.com/Dinduks/068998b356422a79127593371fef03d9 - I only changed sensitive information (description, email addresses, etc.). 
The time displayed in my calendar was 1pm to 2pm, but it should have been 11am to 12am.

Please let me know if I can be of any help.

Thank you!

**Comment by ingoratsdorf** [comment]
TZID:Romance Standard Time????
No surprise that most caldav servers would not handle this. This is Outlook typical non-standard (Olsen) timezone and will need to be converted either by client or server. Typically by the server.

This (Romance Standard Time) appears to be a microsoft 'invention'
http://www.quora.com/Where-did-Romance-Standard-Time-come-from-and-why-Romance
http://www.reddit.com/r/RedditDayOf/comments/18ib1d/romance_standard_time_for_central_european_time/

Most servers use the more commonly accepted Olsen Timezone DB. (IANA, PHP etc. Wikipedia calls it "the Tz database" http://en.wikipedia.org/wiki/Tz_database

**Comment by aluxnimm** [comment]
but it has a correct vtimezone definition included. so the server should handle it. we also you the outlook/windows tzids for compatibility and all other server can handle it so far.  but you can try the event mapping configuration " Create events on server in UTC"

**Comment by ingoratsdorf** [comment]
Re 'correect" VTIMEZONE: DTSTART:16010101T030000
CET does not start/end on 1 Jan. And has changed quite a few times from 1601.... ;-)

Anyway, as we can see in the cross bug report, the CozyCloud server stumbles on that timezone definition, so does not even parse it properly.

So yes, the timezone mapping may be your best bet.

**Comment by aluxnimm** [comment]
Implemented mapping to IANA/Olson timezones with configuration options and use VTIMEZONE definitions from tzurl.org.
Will be in next release and should fix those issues with Cozy and other servers which don't accept non standard timezones.

**Comment by Dinduks** [comment]
Thank you very much!

**Comment by jsilvestre** [comment]
(I'm working at Cozy Cloud)
Thank you! I know we are faulty for not supporting the VTIMEZONE component, we will improve our ical support, but this change helps us (our users) a lot in the short term!

**Comment by aluxnimm** [comment]
If Cozy works properly now with Olson timezones, we just need to inform your users that this options are necessary to avoid timeshifts, since it is not the default setting. Do you provide a hosted service with a fixed discovery url also? Then we could add an account type Cozy with that option set already, similar to GMX for example.

**Comment by jsilvestre** [comment]
Cozy works well with Olson timezones, so it's going to work decently, thank you again!

We don't have a centralized discovery service because Cozy are decentralized instances so they can be hosted anywhere, and the point is not to track them (if I understand you correctly, but I am not sure).

**Comment by aluxnimm** [comment]
Ok maybe only a provided example url then?
Is the path always like
https://your.domain.me/public/sync/principals/me/

**Comment by jsilvestre** [comment]
Ah, right sorry. Yes it's always this path!

**Comment by aluxnimm** [comment]
Ok can you provide a link to an official logo we should use for the account type?

**Comment by jsilvestre** [comment]
Sure!
Name: Cozy Cloud
Logo: https://cozy.io/en/images/press/cozy-lg.svg
(If you need more, you can check https://cozy.io/en/press/)

Thank you!

**Comment by aluxnimm** [comment]
Thanks, cozy account type with olson timezone settings as default will be in next release.

**Comment by jsilvestre** [comment]
Thank you! I will pass that to the marketing team so they can tweet about it hopefully!

**Comment by aluxnimm** [comment]
included in release 2.5.1.
