### ISSUE TITLE
Version 1.3.4 + Outlook 2007, can't open options/about page

### ISSUE THREAD

**Issue by PierreMarieBaty** [aluxnimm/outlookcaldavsynchronizer#69]
Hello there,

Not sure what you did with the latest version after the merge, but I can no longer open the options and about page. To be more precise, I can do it only once, after what clicking the button yields nothing.

I don't have time to look into that precisely but I wasn't having this problem with my fork. Could you look into that ? Thanks

**Comment by aluxnimm** [comment]
was not my commit.
we will check it shouldn't be a big deal.



-------- Ursprüngliche Nachricht --------
Von: PierreMarieBaty <notifications@github.com> 
Datum: 2015.10.12  16:35  (GMT+01:00) 
An: aluxnimm/outlookcaldavsynchronizer <outlookcaldavsynchronizer@noreply.github.com> 
Betreff: [outlookcaldavsynchronizer] Version 1.3.4 + Outlook 2007, can't open
  options/about page (#69) 

Hello there,

Not sure what you did with the latest version after the merge, but I can no longer open the options and about page. To be more precise, I can do it only once, after what clicking the button yields nothing.

I don't have time to look into that precisely but I wasn't having this problem with my fork. Could you look into that ? Thanks

**Comment by aluxnimm** [comment]
Should be working with latest commit, please check it.

**Comment by PierreMarieBaty** [comment]
Indeed it is :) I remember I ran into the same issue. It is important that the buttons not be disposed when the function returns, hence why they need to be stored in non-local storage.
