### ISSUE TITLE
CalDAV timeout 

### ISSUE THREAD

**Issue by peterbeck** [aluxnimm/outlookcaldavsynchronizer#70]
I've got an error synchronizing a calendar to Outlook 2013 (testing the settings is ok, no error, using the most current release 1.4.0)

```
 INFO  2015-10-17 14:18:00,452 [ VSTA_Main] ronizer.Scheduling.SynchronizationWorker . MoveNext                       - Duration of 'Running synchronization profile 'Kalender'': 00:00:05.5448331
 INFO  2015-10-17 14:18:56,800 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . MoveNext                       - Synchronization manually triggered
 INFO  2015-10-17 14:18:56,800 [ VSTA_Main] ronizer.Scheduling.SynchronizationWorker . MoveNext                       - Starting 'Running synchronization profile 'Kalender''
 INFO  2015-10-17 14:18:56,800 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`6' with Atype='AppointmentItemWrapper' and Btype='IICalendar'
 INFO  2015-10-17 14:18:56,815 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Starting 'CalDavRepository.GetVersions'
 INFO  2015-10-17 14:18:56,815 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Duration of 'CalDavRepository.GetVersions': 00:00:00.0003482
 ERROR 2015-10-17 14:18:56,831 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - 
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Die zugrunde liegende Verbindung wurde geschlossen: Eine Verbindung, deren Aufrechterhaltung erwartet wurde, ist vom Server geschlossen worden..
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
```
CardDAV is synchronizing without issues, Backend is SOGo 2.3.2 running on Debian Jessie with Apache. Am I doing something wrong or do I need to set some KeepAlive option in Apache to avoid that issue ?
I've already removed the profile and added a new one, default settings, calendar is recognized correctly with Autodiscovery. 
Adding new entries to the calender is synchronized to the server without any issues, also changes in these newly added events are synchronized correctly (adding categories, set to private etc), but somehow the existing entries do not show up in Outlook. I did also check the Outlook view (reset to defaults). All the existing (not synchronized) entries are (as far as I have seen) reoccurring events, if that matters. Standard events (non reoccurring) seem to be synchronized....

**Comment by aluxnimm** [comment]
What are your apache settings regarding KeepAlive?

**Comment by peterbeck** [comment]
Hi aluxnimm,
there are no KeepAlive settings set at the moment. Do you recommend anything ? (I've also asked the same question to the SOGo-lists, maybe it would be better to set that anyway).

But somehow there was also a mysql-table crashed and after repairing the table, I could not see this issue anymore. Maybe I was making noise but there was another problem....I'll check that during monday, otherwise I'll close that issue.
Thanks and regards
Peter

**Comment by nertsch** [comment]
Hi,

CalDAV Synchronizer requires a Server, which supports KeepAlive. Otherwise synchronization will fail. Currently there is no Setting to turn KeepAlive off.

br
Gerhard
