### ISSUE TITLE
Chat-Mapping set to mail

### ISSUE THREAD

**Issue by peterbeck** [aluxnimm/outlookcaldavsynchronizer#71]
Hi there,

In Outlook 2010 the "Chat" field seems to be mapped to one of the mail-addresses, even if the user does not have any instant messaging accounts. Using version 1.4.1

Regards Peter

**Comment by aluxnimm** [comment]
Con you provide an example of a wrong mapped vcf file?

**Comment by peterbeck** [comment]
sure, here 's the sogo-vcard:
```
BEGIN:VCARD
VERSION:3.0
N:Last;First
FN:Last\, First
EMAIL;TYPE=INTERNET:first.last@domain.com
ORG:Somename Aktiengesellschaft
UID:13EF-56106200-1-5EF05780
END:VCARD
```
and the Outlook 2013 vcard looks:
![ol2013scr](https://cloud.githubusercontent.com/assets/561186/10710554/ccf4a190-7a5f-11e5-9d05-da08e6370652.png)

```
BEGIN:VCARD
VERSION:2.1
N;LANGUAGE=de-li:Last;First
FN:First Last
ORG:Somename Aktiengesellschaft
X-MS-OL-DEFAULT-POSTAL-ADDRESS:0
EMAIL;PREF;INTERNET:first.last@domain.com
X-MS-OL-DESIGN;CHARSET=utf-8:<card xmlns="http://schemas.microsoft.com/office/outlook/12/electronicbusinesscards" ver="1.0" layout="left" bgcolor="ffffff"><img xmlns="" align="fit" area="16" use="cardpicture"/><fld xmlns="" prop="name" align="left" dir="ltr" style="b" color="000000" size="10"/><fld xmlns="" prop="org" align="left" dir="ltr" color="000000" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="email" align="left" dir="ltr" color="d48d2a" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/></card>
REV:20151024T125303Z
END:VCARD
```

**Comment by peterbeck** [comment]
btw: using version 1.4.2 now...

**Comment by aluxnimm** [comment]
Can't reproduce. When I import your example to SOGo and then sync to Outlook, only the email field get's populated, very strange.

**Comment by peterbeck** [comment]
Hi there,
I've just replaced the active directory domain with a a complete fresh installation on the affected system and now everything is working the way it should. 
It was a very old system with Exchange 2003 and Zarafa schema extensions installed, i think that was the issue. Anyway, now everything is shiny ;-)
Cheers
Peter
