### ISSUE TITLE
TimeZone Mismatch

### ISSUE THREAD

**Issue by Abolfazl** [aluxnimm/outlookcaldavsynchronizer#74]
I am trying to sync Outlook with Google Calendar using CalDav but for some reason all my events are appearing 1 hour later. I have the latest version (1.4.3.0), Outlook 2010. How might I fix this?

**Comment by jhotmann** [comment]
Experiencing the same issue with Outlook 2013.

**Comment by aluxnimm** [comment]
what timezone? a fix for Google will be in next release.

**Comment by Abolfazl** [comment]
Both Outlook and Gmail are on Pacific TimeZone. Could it be because the TimeZone is currently set to GMT-7 but typically the timezone is GMT-8 due to DST?

**Comment by aluxnimm** [comment]
Please try 1.4.4

**Comment by Abolfazl** [comment]
Works! Thank you @aluxnimm
