### ISSUE TITLE
problems with https - self signed certificate

### ISSUE THREAD

**Issue by maxy01** [aluxnimm/outlookcaldavsynchronizer#76]
Self signed certificates are not acceptet? Is there a workaround?
I ve got this error:

"An error accurred while sending the request.
Die zugrunde liegende Verbindung wurde geschlossen: Für den geschützten SSL/TLS-Kanal konnte keine Vertrauensstellung hergestellt werden..
Das Remotezertifikate ist laut Validierungsverfahren ungültig."

Outlook in MS-Office 2010 under Windows 10 with owncloud. The same adress works fine in thunderbird lightning, but have to use Windows and Outlook...

Thanks for your support!

max

**Comment by aluxnimm** [comment]
please read instructions in the readme file.  either import your certificate in the trusted machine store or disable certificate validation in the app.config
