### ISSUE TITLE
Outlook 2016

### ISSUE THREAD

**Issue by vascowhite** [aluxnimm/outlookcaldavsynchronizer#77]
This is a great plugin, well done!

I just wanted to let you know that this plugin is working fine with Outlook 2016 <--> Owncloud 8.13. Outlook is running in Windows 7 Pro 64 bit.

Feel free to close this as soon as you've read it :)

**Comment by aluxnimm** [comment]
Thanks for the information.  Had no opportunity to test OL2016 yet so good news :)
