### ISSUE TITLE
Failing with "403"

### ISSUE THREAD

**Issue by dinesh-advytha** [aluxnimm/outlookcaldavsynchronizer#78]
I am unable to connect to beehive, its failing with "403". Any help will be appreciated.

**Comment by aluxnimm** [comment]
We have no experience with beehive. What url and username do you use? what errors are in the log file? Test settings fails with 403?

**Comment by stefanspe** [comment]
I have the same error while trying to connect to tine20. I tested caldav. Appointments from the tine server are shown in Outlook, but new appointments in Outlook caused the error.
[log.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/98074/log.txt)

**Comment by aluxnimm** [comment]
The log states the error:
System.Net.Http.HttpRequestException: Response status code does not indicate success: '403' ('Forbidden'). Message:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message>write access denied for unknown client</s:message>
  <s:sabredav-version>1.8.10</s:sabredav-version>
</d:error>

"write access denied for unknown client" means that the server only allows write operations from clients which are known from some kind of whitelist or whatever Tine uses, You have to ask in the Tine forum how to enable a new client.

**Comment by aluxnimm** [comment]
see
https://forge.tine20.org/view.php?id=11588
