### ISSUE TITLE
Sync does not work. Throws exception that there is error Xml Document

### ISSUE THREAD

**Issue by TfDds** [aluxnimm/outlookcaldavsynchronizer#80]
Hi all,

I have a problem with running the syncwith outlook 2007 and our CalDav Server.
I switched the outlook folder in the outlook settings from the subfolder "Kalender/CalDav" to "Kalender" directly. Can that cause the problems?
I have already done a new installation of the plugin.

I get the following log messages at every sync attempt:

    INFO  2015-11-11 08:45:43,106 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . MoveNext                       - Synchronization manually triggered
    INFO  2015-11-11 08:45:43,109 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Starting 'Running synchronization profile 'CalDav DDS''
    INFO  2015-11-11 08:45:43,114 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`6' with Atype='AppointmentItemWrapper' and Btype='IICalendar'
    ERROR 2015-11-11 08:45:43,121 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - 
    System.InvalidOperationException: Fehler im XML-Dokument (0,0). ---> System.Xml.XmlException: Das Stammelement ist nicht vorhanden.
       bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
       bei System.Xml.XmlTextReaderImpl.ParseDocumentContent()
       bei System.Xml.XmlTextReaderImpl.Read()
       bei System.Xml.XmlTextReader.Read()
       bei System.Xml.XmlReader.MoveToContent()
       bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read3_Item()
       --- Ende der internen Ausnahmestapelüberwachung ---
       bei System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
       bei System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
       bei GenSync.EntityRelationManagement.EntityRelationDataAccess`5.LoadEntityRelationData()
       bei GenSync.Synchronization.Synchronizer`6.<Synchronize>d__0.MoveNext()
     INFO  2015-11-11 08:45:43,144 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Running synchronization profile 'CalDav DDS'': 00:00:00.0299441
     INFO  2015-11-11 08:50:44,659 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Starting 'Running synchronization profile 'CalDav DDS''
     INFO  2015-11-11 08:50:44,663 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`6' with Atype='AppointmentItemWrapper' and Btype='IICalendar'
     ERROR 2015-11-11 08:50:44,669 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - 
    System.InvalidOperationException: Fehler im XML-Dokument (0,0). ---> System.Xml.XmlException: Das Stammelement ist nicht vorhanden.
       bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
       bei System.Xml.XmlTextReaderImpl.ParseDocumentContent()
       bei System.Xml.XmlTextReaderImpl.Read()
       bei System.Xml.XmlTextReader.Read()
       bei System.Xml.XmlReader.MoveToContent()
       bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read3_Item()
       --- Ende der internen Ausnahmestapelüberwachung ---
       bei System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
       bei System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
       bei GenSync.EntityRelationManagement.EntityRelationDataAccess`5.LoadEntityRelationData()
       bei GenSync.Synchronization.Synchronizer`6.<Synchronize>d__0.MoveNext()
     INFO  2015-11-11 08:50:44,678 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Running synchronization profile 'CalDav DDS'': 00:00:00.0145332
     INFO  2015-11-11 08:55:15,774 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . .ctor                          - Startup...
     INFO  2015-11-11 08:55:16,175 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . .ctor                          - Startup finnished
     INFO  2015-11-11 08:55:45,931 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Starting 'Running synchronization profile 'CalDav DDS''
     INFO  2015-11-11 08:55:45,954 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`6' with Atype='AppointmentItemWrapper' and Btype='IICalendar'
     ERROR 2015-11-11 08:55:46,012 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - 
    System.InvalidOperationException: Fehler im XML-Dokument (0,0). ---> System.Xml.XmlException: Das Stammelement ist nicht vorhanden.
       bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
       bei System.Xml.XmlTextReaderImpl.ParseDocumentContent()
       bei System.Xml.XmlTextReaderImpl.Read()
       bei System.Xml.XmlTextReader.Read()
       bei System.Xml.XmlReader.MoveToContent()
       bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read3_Item()
       --- Ende der internen Ausnahmestapelüberwachung ---
       bei System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
       bei System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
       bei GenSync.EntityRelationManagement.EntityRelationDataAccess`5.LoadEntityRelationData()
       bei GenSync.Synchronization.Synchronizer`6.<Synchronize>d__0.MoveNext()
     INFO  2015-11-11 08:55:46,075 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Running synchronization profile 'CalDav DDS'': 00:00:00.1343699
     INFO  2015-11-11 09:00:46,216 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Starting 'Running synchronization profile 'CalDav DDS''
     INFO  2015-11-11 09:00:46,226 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`6' with Atype='AppointmentItemWrapper' and Btype='IICalendar'
     ERROR 2015-11-11 09:00:46,238 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - 
    System.InvalidOperationException: Fehler im XML-Dokument (0,0). ---> System.Xml.XmlException: Das Stammelement ist nicht vorhanden.
       bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
       bei System.Xml.XmlTextReaderImpl.ParseDocumentContent()
       bei System.Xml.XmlTextReaderImpl.Read()
       bei System.Xml.XmlTextReader.Read()
       bei System.Xml.XmlReader.MoveToContent()
       bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read3_Item()
       --- Ende der internen Ausnahmestapelüberwachung ---
       bei System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
       bei System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
       bei GenSync.EntityRelationManagement.EntityRelationDataAccess`5.LoadEntityRelationData()
       bei GenSync.Synchronization.Synchronizer`6.<Synchronize>d__0.MoveNext()
     INFO  2015-11-11 09:00:46,254 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Running synchronization profile 'CalDav DDS'': 00:00:00.0287515

Thanks for your help in advance.

**Comment by aluxnimm** [comment]
Try to delete all state data in 
C:\Users\<Your Username>\AppData\Local\CalDavSychronizer
and reconfigure the plugin.

**Comment by TfDds** [comment]
Ah, thanks. That did the trick. It seems something went wrong before.
