### ISSUE TITLE
Outlook 2016 TimeoutException

### ISSUE THREAD

**Issue by vascowhite** [aluxnimm/outlookcaldavsynchronizer#81]
Your synchroniser has been running flawlessly since I started using it. I upgraded to version 1.5.3 on the 14th November 2015 and it continued to work fine until this morning (17th November 2015) when I received the following errror

![caldavsyncerror](https://cloud.githubusercontent.com/assets/874109/11205591/2c0f2838-8d09-11e5-9256-e2469eaa7eef.png)

Clicking the `Details` button gives the following text:-

>Name: 
>From: file:///C:/Program Files (x86)/Gerhard >Zehetbauer/CalDavSynchronizer/CalDavSynchronizer.vsto

>************** Exception Text **************
>System.TimeoutException: The deployment manifest could not be downloaded because a connection >to the network could not be established. Ensure that you can connect to the network, and try again.
>   at >Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
>   at >Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

This prevents Outlook from loading any further plugins and prevents it from starting up.

I do have a network connection. Any suggestions?

**Comment by aluxnimm** [comment]
No firewall or proxy issues on the network? Maybe try to manually uninstall and reinstall the plugin.

**Comment by vascowhite** [comment]
No, there are no firewall/proxy issues and I have uninstalled/re-installed several times this morning.
As I say, it worked fine since Saturday and suddenly failed today.
I'm not sure what network it is referring to. Is this .net trying to contact our Exchange server?

**Comment by vascowhite** [comment]
I tried it with my AV switched off and still the same problem.
I am using Outlook 2016 on Windows 7 Pr0 64 bit.

**Comment by aluxnimm** [comment]
So the question is, what changed suddenly since our plugin is the same obviously. Any Windows Updates regarding .net or vsto runtime or Office?

**Comment by vascowhite** [comment]
Exactly.

The last update logged is 12th November which pre-dates the installation of 1.5.3. Nothing on our network has changed, which makes this quite a mystery.

Where will the deployment manifest referenced in the error message be stored? Is that part of your plugin?

**Comment by aluxnimm** [comment]
You can try to clear the ClickOnce Cache

http://stackoverflow.com/questions/2418542/clear-the-net-downloaded-application-cache-without-mage

rundll32 dfshim CleanOnlineAppCache

**Comment by vascowhite** [comment]
That seems to have sorted it. I did the following:-

 - Un-install caldavsynchronizer
 - Run rundll32 dfshim CleanOnlineAppCache
 - reboot
 - re-install caldavsynchronizer

Thanks for the help, I probably wouldn't have found that SO question as I wouldn't have made the connection between that and my issue.

**Comment by aluxnimm** [comment]
Good news, at least we have a solution for such problems now!
