### ISSUE TITLE
problem with carddav

### ISSUE THREAD

**Issue by Mr-HeBo** [aluxnimm/outlookcaldavsynchronizer#82]
Hello, 

at first: the calendar and tasks syncing works fine :+1: !

I added a new profile to synchronize my owncloud address book.. 
> ![settings](https://cloud.githubusercontent.com/assets/11228598/11268600/e659b59c-8eb1-11e5-9432-a38fbbb14ad8.png)

When I try the settings, I get the message:
> ![message](https://cloud.githubusercontent.com/assets/11228598/11268595/e0a186b6-8eb1-11e5-9956-81c5f3ebf443.png)

The address book syncing works without problems with my mobile devices.
What or where is the cause?

my facts:
* Outlook 2010
* CalDavSynchronizer 1.5.4.0
* [Owncloud] (https://owncloud.org) 8.1.4 with [Contacts Plus] (https://apps.owncloud.com/content/show.php/Contacts+Plus?content=171237)

Thanks and regards
Heiko

**Comment by aluxnimm** [comment]
What is the complete url to the adressbook? e.g.
https://myserver/remote.php/carddav/addressbooks/user/adressbookname/

Try this url instead maybe. 
The normal contact app for owncloud works, but I don't have the ContactPlus app to test right now.

Is there any strange character in the adressbook name, somehow the xml response from your server contains a » character which causes trouble.

**Comment by Mr-HeBo** [comment]
Hello, 

thanks for your support. The URL was the cause :(. 
You have to use this URL (for Contacts Plus): 

https://myserver/remote.php/contactsplus/addressbooks/username/contacts/ 

The last "/" is importent.

Regards
Heiko

**Comment by Mr-HeBo** [comment]
no problem. I'll create you an test account and send all information via http://sourceforge.net messaging. 
Is it ok for you?.

**Comment by aluxnimm** [comment]
perfect. thx.

**Comment by aluxnimm** [comment]
Fixed in latest commit, now https://myserver/remote.php/contactsplus/ works aswell and discovers the full url
