### ISSUE TITLE
Support for images when using CardDAV

### ISSUE THREAD

**Issue by thomaswoeckinger** [aluxnimm/outlookcaldavsynchronizer#83]
Currently VCard's with images causing an error during synchronization.

So it would be great if images would not result in an error, and all other informations are transferred.
In general the support of images would be great!

Anyway thx for your great work!

**Comment by aluxnimm** [comment]
What server? Images work for sogo,horde,owncloud etc. Please provide the log with the error and an vcf file from the server with the image that doesn't work.

**Comment by thomaswoeckinger** [comment]
Zarafa Sabre DAV

**Comment by aluxnimm** [comment]
Never tested with Zarafa, we don't have a test account atm. Log and vcf file should help to find the issues.

**Comment by thomaswoeckinger** [comment]
[log.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/50170/log.txt)

Isolated log when trying to transfer one Vcard entry with an image.

**Comment by aluxnimm** [comment]
So you have problems syncing vcards with images from the server to Outlook? that vcard in your server debug log is not base64 encoded.

**Comment by thomaswoeckinger** [comment]
I tracked it down to an bug in sabre-zarafa wich allows to send vcard 4.0 but the used sabredav version 2.1.7 does not support it fully, so i changed the configuration to 3.0 and all is working now.

Thx for your time
