### ISSUE TITLE
Outlook 2016/Win 10 - Sudden Runtime error on Load

### ISSUE THREAD

**Issue by dasilvetz** [aluxnimm/outlookcaldavsynchronizer#84]
Hi- thanks again for the great work on this plugin.

I have been using it with no problems for the past few weeks.

Suddenly, as of this morning, it refuses to load. 

Outlook keep disabling it/it shows up in the Inactive section of my Outlook Add-Ins, and when I try to re-enable it manually, I am seeing the following error in Outlook:
Not loaded. A runtime error occurred during the loading of the COM Add-in.

I have tried trashing the options_profile xml file, as well as install /reinstall versions 1.6, 1.7, and 1.8.

Unfortunately I am not sure what else to try!

Any help would be realty appreciated.

**Comment by aluxnimm** [comment]
what com error? anything in the log file? any new windows updates regarding office or .net?

**Comment by dasilvetz** [comment]
Unfortunately I'm not sure what the specific error is, as that is the only info Outlook provides- I also checked and the only updates that Windows has applied are Windows Defender Definition Updates.

I checked AppData>Local>CalDavSynchronizer, and the latest entries appear to be from 12/1 (not sure why the log file hasn't updated since?) 

Here are the very last entries:

 DEBUG 2015-12-01 17:22:35,865 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Exiting.
 INFO  2015-12-01 17:22:35,878 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Running synchronization profile 'Oracle'': 00:00:00.6915996
 INFO  2015-12-01 17:32:35,885 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Starting 'Running synchronization profile 'Oracle''
 INFO  2015-12-01 17:32:35,894 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`6' with Atype='AppointmentItemWrapper' and Btype='IICalendar'
 INFO  2015-12-01 17:32:36,558 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Starting 'CalDavRepository.GetVersions'
 INFO  2015-12-01 17:32:36,567 [ VSTA_Main] hronizer.Implementation.CalDavRepository . GetVersions                    - Duration of 'CalDavRepository.GetVersions': 00:00:00.0005924
 ERROR 2015-12-01 17:32:36,574 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - 
System.IO.FileLoadException: Could not load file or assembly 'CalDavSynchronizer.OAuth.Google, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. There is not enough space on the disk. (Exception from HRESULT: 0x80070070)
File name: 'CalDavSynchronizer.OAuth.Google, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null'
   at CalDavSynchronizer.Scheduling.SynchronizerFactory.<CreateHttpClient>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at CalDavSynchronizer.Scheduling.SynchronizerFactory.CreateHttpClient(String username, String password, TimeSpan calDavConnectTimeout, ServerAdapterType serverAdapterType, ProxyOptions proxyOptions)
   at CalDavSynchronizer.Scheduling.SynchronizerFactory.<>c__DisplayClass2.<CreateWebDavClient>b__0()
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<GetEntities>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.Synchronizer`6.<Synchronize>d__0.MoveNext()

**Comment by aluxnimm** [comment]
There is not enough space on the disk. (Exception from HRESULT: 0x80070070)


enough free space on c:/  ?

**Comment by dasilvetz** [comment]
I actually did run into this issue last week but have since then freed up 10 GB's - (just double-checked).

So that makes sense as to why the log stopped writing then- but doesn't explain why it hasn't logged since? 

Nor why the plugin refuses to load this morning. Is there a different place where event are being logged that I can check? 

Ive included screenshots of what I'm seeing in Outlook.
![capture](https://cloud.githubusercontent.com/assets/16188589/11625956/c5dccc68-9cd6-11e5-9e59-3b4e04bd4075.PNG)
![capture2](https://cloud.githubusercontent.com/assets/16188589/11625955/c5dc7c5e-9cd6-11e5-9eda-f536cfb863a5.PNG)

**Comment by aluxnimm** [comment]
slow startup is possible sometimes. what happens when you check the checkbox and add it manually again?

**Comment by dasilvetz** [comment]
Unfortunately nothing- if I check the box, I get the "runtime error" and if I restart, it still wont load.

I was also able to locate this event in the Event Viewer ID 59:

Outlook disabled the following add-in(s):
ProgID: CalDavSynchronizer.1
GUID: {00000000-0000-0000-0000-000000000000}
Name: CalDavSynchronizer
Description: CalDavSynchronizer
Load Behavior: 2
HKLM: 0
Location: file:///c:\program files (x86)\gerhard zehetbauer\caldavsynchronizer\caldavsynchronizer.vsto|vstolocal
Threshold Time (Milliseconds): 1000
Time Taken (Milliseconds): 1250
Disable Reason: This add-in caused Outlook to start slowly.
Policy Exception (Allow List): 0

**Comment by dasilvetz** [comment]
So it looks as though outlook is disabling due to slow startup, but then when i manually try to enable it, outlook is throwing a runtime error (see screenshots above).

What's bizarre is that I haven't change anything, and the plugin was never disabled in the past few weeks by Outlook. 

I also cannot locate the CalDavSynchronizer log.. i just deleted the one from above (that stopped writing on 12/1), and it doesn't look as though a new one is being created? Am guessing that is because the add-in never actually loads?

**Comment by aluxnimm** [comment]
you can try to delete everything in AppData>Local>CalDavSynchronizer or check if you switched to Appdata->Roaming and delete google oauth token in AppData\Roaming\Google.Apis.Auth  if using google and manually uninstall and install it again?

**Comment by dasilvetz** [comment]
Thanks again for helping out here.

So I deleted the AppData>Local>CalDavSynchronizer folder completely (and checked in Roaming but i don't have the Google.Apis.Auth folder).

Uninstalled CalDavSynchronizer completely, then reinstalled. 

I'm still seeing the same indentical issues in Outlook-

However what is bizarre is that it is not creating a new CalDavSynchronizer folder in AppData>Local> ?

Is this because it doesn't ever launch, and therefore it doesn't actually create the necessary files?

**Comment by dasilvetz** [comment]
Any other thoughts of what I can try here? Any other location the log files are being written perhaps (since the folder is not being created) ?
Thanks!

**Comment by aluxnimm** [comment]
do you have write access to that directory? somehow the plugin can't load and write the log file. is is still shown in the com Addins as disabled? there is a checkbox  to always enable slow addins at startup.

**Comment by extremeshok** [comment]
Just a thought, install the plungin as administrator and run outlook at administrator.

Also make sure your outlook, Windows is updated.

Disable your firewalls and antivirus.

**Comment by dasilvetz** [comment]
@extremeshok that did the trick-

I installed the plugin as admin and ran outlook as admin.

@aluxnimm what's bizarre is that this was all working fine (sans the admin part) for the last few weeks, and then suddenly stopped.

Anyways thanks both for your help.

**Comment by aluxnimm** [comment]
strange but glad it works now.
