### ISSUE TITLE
Error during contact sync with Baikal

### ISSUE THREAD

**Issue by sadmin91** [aluxnimm/outlookcaldavsynchronizer#85]
Hello,

We try to set up our connector to sync my contacts between Outlook 2013 and a Baikal server.
The profile has been successfully created and tested.

But during sync, in the log file, we have the following error:
INFO  2015-12-08 21:03:38,203 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Starting 'Running synchronization profile 'Contacts''
 INFO  2015-12-08 21:03:38,219 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`6' with Atype='ContactItemWrapper' and Btype='vCard'
 INFO  2015-12-08 21:03:38,219 [ VSTA_Main] mplementation.Contacts.CardDavRepository . MoveNext                       - Starting 'CardDavRepository.GetVersions'
 INFO  2015-12-08 21:03:38,625 [ VSTA_Main] mplementation.Contacts.CardDavRepository . MoveNext                       - Duration of 'CardDavRepository.GetVersions': 00:00:00.4022556
 WARN  2015-12-08 21:03:38,625 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . CreateDictionary               - EntitiyVersion '/baikal/card.php/addressbooks/fam-manchette/fam-manchette/20140114T084711.b63b68225f@109.18.203.69.vcf' was contained multiple times in server response. Ignoring redundant entity
 INFO  2015-12-08 21:03:38,640 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - Did not find entity caches. Performing initial population
 INFO  2015-12-08 21:03:38,734 [ VSTA_Main] mplementation.Contacts.CardDavRepository . MoveNext                       - Starting 'CardDavRepository.Get (61 entitie(s))'
 INFO  2015-12-08 21:03:38,969 [ VSTA_Main] mplementation.Contacts.CardDavRepository . MoveNext                       - Duration of 'CardDavRepository.Get (61 entitie(s))': 00:00:00.2332141
 ERROR 2015-12-08 21:03:39,000 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`6 . MoveNext                       - 
System.Net.Http.HttpRequestException: Response status code does not indicate success: '404' ('NotFound'). Message:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Card not found</s:message>
  <s:sabredav-version>1.8.6</s:sabredav-version>
</d:error>

   à CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<EnsureSuccessStatusCode>d__13.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__a.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CalDavSynchronizer.DataAccess.CardDavDataAccess.<GetEntities>d__23.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CalDavSynchronizer.Implementation.Contacts.CardDavRepository.<Get>d__4.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à GenSync.Synchronization.Synchronizer`6.EntityContainer.<FillIfEmpty>d__41.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à GenSync.Synchronization.Synchronizer`6.<Synchronize>d__4.MoveNext()
 INFO  2015-12-08 21:03:39,062 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Running synchronization profile 'Contacts'': 00:00:00.8552382

Could you help me to resolve this issue?

Regards

**Comment by aluxnimm** [comment]
Can you provide a test account on your baikal server? We have none available at the moment and it is hard to reproduce the problem otherwise.

**Comment by sadmin91** [comment]
Hello,

Yes !
I have created this test user :
    * Login : test-outlookcaldavsynchronizer
    * Password : pass
    * Baikal URL : https://www.labemilie.fr/baikal

Regards

**Comment by aluxnimm** [comment]
Can't access your server, firewall?

**Comment by sadmin91** [comment]
As previously said, I need to configure your IP address on my server side in order to allow this access.
Could you give me this information?

**Comment by aluxnimm** [comment]
Please provide an email adress where I can send you this information.

**Comment by sadmin91** [comment]
Hello,

You can send this information to itmexfvb@trashmail.com.

Thanks

**Comment by aluxnimm** [comment]
I can upload and download hundreds of vcards to your server without any problem. So the problem is your data on the server, you have some invalid vcards or invalid not unique ids, like '/baikal/card.php/addressbooks/fam-manchette/fam-manchette/20140114T084711.b63b68225f@109.18.203.69.vcf'

Please try with an new empty adressbook on the server and clean your data. You can also send me an export of your vcards from the server and I check with those.

**Comment by sadmin91** [comment]
Hello,

I have clean up my data on Baikal Server: on some contacts, we have the HTML convertion of "@" character on URI field.
After replace this convertion with the corresponding character, the sync works.

Thank you very much for your assistance.

Regards
