### ISSUE TITLE
Private appointments only

### ISSUE THREAD

**Issue by jhbmueller** [aluxnimm/outlookcaldavsynchronizer#86]
Hi, would it be possible to sync private appointments only, or even export them as "private appointment" for a caldav calender which can be shared to others?

Thanks, Jan

**Comment by aluxnimm** [comment]
The privacy flag is exported as TRANSP:OPAQUE already to caldav servers. When sharing that calendar it depends on the ACLS settings if the user can see private events or not. Or you can create a category "private" in Outlook and use that as a sync filter in Advanved settings-Mapping Configuration.

**Comment by evert** [comment]
For what it's worth, `TRANSP` is unrelated to privacy. It just influences whether or not an event is 'blocking', or that it fills up time in freebusy. Privacy is controlled  with `CLASS`. [We](http://sabre.io/) don't do anything with `CLASS` but we do correctly implement `TRANSP`.

**Comment by aluxnimm** [comment]
sorry for confusion. copied the wrong part. of course it is CLASS and we map it to PRIVATE

**Comment by jhbmueller** [comment]
No I am confused... The privacy flag is mapped to what? In the owncloud Caldav implementation, I can select an appointment as visible, show as blocked only, and invisible. What I actually want is, that my private appointments from Exchange are shown as blocked only in owncloud to others.

**Comment by aluxnimm** [comment]
Private appointments in Outlook get the CLASS:PRIVATE and Owncloud shows that as "Hide Event"

**Comment by jhbmueller** [comment]
Now I understand, thank you. However, is it possible, that Owncloud shows the appointments as busy only?

**Comment by aluxnimm** [comment]
When created in Owncloud "busy only" is mapped to CLASS:CONFIDENTIAL, this is also mapped correctly to Outlook and preserved when mapping back to Owncloud. The problem is that Outlook doesn't expose it in the UI, you can only choose public or private for appointments.

**Comment by jhbmueller** [comment]
OK, thank you for your help. Maybe it might be an interesting future feature that one can select wether the Exchange private flag is translated to PRIVATE or CONFIDENTIAL.

**Comment by aluxnimm** [comment]
Could be added to mapping configuration in advanced options. Please create a feature request at https://sourceforge.net/p/outlookcaldavsynchronizer/features/

**Comment by aluxnimm** [comment]
For changing the CLASS attribute in owncloud you can also use something like
http://uname.pingveno.net/blog/index.php/post/2015/11/09/Owncloud-%3A-batch-set-calendar-events-to-CONFIDENTIAL
