### ISSUE TITLE
Installation with multiple users

### ISSUE THREAD

**Issue by sadmin91** [aluxnimm/outlookcaldavsynchronizer#87]
Hello,

On my PC, I have successfully installed and configured this plugin for a first user.
On the same machine, when I open Outlook from a second user, the plugin is not present.

Could you help to configure the second Outlook profile in order to have this plugin?
I would not like to install this plugin twice (I would like to share binairies if it's possible).

Regards

**Comment by aluxnimm** [comment]
See https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/123/

It can only be installed per user at the moment, we would need to completely rewrite the installer which is planned but will take some time.

**Comment by sadmin91** [comment]
Thanks for your answer.
I have checked issues on GitHub but not on Sourceforce.
Sorry.

I have successfully installed two times the software on two profiles.
