### ISSUE TITLE
Can not sync a recurrence appointment with Posteo

### ISSUE THREAD

**Issue by dollydl** [aluxnimm/outlookcaldavsynchronizer#88]
If I generate a recurrence appointment in Outlook 2016 (32bit, Win 8.1 64bit) with intervall of "every last Sunday in a month with unlimited validity" I get the following failure. Also after a sync with Posteo the calender entry is displayed every Sunday on Posteo calender and not only on the last Sunday of a month.

<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>Posteo - Kalender</ProfileName>
  <ProfileId>2c824ee0-0bbe-454a-83fb-dac8d967ff24</ProfileId>
  <StartTime>2015-12-28T15:01:08.821084Z</StartTime>
  <InitialEntityMatchingPerformed>false</InitialEntityMatchingPerformed>
  <LoadErrors />
  <EntitySynchronizationReports />
  <ExceptionThatLeadToAbortion>System.Net.Http.HttpRequestException: Response status code does not indicate success: '500' ('InternalServerError'). Message:
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"&gt;
  &lt;s:exception&gt;ErrorException&lt;/s:exception&gt;
  &lt;s:message&gt;Undefined variable: propertyList&lt;/s:message&gt;
  &lt;s:sabredav-version&gt;1.7.1&lt;/s:sabredav-version&gt;
&lt;/d:error&gt;

   bei CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;EnsureSuccessStatusCode&gt;d__14.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequest&gt;d__a.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequestAndReadResponse&gt;d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CalDavSynchronizer.DataAccess.CalDavDataAccess.&lt;GetVersions&gt;d__35.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei GenSync.Synchronization.Synchronizer`6.&lt;SynchronizePartialNoThrow&gt;d__17.MoveNext()</ExceptionThatLeadToAbortion>
  <Duration>00:00:00.4337250</Duration>
</SynchronizationReport>

**Comment by aluxnimm** [comment]
For last sunday in month we generate the following RFC compliant rule:
RRULE:FREQ=MONTHLY;BYDAY=SU;BYSETPOS=-1
It also works with Google,SOGo and GroupOffice for example, so please report the problem to Posteo.

I checked Posteo, it generates
RRULE:FREQ=MONTHLY;BYDAY=-1SU which is correct too and we sync it correctly to Outlook, so a workaround would be to generate that recurrence in Posteo and sync it.

The other error I can't reproduce with that event, must be something else on the server side, never seen <s:message>Undefined variable: propertyList</s:message> before.

**Comment by aluxnimm** [comment]
See also https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/58/

**Comment by dollydl** [comment]
Thanks for your fast response. I will report the issue to Posteo.

Best regards
Uwe
