### ISSUE TITLE
Auto update / Update checking

### ISSUE THREAD

**Issue by extremeshok** [aluxnimm/outlookcaldavsynchronizer#89]
Would it be possible to add auto update / update checking ?

Seems your updates are extremely frequent which is a good thing, problem is we always land up being out of date.

Thanks

**Comment by aluxnimm** [comment]
update checking is already available. we need to investigate the possibility to automatically download and install the update. would also need to restart outlook then.

**Comment by aluxnimm** [comment]
Improved the update checker to provide the possibility to automatically download and unzip the new version and start the setup.exe. You only need to restart Outlook manually after that.
Will be in the next release.

**Comment by may-bee** [comment]
I observed, that outlookcalcdavsync installer is not aware of already installed versions.
This is interesting according to the installation path. If I would have installed this in a different path, running the next update's setup, the installation path will be the standard one.
Is there a way to adapt the assumed installation path accordingly? If yes, you could also automatically install the update.

**Comment by aluxnimm** [comment]
Not possible atm, but the installer will be changed if we find time, all users install doesn't work either, see https://sourceforge.net/p/outlookcaldavsynchronizer/features/18/
