### ISSUE TITLE
Contacts with contact photos not synchronized

### ISSUE THREAD

**Issue by somova** [aluxnimm/outlookcaldavsynchronizer#90]
Hi,

I tried out the Caldavsynchronizer for synchronizing Outlook contacts (calendars and tasks currently not tested) and it works fine but synchronizing contacts containing a contact photo will result in an error (see below):

Dependencies:
- Outlook 2007 (12.0.6739.5000)
- Caldavsynchronizer: v.1.12.0
- Carddav server: Synology DSM 5.2 (same results with Baikal and Owncloud)

[contact_sync_error.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/76674/contact_sync_error.txt)

**Comment by aluxnimm** [comment]
Do you use an exchange profile or a local contact folder? We tested this feature only with OL 2010 and 2013. Do you have access to that for testing?

**Comment by somova** [comment]
I have a local contact folder (outlook pst file in local user profile). Sorry I do not own OL 2010 and therefore I am unable to test it. When I remove the contact photo from a specific contact, it will be synchronized, too.

**Comment by aluxnimm** [comment]
Ok tested again with OL2010 and 2013. No problems there. Then I guess the property needed to access the file doesn't work in OL 2007. Latest commits catch the exception and add the possibility to disable sync of contact photos. Will be in next release.
