### ISSUE TITLE
Cannot create new calendars via folder select wizard in Outlook2013

### ISSUE THREAD

**Issue by may-bee** [aluxnimm/outlookcaldavsynchronizer#94]
Choosing an Outlook folder for synchronization allows e.g. to create new calendars.
Creating a new one within the selection wizard works for Outlook2010, but not for Outlook2013.
For the latter one, the wizard will always create folder entries:

![outlooksyncbug](https://cloud.githubusercontent.com/assets/1427255/12101052/f5122b96-b332-11e5-8f29-7720f16624ba.PNG)

**Comment by aluxnimm** [comment]
Noticed that aswell, but that is the Outlook dialog itself, nothing from our plugin, so not our fault :)
After restarting Outlook it is shown as calendar folder btw.

**Comment by may-bee** [comment]
Nice catch :)
I already observed, that Outlook 2013 is much more buggy than the previous versions...

Nevertheless, the usability has been improved ^^
