### ISSUE TITLE
Error in Outlook 2007 since Update to 1.13

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [aluxnimm/outlookcaldavsynchronizer#96]
Hi there,
first of all, thank you for making this awesome plugin! It is so useful.

However it looks like something broke with the last update. The sync to my owncloud calendars and back still works fine, but I get the following error popping up on each sync:

    <?xml version="1.0" encoding="utf-16"?>
    <SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <ProfileName>OC</ProfileName>
      <ProfileId>8e3d561b-2db0-47ad-ac1a-990d6c76c2e9</ProfileId>
      <StartTime>2016-01-06T07:23:57.7139075Z</StartTime>
      <InitialEntityMatchingPerformed>false</InitialEntityMatchingPerformed>
      <ADelta>Unchanged: 51 , Added: 7 , Deleted 0 ,  Changed 0</ADelta>
      <BDelta>Unchanged: 51 , Added: 0 , Deleted 0 ,  Changed 0</BDelta>
      <LoadErrors />
      <EntitySynchronizationReports>
        <EntitySynchronizationReport>
          <MappingErrors />
          <AId>000000009A10AF670C4E4FE8BFAC47D5E70117D9010000000500000002C7B0D1DA8F2E4E8A630273622E33E100000000</AId>
          <BId />
          <ExceptionThatLeadToAbortion>System.Runtime.InteropServices.COMException (0x8004010F): Die http://schemas.microsoft.com/mapi/proptag/0x00410102-Eigenschaft ist unbekannt oder wurde nicht gefunden.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.Events.EventEntityMapper.GetEventOrganizer(AppointmentItem source)
       bei CalDavSynchronizer.Implementation.Events.EventEntityMapper.MapOrganizer1To2(AppointmentItem source, IEvent target)
       bei CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map1To2(AppointmentItem source, IEvent target, Boolean isRecurrenceException, iCalTimeZone startIcalTimeZone, iCalTimeZone endIcalTimeZone)
       bei CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map1To2(AppointmentItemWrapper sourceWrapper, IICalendar existingTargetCalender, IEntityMappingLogger logger)
       bei GenSync.Synchronization.States.CreateInB`6.&lt;&gt;c__DisplayClass2.&lt;PerformSyncActionNoThrow&gt;b__0(TBtypeEntity b)
       bei CalDavSynchronizer.Implementation.CalDavRepository.&lt;Create&gt;d__15.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei GenSync.Synchronization.States.CreateInB`6.&lt;PerformSyncActionNoThrow&gt;d__4.MoveNext()</ExceptionThatLeadToAbortion>
        </EntitySynchronizationReport>
        <EntitySynchronizationReport>
          <MappingErrors />
          <AId>000000009A10AF670C4E4FE8BFAC47D5E70117D9010000000500000074226A253653854AA0648EB77C4E0C4000000000</AId>
          <BId />
          <ExceptionThatLeadToAbortion>System.Runtime.InteropServices.COMException (0x8004010F): Die http://schemas.microsoft.com/mapi/proptag/0x00410102-Eigenschaft ist unbekannt oder wurde nicht gefunden.
       bei Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
       bei CalDavSynchronizer.Implementation.Events.EventEntityMapper.GetEventOrganizer(AppointmentItem source)
       bei CalDavSynchronizer.Implementation.Events.EventEntityMapper.MapOrganizer1To2(AppointmentItem source, IEvent target)
       bei CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map1To2(AppointmentItem source, IEvent target, Boolean isRecurrenceException, iCalTimeZone startIcalTimeZone, iCalTimeZone endIcalTimeZone)
       bei CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map1To2(AppointmentItemWrapper sourceWrapper, IICalendar existingTargetCalender, IEntityMappingLogger logger)
       bei GenSync.Synchronization.States.CreateInB`6.&lt;&gt;c__DisplayClass2.&lt;PerformSyncActionNoThrow&gt;b__0(TBtypeEntity b)
       bei CalDavSynchronizer.Implementation.CalDavRepository.&lt;Create&gt;d__15.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei GenSync.Synchronization.States.CreateInB`6.&lt;PerformSyncActionNoThrow&gt;d__4.MoveNext()</ExceptionThatLeadToAbortion>
        </EntitySynchronizationReport>
      </EntitySynchronizationReports>
      <Duration>00:00:06.3960113</Duration>
    </SynchronizationReport>

**Comment by aluxnimm** [comment]
I don't think this has anything to do with the update, we didn't change anything in the GetEventOrganizer() code. PierreMarieBaty comitted that months ago.

Somehow the organizer can't be accessed. Can you check if a new event with organizer and attendees you create can be synced?

You can also disable syncing attendees and organizer in advanced options - mapping configuration to avoid that error but I will catch that exception and return no organizer in that case. Fix will be in next release.

**Comment by aluxnimm** [comment]
can you try
https://sourceforge.net/projects/outlookcaldavsynchronizer/files/1.13.1_Test/

**Comment by 1337sup3rh4x0r** [comment]
Your magic trick worked, no more errors. Thank you!
