### ISSUE TITLE
Outlook stalls when sync is running

### ISSUE THREAD

**Issue by Kugeleis** [aluxnimm/outlookcaldavsynchronizer#97]
When the sync is in progress my outlook is not usable. It reacts with massive delay and Windows proposes to close the non-reacting application. (outlook 2010 on windows 7 prof 32bit)
In the log I find hints for the reason:
* attachments too big: System.Runtime.InteropServices.COMException (0xB1704005): Die Anlagengröße überschreitet das erlaubte Maximum.
* too many open elements: System.Runtime.InteropServices.COMException (0xAF540305): Die Anzahl der Elemente, die gleichzeitig geöffnet werden können, wurde vom Serveradministrator begrenzt. Schließen Sie zunächst geöffnete Nachrichten, oder entfernen Sie Anhänge und Bilder von ungesendeten Nachrichten, die Sie gerade verfassen.

Is there a way to avoid this? The calendar items are not by me and I can't change them. I see some appointments with no attachments but many attendies with an item size >1MB.

**Comment by aluxnimm** [comment]
do you only sync calendar or also contacts? for calendar we don't sync attachments at all. but you could disable sync attendees and organizer and body of appointments  in advanced options - mapping configuration. for contacts you can disable sync of contact pictures.

**Comment by Kugeleis** [comment]
I sync only the calender. In advanced options I disabled attendees already. I will try it with disabled body now.

**Comment by Kugeleis** [comment]
It still stalls with everyhing disabled.
![2016-01-06 12_39_21-appointment mapping](https://cloud.githubusercontent.com/assets/9948777/12141768/ae1f831e-b472-11e5-92ae-3d71cb82e08e.png)

**Comment by aluxnimm** [comment]
Can you attach the full debug log

**Comment by Kugeleis** [comment]
here you go 
[log.zip](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/79738/log.zip)

**Comment by aluxnimm** [comment]
Ok there are issues with recurrence exceptions and getting mail adress of attendees. Those should be fixed with latest commits which will be in next release. But I can build you a test release 1.13.1 and you can check it

**Comment by aluxnimm** [comment]
https://sourceforge.net/projects/outlookcaldavsynchronizer/files/1.13.1_Test/

**Comment by Kugeleis** [comment]
This actually seems to fix it. No error log comes up. Sync time dropped from 4 minutes to 9 seconds. Thanks, great work & great support.

**Comment by aluxnimm** [comment]
good news thx for testing

**Comment by aluxnimm** [comment]
Fixed in new release 1.13.2.
