### ISSUE TITLE
Outlook and Zimbra 7.2 Calendar sync issues

### ISSUE THREAD

**Issue by internaut19** [aluxnimm/outlookcaldavsynchronizer#98]
Hi,

First of all, thanks for this wonderful Outlook plugin.

I do have a problem with it, when I'm trying to sync Zimbra 7.2 Calendar with Outlook, I get the message from the attached file.
The Contacts and Tasks sync works nicely.

Thanks.

[Desktop.zip](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/80988/Desktop.zip)

**Comment by aluxnimm** [comment]
are you using outlook 2007?

the error will be fixed in next release. meanwhile you can disable mapping of attendees and organizer in advanced options - mapping configuration.

**Comment by internaut19** [comment]
Yes, Outlook 2007 and after a disabled the mapping of attendees and organizer the error went away.

Looking forward for the next release.

**Comment by aluxnimm** [comment]
Fixed in 1.13.2
